import re

# This script will replace all remaining `"word": "something 2"` in learn.py with synonyms

REPLACEMENTS = {
  "goal 2": "target",
  "deal 2": "transaction",
  "profit 2": "gain",
  "cost 2": "expense",
  "contract 2": "agreement",
  "partner 2": "associate",
  "invest 2": "fund",
  "budget 2": "allowance",
  "income 2": "revenue",
  "tax 2": "duty",
  "import 2": "inbound",
  "export 2": "outbound",
  "molecular gastronomy 2": "modern cuisine",
  "umami glutamate 2": "savory essence",
  "deconstructivism (fashion) 2": "avant-garde fashion",
  "fashion theory 2": "style philosophy",
  "quantitative easing 2": "monetary expansion",
  "symptom 2": "sign",
  "work 2": "labor",
  "job 2": "occupation",
  "boss 2": "manager",
  "office 2": "workplace",
  "team 2": "squad",
  "meeting 2": "gathering",
  "money 2": "cash",
  "break 2": "pause",
  "salary 2": "wage",
  "colleague 2": "coworker",
  "schedule 2": "timetable",
  "deadline 2": "time limit",
  "overtime 2": "extra hours",
  "resume 2": "curriculum vitae",
  "apply 2": "enroll",
  "hire 2": "recruit",
  "career 2": "profession",
  "promotion 2": "advancement",
  "freelancer 2": "independent contractor",
  "remote work 2": "telecommuting",
  "networking 2": "connecting",
  "skill set 2": "expertise",
  "reference 2": "recommendation",
  "workplace 2": "workspace",
  "compensation 2": "remuneration",
  "corporate culture 2": "company culture",
  "headhunter 2": "recruiter",
  "probation 2": "trial period",
  "redundancy 2": "layoff",
  "appraisal 2": "evaluation",
  "outsourcing 2": "subcontracting",
  "turnover 2": "staff turnover",
  "meritocracy 2": "skill-based system",
  "glass ceiling 2": "invisible barrier",
  "occupational hazard 2": "workplace risk",
  "sabbatical 2": "leave of absence",
  "moonlighting 2": "second job",
  "golden parachute 2": "severance package",
  "whistleblower 2": "informant",
  "non-compete clause 2": "restriction clause",
  "shop 2": "store",
  "buy 2": "purchase",
  "sell 2": "vend",
  "price 2": "rate",
  "cheap 2": "inexpensive",
  "brand 2": "trademark",
  "advert 2": "advertisement",
  "poster 2": "banner",
  "customer 2": "client",
  "product 2": "item",
  "discount 2": "reduction",
  "promotion 2": "marketing",
  "market 2": "marketplace",
  "survey 2": "poll",
  "logo 2": "emblem",
  "offer 2": "proposal",
  "target audience 2": "target demographic",
  "campaign 2": "drive",
  "branding 2": "identity",
  "analytics 2": "data analysis",
  "conversion 2": "transition",
  "engagement 2": "interaction",
  "influencer 2": "trendsetter",
  "content marketing 2": "digital content",
  "segmentation 2": "division",
  "market penetration 2": "market share",
  "brand equity 2": "brand value",
  "omnichannel 2": "multichannel",
  "lead generation 2": "lead capture",
  "A/B testing 2": "split testing",
  "ROI 2": "return on investment",
  "viral marketing 2": "buzz marketing",
  "brand dilution 2": "brand weakening",
  "psychographics 2": "psychological profiling",
  "programmatic advertising 2": "automated ads",
  "attribution modeling 2": "attribution analysis",
  "guerrilla marketing 2": "unconventional marketing",
  "neuromarketing 2": "consumer neuroscience",
  "customer lifetime value 2": "CLV",
  "market saturation 2": "market capacity",
  "social media marketing 2": "social advertising",
  "phone 2": "telephone",
  "screen 2": "display",
  "camera 2": "lens",
  "tablet 2": "pad",
  "video 2": "clip",
  "game 2": "match",
  "internet 2": "net",
  "email 2": "electronic mail",
  "smartphone 2": "mobile",
  "battery 2": "power cell",
  "download 2": "fetch",
  "website 2": "site",
  "password 2": "passcode",
  "update 2": "upgrade",
  "connect 2": "link",
  "message 2": "text",
  "innovation 2": "invention",
  "bandwidth 2": "capacity",
  "cybersecurity 2": "IT security",
  "cloud computing 2": "cloud tech",
  "virtual reality 2": "VR",
  "wearable 2": "smart tech",
  "streaming 2": "broadcasting",
  "gadget 2": "device",
  "augmented reality 2": "AR",
  "blockchain 2": "distributed ledger",
  "quantum computing 2": "quantum tech",
  "biometrics 2": "biometric scanning",
  "IoT 2": "Internet of Things",
  "encryption 2": "cryptography",
  "scalability 2": "adaptability",
  "microchip 2": "processor",
  "ubiquitous computing 2": "pervasive computing",
  "disruptive technology 2": "groundbreaking tech",
  "nanotechnology 2": "nanotech",
  "algorithmic bias 2": "AI bias",
  "digital sovereignty 2": "digital autonomy",
  "transhumanism 2": "posthumanism",
  "interoperability 2": "compatibility",
  "proprietary 2": "patented",
  "Airport 2": "Aerodrome",
  "Luggage 2": "Baggage",
  "Journey 2": "Voyage",
  "Tourist 2": "Visitor",
  "Flight 2": "Aviation",
  "Station 2": "Terminal",
  "Guide 2": "Escort",
  "Souvenir 2": "Keepsake",
  "Expedition 2": "Trek",
  "Picturesque 2": "Scenic",
  "Breathtaking 2": "Stunning",
  "Hospitable 2": "Welcoming",
  "Spectacular 2": "Magnificent",
  "Wilderness 2": "Outback",
  "Sightseeing 2": "Touring",
  "Transcontinental 2": "Cross-country",
  "Sojourn 2": "Stay",
  "Uncharted 2": "Undiscovered",
  "Peregrination 2": "Roaming",
  "Globetrotter 2": "World traveler",
  "Bespoke 2": "Custom-made",
  "Wanderlust 2": "Travel bug",
  "Unspoiled 2": "Pristine",
  "Vagabond 2": "Nomad"
}

FILE_PATH = 'e:/Project/Hoc/hoc-tieng-anh/backend/app/api/v1/endpoints/learn.py'
with open(FILE_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

count = 0
for k, v in REPLACEMENTS.items():
    # replace `"word": "k"` with `"word": "v"`
    # using literal string replacement for safety
    old_str = f'"word": "{k}"'
    new_str = f'"word": "{v}"'
    if old_str in content:
        content = content.replace(old_str, new_str)
        count += 1

with open(FILE_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Replaced {count} instances.")

# Check if any " 2" are left
left = re.findall(r'"word":\s*"([^"]+) 2"', content)
print("Remaining with suffix ' 2':", len(left))
