# Từ vựng Tech A1-C1 (50 từ mỗi cấp, tránh trùng)
# Đã có: camera, clip, display, electronic mail, email (A1); battery, cellphone, charger, connect, download (A2)
# bandwidth, broadcasting, capacity, cloud computing, cloud tech (B1)

TECH_A1 = [
    ("phone", "/foʊn/", "điện thoại", "I call my friend on my phone."),
    ("computer", "/kəmˈpjuː.tər/", "máy tính", "I use a computer for my homework."),
    ("internet", "/ˈɪn.tər.nɛt/", "mạng internet", "The internet connects billions of people."),
    ("app", "/æp/", "ứng dụng trên điện thoại", "Download the app for free."),
    ("screen", "/skriːn/", "màn hình thiết bị", "The phone screen is very bright."),
    ("keyboard", "/ˈkiː.bɔːrd/", "bàn phím máy tính", "Type on the keyboard to enter text."),
    ("mouse", "/maʊs/", "chuột máy tính", "Click the mouse to open the file."),
    ("printer", "/ˈprɪn.tər/", "máy in tài liệu", "Print the document on the printer."),
    ("speaker", "/ˈspiː.kər/", "loa âm thanh", "The speaker makes very clear sound."),
    ("headphones", "/ˈhɛd.foʊnz/", "tai nghe", "Use headphones to listen to music."),
    ("cable", "/ˈkeɪ.bəl/", "dây cáp kết nối", "Connect using a USB cable."),
    ("plug", "/plʌɡ/", "phích cắm điện", "Plug the device into the socket."),
    ("power", "/ˈpaʊ.ər/", "nguồn điện", "The device runs on battery power."),
    ("memory", "/ˈmɛm.ər.i/", "bộ nhớ thiết bị", "Buy more memory for your computer."),
    ("file", "/faɪl/", "tập tin, file dữ liệu", "Save the file before closing."),
    ("folder", "/ˈfoʊl.dər/", "thư mục chứa file", "Put the file in the correct folder."),
    ("icon", "/ˈaɪ.kɒn/", "biểu tượng ứng dụng", "Click the icon to open the app."),
    ("menu", "/ˈmɛn.juː/", "thanh menu điều hướng", "Select the option from the menu."),
    ("button", "/ˈbʌt.ən/", "nút bấm giao diện", "Press the button to start."),
    ("link", "/lɪŋk/", "đường dẫn liên kết", "Click the link to visit the website."),
    ("website", "/ˈwɛb.saɪt/", "trang web", "Visit our website for more info."),
    ("page", "/peɪdʒ/", "trang web cụ thể", "Open a new page in the browser."),
    ("browser", "/ˈbraʊ.zər/", "trình duyệt web", "Use a browser to access websites."),
    ("search", "/sɜːrtʃ/", "tìm kiếm trên web", "Search for the answer online."),
    ("upload", "/ˈʌp.loʊd/", "tải lên máy chủ", "Upload the photo to social media."),
    ("photo", "/ˈfoʊ.toʊ/", "bức ảnh kỹ thuật số", "Take a photo with your phone."),
    ("video", "/ˈvɪd.i.oʊ/", "video kỹ thuật số", "Watch a video on YouTube."),
    ("music", "/ˈmjuː.zɪk/", "âm nhạc kỹ thuật số", "Listen to music on your phone."),
    ("game", "/ɡeɪm/", "trò chơi điện tử", "Play an online game with friends."),
    ("chat", "/tʃæt/", "trò chuyện trực tuyến", "Chat with friends on the app."),
    ("share", "/ʃɛər/", "chia sẻ nội dung", "Share the photo with your friends."),
    ("save", "/seɪv/", "lưu dữ liệu", "Save the document before closing."),
    ("delete", "/dɪˈliːt/", "xóa dữ liệu", "Delete old files to free up space."),
    ("open", "/ˈoʊ.pən/", "mở file hoặc ứng dụng", "Open the file from the folder."),
    ("close", "/kloʊz/", "đóng chương trình", "Close all unused applications."),
    ("start", "/stɑːrt/", "khởi động thiết bị", "Start the computer by pressing power."),
    ("stop", "/stɒp/", "dừng hoạt động", "Stop the download now."),
    ("connect", "/kəˈnɛkt/", "kết nối thiết bị", "Connect to the WiFi network."),
    ("wifi", "/ˈwaɪ.faɪ/", "mạng wifi không dây", "Connect to the home wifi."),
    ("signal", "/ˈsɪɡ.nəl/", "tín hiệu mạng", "The signal is weak here."),
    ("update", "/ˈʌp.deɪt/", "cập nhật phần mềm", "Update your app for the best features."),
    ("install", "/ɪnˈstɔːl/", "cài đặt phần mềm", "Install the program on your computer."),
    ("password", "/ˈpæs.wɜːrd/", "mật khẩu bảo mật", "Enter your password to log in."),
    ("login", "/ˈlɒɡ.ɪn/", "đăng nhập tài khoản", "Login to access your account."),
    ("account", "/əˈkaʊnt/", "tài khoản trực tuyến", "Create an account to use the service."),
    ("notification", "/ˌnoʊ.tɪ.fɪˈkeɪ.ʃən/", "thông báo trên thiết bị", "Turn off notifications at night."),
    ("settings", "/ˈsɛt.ɪŋz/", "cài đặt hệ thống", "Change the settings in the app."),
    ("data", "/ˈdeɪ.tə/", "dữ liệu kỹ thuật số", "Back up your data regularly."),
    ("storage", "/ˈstɔːr.ɪdʒ/", "không gian lưu trữ", "The phone has 128GB of storage."),
    ("tablet", "/ˈtæb.lɪt/", "máy tính bảng", "Use a tablet for reading and drawing."),
]

TECH_A2 = [
    ("software", "/ˈsɒft.weər/", "phần mềm ứng dụng", "Install the latest software version."),
    ("hardware", "/ˈhɑːrd.weər/", "phần cứng máy tính", "Upgrade the hardware for better performance."),
    ("processor", "/ˈprɒs.ɛs.ər/", "bộ vi xử lý trung tâm", "A faster processor speeds up your computer."),
    ("RAM", "/ræm/", "bộ nhớ truy cập ngẫu nhiên", "Add more RAM for multitasking."),
    ("SSD", "/ˌɛs.ɛsˈdiː/", "ổ cứng thể rắn nhanh", "An SSD makes the computer boot faster."),
    ("graphics card", "/ˈɡræf.ɪks kɑːrd/", "card đồ họa xử lý hình ảnh", "A good graphics card is needed for gaming."),
    ("monitor", "/ˈmɒn.ɪ.tər/", "màn hình hiển thị máy tính", "A large monitor improves productivity."),
    ("laptop", "/ˈlæp.tɒp/", "máy tính xách tay", "I carry my laptop to work every day."),
    ("desktop", "/ˈdɛsk.tɒp/", "máy tính để bàn", "A desktop is more powerful than a laptop."),
    ("network", "/ˈnɛt.wɜːrk/", "mạng lưới máy tính", "Connect all devices to the same network."),
    ("router", "/ˈruː.tər/", "bộ định tuyến mạng", "The router distributes internet to all devices."),
    ("modem", "/ˈmoʊ.dɛm/", "thiết bị kết nối internet", "The modem connects you to the internet."),
    ("bluetooth", "/ˈbluː.tuːθ/", "kết nối không dây Bluetooth", "Pair your phone via Bluetooth."),
    ("GPS", "/ˌdʒiː.piːˈɛs/", "hệ thống định vị toàn cầu", "The GPS shows your exact location."),
    ("USB", "/ˌjuː.ɛsˈbiː/", "cổng kết nối USB phổ biến", "Plug in the USB drive to transfer files."),
    ("backup", "/ˈbæk.ʌp/", "sao lưu dữ liệu an toàn", "Always back up your important files."),
    ("virus", "/ˈvaɪ.rəs/", "phần mềm độc hại virus", "Install antivirus to protect your computer."),
    ("antivirus", "/ˌæn.tiˈvaɪ.rəs/", "phần mềm diệt virus", "Run antivirus scans weekly."),
    ("firewall", "/ˈfaɪər.wɔːl/", "tường lửa bảo vệ mạng", "A firewall blocks unauthorized access."),
    ("encryption", "/ɪnˈkrɪp.ʃən/", "mã hóa dữ liệu bảo mật", "Encryption protects your personal data."),
    ("browser extension", "/ˈbraʊ.zər ɪkˈstɛn.ʃən/", "tiện ích mở rộng trình duyệt", "Install a browser extension for ad blocking."),
    ("operating system", "/ˈɒp.ər.eɪ.tɪŋ ˈsɪs.təm/", "hệ điều hành máy tính", "Windows is a popular operating system."),
    ("user interface", "/ˈjuː.zər ˈɪn.tər.feɪs/", "giao diện người dùng", "The user interface is clean and easy."),
    ("database", "/ˈdeɪ.tə.beɪs/", "cơ sở dữ liệu", "Store all records in a database."),
    ("server", "/ˈsɜːr.vər/", "máy chủ dịch vụ", "The server stores all the website data."),
    ("email", "/ˈiː.meɪl/", "thư điện tử", "Send an email to the support team."),
    ("attachment", "/əˈtætʃ.mənt/", "tệp đính kèm email", "Open the email attachment carefully."),
    ("spam", "/spæm/", "email rác không mong muốn", "Delete spam emails immediately."),
    ("subscription", "/səbˈskrɪp.ʃən/", "đăng ký dịch vụ trả phí", "Buy a monthly subscription for the app."),
    ("streaming", "/ˈstriː.mɪŋ/", "phát trực tuyến nội dung số", "Streaming services replaced physical DVDs."),
    ("podcast", "/ˈpɒd.kæst/", "chương trình âm thanh trực tuyến", "Listen to a podcast while commuting."),
    ("social media", "/ˈsoʊ.ʃəl ˈmiː.di.ə/", "mạng xã hội trực tuyến", "Social media connects people worldwide."),
    ("profile", "/ˈproʊ.faɪl/", "hồ sơ tài khoản người dùng", "Update your profile photo."),
    ("post", "/poʊst/", "đăng bài lên mạng xã hội", "Post a photo of your lunch."),
    ("comment", "/ˈkɒm.ənt/", "bình luận dưới bài đăng", "Leave a comment on the post."),
    ("like", "/laɪk/", "bấm thích bài đăng", "Like the post if you enjoy it."),
    ("follow", "/ˈfɒl.oʊ/", "theo dõi tài khoản người dùng", "Follow the official account for updates."),
    ("digital", "/ˈdɪdʒ.ɪ.təl/", "kỹ thuật số, công nghệ số", "Digital payments are fast and secure."),
    ("smart device", "/smɑːrt dɪˈvaɪs/", "thiết bị thông minh kết nối", "A smart device learns your preferences."),
    ("IoT", "/ˌaɪ.oʊˈtiː/", "internet vạn vật kết nối", "IoT connects everyday objects online."),
    ("wearable", "/ˈwɛər.ə.bəl/", "thiết bị đeo tay thông minh", "Smartwatches are popular wearables."),
    ("scanner", "/ˈskæn.ər/", "máy quét tài liệu", "Scan the document with a scanner."),
    ("webcam", "/ˈwɛb.kæm/", "camera web cho video call", "Use a webcam for online meetings."),
    ("microphone", "/ˈmaɪ.krə.foʊn/", "micro thu âm", "Speak clearly into the microphone."),
    ("touchscreen", "/ˈtʌtʃ.skriːn/", "màn hình cảm ứng", "The touchscreen responds to finger touch."),
    ("fingerprint", "/ˈfɪŋ.ɡər.prɪnt/", "vân tay mở khóa thiết bị", "Use fingerprint to unlock your phone."),
    ("face ID", "/feɪs aɪˈdiː/", "nhận dạng khuôn mặt bảo mật", "Face ID unlocks the phone instantly."),
    ("drone", "/droʊn/", "máy bay không người lái", "A drone took aerial photos of the event."),
    ("3D printer", "/ˌθriː diː ˈprɪn.tər/", "máy in 3 chiều", "The 3D printer creates plastic models."),
    ("VR headset", "/ˌviː.ɑːr ˈhɛd.sɛt/", "kính thực tế ảo", "Wear a VR headset to enter virtual worlds."),
]

TECH_B1 = [
    ("API", "/ˌeɪ.piːˈaɪ/", "giao diện lập trình ứng dụng", "Use the API to connect two services."),
    ("SDK", "/ˌɛs.diːˈkeɪ/", "bộ công cụ phát triển phần mềm", "Download the SDK to build your app."),
    ("framework", "/ˈfreɪm.wɜːrk/", "khung phát triển phần mềm", "React is a popular frontend framework."),
    ("open source", "/ˈoʊ.pən sɔːrs/", "phần mềm mã nguồn mở", "Linux is a free open source OS."),
    ("repository", "/rɪˈpɒz.ɪ.tɒr.i/", "kho lưu trữ mã nguồn", "Push your code to the repository."),
    ("version control", "/ˈvɜːr.ʒən kənˈtroʊl/", "quản lý phiên bản mã nguồn", "Use version control to track changes."),
    ("debugging", "/diːˈbʌɡ.ɪŋ/", "gỡ lỗi chương trình", "Debugging takes a lot of patience."),
    ("deployment", "/dɪˈplɔɪ.mənt/", "triển khai phần mềm lên môi trường", "Deployment moved the app to production."),
    ("microservices", "/ˈmaɪ.krə.sɜːr.vɪ.sɪz/", "kiến trúc vi dịch vụ chia nhỏ", "Microservices allow independent scaling."),
    ("containerization", "/kənˌteɪ.nər.ɪˈzeɪ.ʃən/", "đóng gói ứng dụng vào container", "Docker enables containerization of apps."),
    ("DevOps", "/ˈdɛv.ɒps/", "kết hợp phát triển và vận hành", "DevOps speeds up the release cycle."),
    ("agile", "/ˈædʒ.aɪl/", "phương pháp phát triển linh hoạt", "Agile teams work in short sprints."),
    ("scrum", "/skrʌm/", "khung làm việc agile theo sprint", "The scrum meeting is every morning."),
    ("sprint", "/sprɪnt/", "chu kỳ làm việc ngắn agile", "We completed the feature in one sprint."),
    ("backend", "/ˈbæk.ɛnd/", "phần server xử lý logic nghiệp vụ", "The backend handles data processing."),
    ("frontend", "/ˈfrʌnt.ɛnd/", "phần giao diện người dùng web", "The frontend is built with React."),
    ("database management", "/ˈdeɪ.tə.beɪs ˈmæn.ɪdʒ.mənt/", "quản trị cơ sở dữ liệu", "Database management keeps data organized."),
    ("SQL", "/ˈsiː.kwəl/", "ngôn ngữ truy vấn cơ sở dữ liệu", "Use SQL to query the database."),
    ("NoSQL", "/ˌnoʊˈsiː.kwəl/", "cơ sở dữ liệu phi quan hệ linh hoạt", "MongoDB is a popular NoSQL database."),
    ("caching", "/ˈkæʃ.ɪŋ/", "lưu tạm bộ nhớ đệm tăng tốc", "Caching reduces server load significantly."),
    ("load balancing", "/loʊd ˈbæl.ən.sɪŋ/", "cân bằng tải giữa các server", "Load balancing prevents server overload."),
    ("scalability", "/ˌskeɪ.lə.ˈbɪl.ɪ.ti/", "khả năng mở rộng hệ thống", "Good architecture ensures scalability."),
    ("uptime", "/ˈʌp.taɪm/", "thời gian hệ thống hoạt động ổn định", "The server achieved 99.9% uptime."),
    ("latency", "/ˈleɪ.tən.si/", "độ trễ phản hồi hệ thống", "Reduce latency for a better experience."),
    ("throughput", "/ˈθruː.pʊt/", "thông lượng xử lý dữ liệu", "High throughput handles more requests."),
    ("authentication", "/ɔːˌθɛn.tɪˈkeɪ.ʃən/", "xác thực danh tính người dùng", "Two-factor authentication improves security."),
    ("authorization", "/ˌɔː.θər.aɪˈzeɪ.ʃən/", "phân quyền truy cập hệ thống", "Authorization controls user permissions."),
    ("SSL certificate", "/ˌɛs.ɛsˈɛl ˈsɜːr.tɪ.fɪ.kɪt/", "chứng chỉ bảo mật SSL cho web", "SSL certificate encrypts website data."),
    ("protocol", "/ˈproʊ.tə.kɒl/", "giao thức truyền thông mạng", "HTTP is a common web protocol."),
    ("webhook", "/ˈwɛb.hʊk/", "cơ chế gọi lại sự kiện tự động", "A webhook triggers when an event occurs."),
    ("middleware", "/ˈmɪd.əl.weər/", "phần mềm trung gian kết nối", "Middleware connects the frontend and backend."),
    ("monolith", "/ˈmɒn.ə.lɪθ/", "kiến trúc nguyên khối một ứng dụng lớn", "A monolith is easier to develop initially."),
    ("refactoring", "/ˌriːˈfæk.tər.ɪŋ/", "tái cấu trúc mã nguồn cải thiện chất lượng", "Refactoring improves code readability."),
    ("unit test", "/ˈjuː.nɪt tɛst/", "kiểm thử đơn vị từng thành phần nhỏ", "Write unit tests for every function."),
    ("integration test", "/ˌɪn.tɪˈɡreɪ.ʃən tɛst/", "kiểm thử tích hợp nhiều module cùng nhau", "Integration tests check module interaction."),
    ("CI/CD", "/ˌsiː.aɪ.ˌsiːˈdiː/", "tích hợp và triển khai liên tục tự động", "CI/CD automates the deployment pipeline."),
    ("pipeline", "/ˈpaɪp.laɪn/", "luồng xử lý tự động tuần tự", "The CI/CD pipeline runs tests automatically."),
    ("log", "/lɒɡ/", "nhật ký sự kiện hệ thống", "Check the server log for errors."),
    ("monitoring", "/ˈmɒn.ɪ.tər.ɪŋ/", "theo dõi hệ thống liên tục", "Monitoring tools alert you to issues."),
    ("alerting", "/əˈlɜːr.tɪŋ/", "cảnh báo khi có sự cố hệ thống", "Set up alerting for downtime events."),
    ("incident", "/ˈɪn.sɪ.dənt/", "sự cố kỹ thuật cần xử lý ngay", "The incident was resolved in 30 minutes."),
    ("rollback", "/ˈroʊl.bæk/", "quay lại phiên bản trước sau lỗi", "Perform a rollback if the update fails."),
    ("hotfix", "/ˈhɒt.fɪks/", "bản vá lỗi khẩn cấp", "We released a hotfix for the critical bug."),
    ("technical debt", "/ˈtɛk.nɪ.kəl dɛt/", "nợ kỹ thuật do bỏ qua chất lượng", "Accumulated technical debt slows teams down."),
    ("code review", "/koʊd rɪˈvjuː/", "đánh giá mã nguồn của đồng nghiệp", "Code review catches bugs early."),
    ("pull request", "/pʊl rɪˈkwɛst/", "yêu cầu hợp nhất mã nguồn", "Submit a pull request to merge changes."),
    ("merge", "/mɜːrdʒ/", "hợp nhất các nhánh mã nguồn", "Merge the feature branch into main."),
    ("branch", "/bræntʃ/", "nhánh phát triển riêng biệt", "Create a new branch for the feature."),
    ("commit", "/kəˈmɪt/", "ghi nhận thay đổi mã nguồn", "Commit your changes with a clear message."),
    ("documentation", "/ˌdɒk.jʊ.mɛnˈteɪ.ʃən/", "tài liệu hướng dẫn kỹ thuật", "Write clear documentation for the API."),
]

TECH_B2 = [
    ("distributed system", "/dɪˈstrɪb.jʊ.tɪd ˈsɪs.təm/", "hệ thống phân tán nhiều node", "Distributed systems handle massive traffic."),
    ("consensus algorithm", "/kənˈsɛn.səs ˈæl.ɡə.rɪ.ðəm/", "thuật toán đồng thuận trong hệ phân tán", "Raft is a consensus algorithm for clusters."),
    ("eventual consistency", "/ɪˈvɛn.tʃʊ.əl kənˈsɪs.tən.si/", "tính nhất quán cuối cùng trong phân tán", "Eventual consistency trades consistency for availability."),
    ("CAP theorem", "/kæp ˈθɪər.əm/", "định lý CAP về hệ thống phân tán", "The CAP theorem limits distributed systems."),
    ("sharding", "/ˈʃɑːr.dɪŋ/", "phân mảnh dữ liệu theo chiều ngang", "Database sharding improves read performance."),
    ("replication", "/ˌrɛp.lɪˈkeɪ.ʃən/", "sao chép dữ liệu sang nhiều node", "Data replication ensures high availability."),
    ("fault tolerance", "/fɔːlt ˈtɒl.ər.əns/", "khả năng chịu lỗi của hệ thống", "Fault tolerance keeps services running."),
    ("observability", "/əbˌzɜːr.vəˈbɪl.ɪ.ti/", "khả năng quan sát toàn diện hệ thống", "Observability includes logs, metrics, traces."),
    ("tracing", "/ˈtreɪ.sɪŋ/", "theo dõi luồng yêu cầu qua hệ thống", "Distributed tracing finds performance bottlenecks."),
    ("service mesh", "/ˈsɜːr.vɪs mɛʃ/", "lưới dịch vụ quản lý giao tiếp microservice", "A service mesh manages microservice traffic."),
    ("Kubernetes", "/ˌkjuː.bərˈniː.tɪs/", "nền tảng điều phối container phổ biến", "Kubernetes orchestrates containerized workloads."),
    ("Docker", "/ˈdɒk.ər/", "công cụ container hóa ứng dụng", "Docker packages apps in containers."),
    ("infrastructure as code", "/ˈɪn.frə.strʌk.tʃər æz koʊd/", "quản lý hạ tầng bằng mã nguồn", "Terraform enables infrastructure as code."),
    ("serverless", "/ˈsɜːr.vər.lɪs/", "điện toán không máy chủ trả theo dùng", "Serverless functions scale automatically."),
    ("edge computing", "/ɛdʒ kəmˈpjuː.tɪŋ/", "điện toán tại biên gần nguồn dữ liệu", "Edge computing reduces cloud latency."),
    ("message queue", "/ˈmɛs.ɪdʒ kjuː/", "hàng đợi tin nhắn giữa các dịch vụ", "A message queue decouples services."),
    ("event-driven", "/ɪˈvɛnt ˈdrɪv.ən/", "kiến trúc hướng sự kiện phản ứng", "Event-driven systems react to state changes."),
    ("data pipeline", "/ˈdeɪ.tə ˈpaɪp.laɪn/", "luồng xử lý dữ liệu từ đầu đến cuối", "A data pipeline moves data from source to warehouse."),
    ("data warehouse", "/ˈdeɪ.tə ˈweər.haʊs/", "kho dữ liệu lớn phục vụ phân tích", "The data warehouse stores historical reports."),
    ("ETL", "/ˌiː.tiːˈɛl/", "trích xuất chuyển đổi và tải dữ liệu", "ETL pipelines prepare raw data for analysis."),
    ("real-time processing", "/ˌriːl ˈtaɪm ˈprɒs.ɛs.ɪŋ/", "xử lý dữ liệu theo thời gian thực", "Real-time processing powers live dashboards."),
    ("stream processing", "/striːm ˈprɒs.ɛs.ɪŋ/", "xử lý luồng dữ liệu liên tục", "Kafka enables stream processing at scale."),
    ("cryptography", "/krɪpˈtɒɡ.rə.fi/", "mật mã học bảo vệ dữ liệu", "Cryptography underlies all internet security."),
    ("zero-trust", "/ˈzɪər.oʊ trʌst/", "mô hình bảo mật không tin tưởng mặc định", "Zero-trust assumes no user is trusted."),
    ("penetration testing", "/ˌpɛn.ɪˈtreɪ.ʃən ˈtɛs.tɪŋ/", "kiểm tra xâm nhập tìm lỗ hổng bảo mật", "Penetration testing finds security vulnerabilities."),
    ("vulnerability", "/ˌvʌl.nər.əˈbɪl.ɪ.ti/", "lỗ hổng bảo mật trong hệ thống", "Patch all known vulnerabilities quickly."),
    ("exploit", "/ˈɛk.splɔɪt/", "khai thác lỗ hổng tấn công hệ thống", "Hackers use exploits to breach systems."),
    ("phishing", "/ˈfɪʃ.ɪŋ/", "tấn công giả mạo lừa đảo thông tin", "Phishing emails steal login credentials."),
    ("ransomware", "/ˈræn.səm.weər/", "phần mềm mã độc đòi tiền chuộc", "Ransomware encrypts files and demands payment."),
    ("zero-day", "/ˈzɪər.oʊ deɪ/", "lỗ hổng chưa được vá bởi nhà phát triển", "Zero-day exploits are especially dangerous."),
    ("dark web", "/dɑːrk wɛb/", "mạng internet ẩn truy cập qua Tor", "Stolen data is sold on the dark web."),
    ("blockchain", "/ˈblɒk.tʃeɪn/", "công nghệ chuỗi khối phi tập trung", "Blockchain ensures tamper-proof records."),
    ("smart contract", "/smɑːrt ˈkɒn.trækt/", "hợp đồng thông minh tự động thực thi", "Smart contracts execute automatically on blockchain."),
    ("decentralized", "/diːˈsɛn.trə.laɪzd/", "phi tập trung không có cơ quan kiểm soát", "Decentralized apps run on blockchain."),
    ("token economy", "/ˈtoʊ.kən ɪˈkɒn.ə.mi/", "nền kinh tế token trong hệ sinh thái số", "A token economy rewards platform participants."),
    ("WebAssembly", "/ˌwɛb.əˈsɛm.bli/", "ngôn ngữ trung gian web hiệu suất cao", "WebAssembly runs near-native code in browsers."),
    ("PWA", "/ˌpiː.dʌb.ljuːˈeɪ/", "ứng dụng web tiến bộ chạy offline", "A PWA works offline like a native app."),
    ("GraphQL", "/ˈɡræf.kjuː.ɛl/", "ngôn ngữ truy vấn API linh hoạt", "GraphQL lets clients request specific data."),
    ("REST API", "/rɛst ˌeɪ.piːˈaɪ/", "kiến trúc API theo phong cách REST", "A REST API uses HTTP methods for requests."),
    ("OAuth", "/ˈoʊ.ɔːθ/", "giao thức ủy quyền truy cập mở", "OAuth allows third-party login."),
    ("JWT", "/ˌdʒeɪ.dʌb.ljuːˈtiː/", "token xác thực JSON phi trạng thái", "JWT tokens verify user identity securely."),
    ("TDD", "/ˌtiː.diːˈdiː/", "phát triển hướng kiểm thử trước khi code", "TDD requires writing tests before code."),
    ("BDD", "/ˌbiː.diːˈdiː/", "phát triển hướng hành vi người dùng", "BDD describes features in plain language."),
    ("design pattern", "/dɪˈzaɪn ˈpæt.ərn/", "mẫu thiết kế giải quyết vấn đề phổ biến", "The singleton is a common design pattern."),
    ("SOLID principles", "/ˈsɒl.ɪd ˈprɪn.sɪ.pəlz/", "nguyên lý thiết kế phần mềm hướng đối tượng", "SOLID principles guide clean code design."),
    ("clean code", "/kliːn koʊd/", "mã nguồn sạch dễ đọc và bảo trì", "Clean code is easy to read and maintain."),
    ("code smell", "/koʊd smɛl/", "dấu hiệu mã nguồn kém chất lượng", "A code smell suggests refactoring is needed."),
    ("pair programming", "/pɛər ˈproʊ.ɡræm.ɪŋ/", "lập trình đôi cùng một máy tính", "Pair programming catches errors early."),
    ("mob programming", "/mɒb ˈproʊ.ɡræm.ɪŋ/", "lập trình nhóm toàn bộ trên cùng task", "Mob programming builds shared understanding."),
    ("technical specification", "/ˈtɛk.nɪ.kəl ˌspɛs.ɪ.fɪˈkeɪ.ʃən/", "bản đặc tả kỹ thuật chi tiết dự án", "Write a technical specification before coding."),
    ("architecture decision record", "/ˈɑːr.kɪ.tɛk.tʃər dɪˈsɪʒ.ən ˈrɛk.ərd/", "ghi lại quyết định kiến trúc quan trọng", "ADRs document why architecture choices were made."),
]

TECH_C1 = [
    ("neuromorphic computing", "/ˌnjʊər.oʊˈmɔːr.fɪk kəmˈpjuː.tɪŋ/", "điện toán mô phỏng kiến trúc não bộ", "Neuromorphic computing mimics brain structure."),
    ("quantum computing", "/ˈkwɒn.təm kəmˈpjuː.tɪŋ/", "điện toán lượng tử dùng qubit", "Quantum computing solves complex optimization problems."),
    ("qubit", "/ˈkjuː.bɪt/", "bit lượng tử có thể ở trạng thái chồng chất", "A qubit can be 0 and 1 simultaneously."),
    ("superposition", "/ˌsuː.pər.pəˈzɪʃ.ən/", "trạng thái chồng chất lượng tử", "Superposition enables parallel computation."),
    ("quantum entanglement", "/ˈkwɒn.təm ɪnˈtæŋ.ɡəl.mənt/", "vướng mắc lượng tử giữa các qubit", "Quantum entanglement links qubits instantly."),
    ("photonic chip", "/fəˈtɒn.ɪk tʃɪp/", "chip quang tử dùng ánh sáng thay điện", "Photonic chips process data at light speed."),
    ("exascale computing", "/ˈɛk.sə.skeɪl kəmˈpjuː.tɪŋ/", "điện toán exascale vượt 10^18 phép tính", "Exascale computing enables climate simulations."),
    ("formal verification", "/ˈfɔːr.məl ˌvɛr.ɪ.fɪˈkeɪ.ʃən/", "xác minh chính xác toán học của phần mềm", "Formal verification proves program correctness."),
    ("type theory", "/taɪp ˈθɪər.i/", "lý thuyết kiểu dữ liệu trong ngôn ngữ lập trình", "Type theory ensures program correctness."),
    ("dependent types", "/dɪˈpɛn.dənt taɪps/", "kiểu phụ thuộc giá trị trong lập trình", "Dependent types encode invariants in code."),
    ("functional programming", "/ˈfʌŋk.ʃən.əl ˈproʊ.ɡræm.ɪŋ/", "lập trình hàm thuần túy không trạng thái", "Functional programming avoids mutable state."),
    ("monad", "/ˈmɒn.æd/", "cấu trúc đơn nguyên trong lập trình hàm", "Monads handle side effects in functional code."),
    ("lambda calculus", "/ˈlæm.də ˈkæl.kjʊ.ləs/", "phép tính lambda nền tảng lập trình hàm", "Lambda calculus forms the basis of functional languages."),
    ("memory safety", "/ˈmɛm.ər.i ˈseɪf.ti/", "an toàn bộ nhớ ngăn lỗi buffer overflow", "Rust provides memory safety without garbage collection."),
    ("garbage collection", "/ˈɡɑːr.bɪdʒ kəˈlɛk.ʃən/", "thu gom rác giải phóng bộ nhớ tự động", "Garbage collection prevents memory leaks."),
    ("concurrency", "/kənˈkɜːr.ən.si/", "lập trình đồng thời xử lý nhiều tác vụ", "Concurrency improves application responsiveness."),
    ("parallelism", "/ˈpær.ə.lɛl.ɪzm/", "song song hóa thực sự trên nhiều nhân CPU", "Parallelism uses multiple CPU cores simultaneously."),
    ("async programming", "/eɪˈsɪŋk ˈproʊ.ɡræm.ɪŋ/", "lập trình bất đồng bộ không chặn luồng chính", "Async programming prevents blocking the main thread."),
    ("event loop", "/ɪˈvɛnt luːp/", "vòng lặp sự kiện xử lý I/O bất đồng bộ", "Node.js uses an event loop for non-blocking I/O."),
    ("actor model", "/ˈæk.tər ˈmɒd.əl/", "mô hình diễn viên xử lý đồng thời qua tin nhắn", "The actor model avoids shared memory issues."),
    ("CRDT", "/ˌsiː.ɑːr.diːˈtiː/", "kiểu dữ liệu hội tụ phân tán nhất quán", "CRDTs enable conflict-free distributed edits."),
    ("homomorphic encryption", "/ˌhɒm.ə.ˈmɔːr.fɪk ɪnˈkrɪp.ʃən/", "mã hóa đồng cấu tính toán trên dữ liệu mã hóa", "Homomorphic encryption computes on encrypted data."),
    ("zero-knowledge proof", "/ˈzɪər.oʊ ˈnɒl.ɪdʒ pruːf/", "bằng chứng không tiết lộ thông tin bí mật", "Zero-knowledge proofs verify without revealing data."),
    ("post-quantum cryptography", "/ˌpoʊst ˈkwɒn.təm krɪpˈtɒɡ.rə.fi/", "mật mã hậu lượng tử chống máy tính lượng tử", "Post-quantum cryptography resists quantum attacks."),
    ("Byzantine fault", "/ˈbɪz.ən.tiːn fɔːlt/", "lỗi Byzantine khi node gửi thông tin sai", "Byzantine faults occur when nodes send conflicting messages."),
    ("Paxos", "/ˈpæk.sɒs/", "giao thức đồng thuận phân tán cổ điển", "Paxos solves consensus in distributed systems."),
    ("Raft consensus", "/ræft kənˈsɛn.səs/", "thuật toán đồng thuận dễ hiểu hơn Paxos", "Raft consensus is easier to implement than Paxos."),
    ("log-structured merge", "/lɒɡ ˈstrʌk.tʃərd mɜːrdʒ/", "cấu trúc lưu trữ LSM tối ưu ghi dữ liệu", "LSM trees optimize write-heavy workloads."),
    ("column store", "/ˈkɒl.əm stɔːr/", "cơ sở dữ liệu lưu theo cột tối ưu phân tích", "Column stores accelerate analytical queries."),
    ("vector database", "/ˈvɛk.tər ˈdeɪ.tə.beɪs/", "cơ sở dữ liệu vector cho tìm kiếm tương đồng", "Vector databases power semantic search."),
    ("WASM", "/ˈwæz.əm/", "WebAssembly định dạng nhị phân hiệu suất cao", "WASM enables high-performance web applications."),
    ("eBPF", "/ˌiː.biː.piːˈɛf/", "lọc gói mở rộng Berkeley trong nhân Linux", "eBPF enables kernel-level observability."),
    ("RDMA", "/ˌɑːr.diː.ɛmˈeɪ/", "truy cập bộ nhớ từ xa trực tiếp tốc độ cao", "RDMA enables low-latency network communication."),
    ("NUMA architecture", "/ˈnjuː.mə ˈɑːr.kɪ.tɛk.tʃər/", "kiến trúc bộ nhớ không đồng nhất đa nhân", "NUMA affects memory access patterns on servers."),
    ("kernel bypass", "/ˈkɜːr.nəl ˈbaɪ.pæs/", "bỏ qua nhân hệ điều hành để tăng tốc I/O", "Kernel bypass reduces network latency."),
    ("FinOps", "/ˈfɪn.ɒps/", "quản lý tài chính điện toán đám mây hiệu quả", "FinOps optimizes cloud spending."),
    ("platform engineering", "/ˈplæt.fɔːrm ˌɛn.dʒɪˈnɪər.ɪŋ/", "xây dựng nền tảng nội bộ tự phục vụ dev", "Platform engineering improves developer experience."),
    ("chaos engineering", "/ˈkeɪ.ɒs ˌɛn.dʒɪˈnɪər.ɪŋ/", "kiểm tra hệ thống bằng cách cố tình gây lỗi", "Chaos engineering tests system resilience."),
    ("supply chain attack", "/səˈplaɪ tʃeɪn əˈtæk/", "tấn công vào chuỗi cung ứng phần mềm", "Supply chain attacks target software dependencies."),
    ("software bill of materials", "/ˈsɒft.weər bɪl əv məˈtɪər.i.əlz/", "danh sách thành phần phần mềm đầy đủ", "An SBOM lists all software components used."),
    ("ephemeral environment", "/ɪˈfɛm.ər.əl ɪnˈvaɪər.ən.mənt/", "môi trường tạm thời tạo và xóa theo yêu cầu", "Ephemeral environments improve developer speed."),
    ("GitOps", "/ˈɡɪt.ɒps/", "triển khai hạ tầng dùng Git làm nguồn sự thật", "GitOps uses Git as the source of truth."),
    ("policy as code", "/ˈpɒl.ɪ.si æz koʊd/", "quản lý chính sách hệ thống bằng mã", "Policy as code enforces compliance automatically."),
    ("self-healing system", "/sɛlf ˈhiː.lɪŋ ˈsɪs.təm/", "hệ thống tự phục hồi sau sự cố tự động", "A self-healing system restarts failed services."),
    ("semantic versioning", "/sɪˈmæn.tɪk ˈvɜːr.ʒən.ɪŋ/", "đánh số phiên bản ngữ nghĩa MAJOR.MINOR.PATCH", "Semantic versioning communicates breaking changes."),
    ("idempotency", "/ˌaɪ.dɛmˈpoʊ.tən.si/", "tính lũy đẳng: thực hiện nhiều lần ra cùng kết quả", "Idempotency ensures safe API retries."),
    ("eventual consistency model", "/ɪˈvɛn.tʃʊ.əl kənˈsɪs.tən.si ˈmɒd.əl/", "mô hình nhất quán cuối cùng trong hệ phân tán", "The eventual consistency model suits NoSQL stores."),
    ("latency percentile", "/ˈleɪ.tən.si pərˈsɛn.taɪl/", "phân vị độ trễ đo lường hiệu suất thực sự", "Monitor p99 latency for tail latency issues."),
    ("SLO", "/ˌɛs.ɛlˈoʊ/", "mục tiêu mức độ dịch vụ cần đạt được", "An SLO defines the reliability target."),
    ("SLA", "/ˌɛs.ɛlˈeɪ/", "thỏa thuận mức độ dịch vụ với khách hàng", "The SLA guarantees 99.9% uptime."),
]
