# Tech B2 và C1 đầy đủ 50 từ không trùng lặp

tech_b2_c1 = {
    "B2": [
        ("infrastructure", "/ˈɪn.frəˌstrʌk.tʃər/", "cơ sở hạ tầng kỹ thuật", "The company upgraded its server infrastructure."),
        ("broadcasting", "/ˈbrɔːd.kɑː.stɪŋ/", "phát sóng truyền hình/phát thanh", "The broadcasting network covers the entire nation."),
        ("device", "/dɪˈvaɪs/", "thiết bị điện tử cầm tay", "Connect your mobile device to the computer."),
        ("telephone", "/ˈtel.ɪ.fəʊn/", "điện thoại liên lạc", "He answered the ringing telephone."),
        ("display", "/dɪˈspleɪ/", "màn hình hiển thị hình ảnh", "The monitor display has high contrast."),
        ("blockchain", "/ˈblɒk.tʃeɪn/", "công nghệ chuỗi khối bảo mật", "Cryptocurrencies rely on blockchain technology."),
        ("cryptocurrency", "/ˈkrɪp.təʊˌkʌr.ən.si/", "tiền điện tử, tiền mã hóa", "Bitcoin is the most famous cryptocurrency."),
        ("smart contract", "/smɑːt ˈkɒn.trækt/", "hợp đồng thông minh tự thực thi", "Ethereum supports smart contracts."),
        ("decentralized", "/ˌdiːˈsen.trə.laɪzd/", "phi tập trung, phân tán", "A decentralized system has no single point of failure."),
        ("ledger", "/ˈledʒ.ər/", "sổ cái ghi chép dữ liệu", "All transactions are recorded in the shared ledger."),
        ("node validator", "/nəʊd ˈvæl.ɪ.deɪ.tər/", "nút xác thực giao dịch", "Validators secure the network by checking blocks."),
        ("mining rig", "/ˈmaɪ.nɪŋ rɪɡ/", "dàn máy đào tiền điện tử", "He built a powerful mining rig with six GPUs."),
        ("hash rate", "/hæʃ reɪt/", "tốc độ băm, năng lực đào", "The network hash rate reached a new record."),
        ("consensus", "/kənˈsen.səs/", "cơ chế đồng thuận mạng", "Proof of Work is a consensus mechanism."),
        ("proof of work", "/pruːf ɒv wɜːk/", "bằng chứng công việc (đào coin)", "Proof of Work requires high computing power."),
        ("proof of stake", "/pruːf ɒv steɪk/", "bằng chứng cổ phần", "Proof of Stake is more energy-efficient."),
        ("digital wallet", "/ˈdɪdʒ.ɪ.təl ˈwɒl.ɪt/", "ví điện tử lưu trữ coin", "Keep your private keys safe in a digital wallet."),
        ("private key", "/ˈpraɪ.vət kiː/", "khóa tư nhân bảo mật", "Never reveal your private key to anyone."),
        ("public key", "/ˈpʌb.lɪk kiː/", "khóa công khai để nhận coin", "The public key acts like an account number."),
        ("cryptographic hash", "/ˌkrɪp.təˈɡræf.ɪk hæʃ/", "hàm băm mật mã học", "A cryptographic hash is a one-way function."),
        ("digital signature", "/ˈdɪdʒ.ɪ.təl ˈsɪɡ.nə.tʃər/", "chữ ký số xác thực", "Digital signatures verify the sender's identity."),
        ("quantum computing", "/ˈkwɒn.təm kəmˈpjuː.tɪŋ/", "điện toán lượng tử", "Quantum computing could break current encryption."),
        ("supercomputer", "/ˈsuː.pə.kəmˌpjuː.tər/", "siêu máy tính hiệu năng cao", "The weather agency uses a supercomputer for simulations."),
        ("mainframe", "/ˈmeɪn.freɪm/", "máy tính lớn doanh nghiệp", "Banks rely on mainframe computers for transaction processing."),
        ("data center", "/ˈdeɪ.tə ˈsen.tər/", "trung tâm dữ liệu khổng lồ", "The data center has redundant cooling systems."),
        ("server rack", "/ˈsɜː.vər ræk/", "giá tủ chứa máy chủ", "The technician mounted the server in the rack."),
        ("fiber connection", "/ˈfaɪ.bər kəˈnek.ʃən/", "kết nối cáp quang siêu tốc", "A fiber connection offers low latency."),
        ("latency", "/ˈleɪ.tən.si/", "độ trễ truyền mạng", "Low latency is crucial for online gaming."),
        ("ping rate", "/pɪŋ reɪt/", "tốc độ phản hồi mạng ping", "A low ping rate ensures smooth connection."),
        ("packet loss", "/ˈpæk.ɪt lɒs/", "mất gói tin truyền mạng", "Packet loss causes buffering during video calls."),
        ("bandwidth throttling", "/ˈbænd.wɪdθ ˈθrɒt.əl.ɪŋ/", "bóp băng thông, giới hạn tốc độ", "The ISP implements bandwidth throttling during peak hours."),
        ("data cap", "/ˈdeɪ.tə kæp/", "hạn mức dung lượng hàng tháng", "My mobile plan has a 10GB data cap."),
        ("unlimited data", "/ʌnˈlɪm.ɪ.tɪd ˈdeɪ.tə/", "dữ liệu không giới hạn dung lượng", "We upgraded to an unlimited data plan."),
        ("proxy server", "/ˈprɒk.si ˈsɜː.vər/", "máy chủ ủy nhiệm trung gian", "The proxy server filters web traffic."),
        ("virtual private network", "/ˈvɜː.tʃu.əl ˈpraɪ.vət ˈnet.wɜːk/", "mạng riêng ảo VPN bảo mật", "Use a VPN to encrypt your internet traffic."),
        ("dns server", "/ˌdiː.enˈes ˈsɜː.vər/", "máy chủ phân giải tên miền DNS", "Change your DNS server to improve loading speeds."),
        ("ip conflict", "/ˌaɪˈpiː ˈkɒn.flɪkt/", "xung đột địa chỉ IP trong mạng", "An IP conflict prevented the laptop from connecting."),
        ("submask", "/ˈsʌb.mɑːsk/", "mặt nạ mạng con", "The subnet mask defines the network size."),
        ("gateway", "/ˈɡeɪt.weɪ/", "cổng kết nối mạng ngoài", "Set the router IP as the default gateway."),
        ("port forwarding", "/pɔːt ˈfɔː.wə.dɪŋ/", "chuyển tiếp cổng kết nối", "Port forwarding is required to host the server."),
        ("firewall rules", "/ˈfaɪə.wɔːl ruːlz/", "quy tắc cấu hình tường lửa", "Modify the firewall rules to allow traffic."),
        ("intrusion detection", "/ɪnˈtruː.ʒən dɪˈtek.ʃən/", "hệ thống phát hiện xâm nhập trái phép", "The intrusion detection system alerted the IT team."),
        ("data breach", "/ˈdeɪ.tə briːtʃ/", "sự cố rò rỉ, lộ dữ liệu", "The data breach exposed millions of customer passwords."),
        ("identity theft", "/aɪˈden.tə.ti θeft/", "đánh cắp danh tính giả mạo", "Protect your personal details to prevent identity theft."),
        ("two-factor", "/tuː ˈfæk.tər/", "xác thực hai yếu tố bảo mật", "Two-factor authentication secures your account."),
        ("multi-factor", "/ˈmʌl.ti ˈfæk.tər/", "xác thực nhiều yếu tố", "Multi-factor authentication is mandatory for staff."),
        ("biometric lock", "/ˌbaɪ.əʊˈmet.rɪk lɒk/", "khóa bảo mật sinh trắc học", "The safe is protected by a biometric lock."),
        ("fingerprint scanner", "/ˈfɪŋ.ɡə.prɪnt ˈskæn.ər/", "thiết bị quét vân tay", "The phone has an under-display fingerprint scanner."),
        ("facial recognition", "/ˈfeɪ.ʃəl ˌrek.əɡˈnɪʃ.ən/", "công nghệ nhận diện khuôn mặt", "Facial recognition is used for airport security."),
        ("retina scan", "/ˈret.ɪ.nə skæn/", "quét võng mạc bảo mật cao", "A retina scan is required to enter the vault.")
    ],
    "C1": [
        ("infrastructure build", "/ˈɪn.frəˌstrʌk.tʃər bɪld/", "xây dựng cơ sở hạ tầng kỹ thuật", "The project funded an infrastructure build."),
        ("broadcasting studio", "/ˈbrɔːd.kɑː.stɪŋ ˈstjuː.di.əʊ/", "phòng thu phát sóng chuyên dụng", "The broadcasting studio has soundproofing."),
        ("nanotechnology", "/ˌnæn.əʊ.tekˈnɒl.ə.dʒi/", "công nghệ nano siêu nhỏ", "Nanotechnology is used to build faster processors."),
        ("biotechnology", "/ˌbaɪ.əʊ.tekˈnɒl.ə.dʒi/", "công nghệ sinh học số", "Biotechnology advances genetic research."),
        ("telecommunication", "/ˌtel.ɪ.kəˌmjuː.nɪˈkeɪ.ʃən/", "viễn thông, truyền thông từ xa", "The telecommunication network was upgraded to 5G."),
        ("satellite link", "/ˈsæt.əl.aɪt lɪŋk/", "đường truyền kết nối vệ tinh", "The remote island relies on a satellite link."),
        ("telemetry", "/təˈlem.ə.tri/", "đo lường và truyền dữ liệu từ xa", "Spacecraft telemetry is monitored continuously."),
        ("cryptographer", "/krɪpˈtɒɡ.rə.fər/", "nhà mật mã học chuyên nghiệp", "The cryptographer designed a new cipher."),
        ("steganography", "/ˌsteɡ.əˈnɒɡ.rə.fi/", "kỹ thuật giấu thư/tin mật", "Steganography hides messages inside images."),
        ("quantum key", "/ˈkwɒn.təm kiː/", "phân phối khóa lượng tử", "Quantum key distribution is theoretically unbreakable."),
        ("asymmetric", "/ˌeɪ.sɪˈmet.rɪk/", "mật mã học bất đối xứng", "Asymmetric encryption uses a public and private key pair."),
        ("symmetric", "/sɪˈmet.rɪk/", "mật mã học đối xứng một khóa", "Symmetric encryption is faster but harder to share."),
        ("hash collision", "/hæʃ kəˈlɪʒ.ən/", "trùng lặp giá trị băm", "A hash collision occurred in the database."),
        ("distributed ledger", "/dɪˈstrɪb.juː.tɪd ˈledʒ.ər/", "sổ cái phân tán toàn mạng", "The distributed ledger was updated across all nodes."),
        ("zero-knowledge", "/ˈzɪə.rəʊ ˈnɒl.ɪdʒ/", "bằng chứng không tiết lộ tri thức", "Zero-knowledge proofs verify data without revealing it."),
        ("smart contract deploy", "/smɑːt ˈkɒn.trækt dɪˈplɔɪ/", "triển khai hợp đồng thông minh", "The smart contract deploy succeeded."),
        ("byzantine fault", "/ˈbɪz.ən.taɪn fɔːlt/", "khả năng chống lỗi hệ thống Byzantine", "The network achieves Byzantine fault tolerance."),
        ("consensus protocol", "/kənˈsen.səs ˈprəʊ.tə.kɒl/", "giao thức đạt đồng thuận mạng", "The consensus protocol was updated to reduce latency."),
        ("liquidity pool", "/lɪˈkwɪd.ə.ti puːl/", "bể thanh khoản tài chính số", "Users deposit tokens into the liquidity pool."),
        ("smart technology", "/smɑːt tekˈnɒl.ə.dʒi/", "công nghệ thông minh thế hệ mới", "Smart technology optimizes home energy use."),
        ("cyberwarfare", "/ˈsaɪ.bəˌwɔː.feər/", "chiến tranh mạng quốc gia", "Cyberwarfare represents a modern security threat."),
        ("hacktivism", "/ˈhæk.tɪ.vɪ.zəm/", "tin tặc hoạt động chính trị", "Hacktivism was used to target corporate sites."),
        ("vulnerability scan", "/ˌvʌl.nər.əˈbɪl.ə.ti skæn/", "quét lỗ hổng bảo mật", "The security team ran a vulnerability scan."),
        ("penetration testing", "/ˌpen.ɪˈtreɪ.ʃən ˈtest.ɪŋ/", "kiểm thử xâm nhập bảo mật thực tế", "Penetration testing exposed several security flaws."),
        ("exploit payload", "/ɪkˈsplɔɪt ˈpeɪ.ləʊd/", "đoạn mã độc tấn công khai thác", "The exploit payload bypassed the firewall."),
        ("zero-day vulnerability", "/ˈzɪə.rəʊ deɪ ˌvʌl.nər.əˈbɪl.ə.ti/", "lỗ hổng bảo mật chưa được công bố", "A zero-day vulnerability in the browser was patched."),
        ("buffer overflow", "/ˈbʌf.ər ˌəʊ.vəˈfləʊ/", "lỗi tràn bộ đệm hệ thống", "A buffer overflow can allow remote code execution."),
        ("privilege escalation", "/ˈprɪv.əl.ɪdʒ ˌes.kəˈleɪ.ʃən/", "leo thang đặc quyền truy cập trái phép", "The hacker achieved privilege escalation to root."),
        ("rootkit", "/ˈruːt.kɪt/", "mã độc ẩn sâu quyền quản trị", "The rootkit was hard to detect and remove."),
        ("digital forensics", "/ˈdɪdʒ.ɪ.təl fəˈren.zɪks/", "điều tra dấu vết kỹ thuật số", "Digital forensics recovered deleted chat logs."),
        ("packet sniffer", "/ˈpæk.ɪt ˈsnɪf.ər/", "thiết bị/phần mềm nghe lén gói tin", "The packet sniffer captured network traffic."),
        ("man-in-the-middle", "/mæn ɪn ðə ˈmɪd.əl/", "tấn công xen giữa nghe lén", "Encryption prevents man-in-the-middle attacks."),
        ("denial of service", "/dɪˈnaɪ.əl ɒv ˈsɜː.vɪs/", "tấn công từ chối dịch vụ DoS", "A denial of service attack took the site offline."),
        ("ddos mitigation", "/ˌdiː.diː.əʊˈes ˌmɪt.ɪˈɡeɪ.ʃən/", "giảm thiểu tác hại DDoS mạng", "We implemented DDoS mitigation strategies."),
        ("botnet", "/ˈbɒt.net/", "mạng máy tính ma bị điều khiển", "The botnet was used to launch cyberattacks."),
        ("phishing campaign", "/ˈfɪʃ.ɪŋ kæmˈpeɪn/", "chiến dịch tấn công giả mạo", "A phishing campaign targeted company staff."),
        ("two-factor setup", "/tuː ˈfæk.tər ˈset.ʌp/", "thiết lập bảo mật hai lớp", "Complete the two-factor setup now."),
        ("biometric access", "/ˌbaɪ.əʊˈmet.rɪk ˈæk.sɛs/", "truy cập quét sinh trắc học", "Biometric access is required for vault entry."),
        ("retina scanner", "/ˈret.ɪ.nə ˈskæn.ər/", "thiết bị quét võng mạc bảo mật", "The retina scanner is highly accurate."),
        ("quantum cryptography", "/ˈkwɒn.təm krɪpˈtɒɡ.rə.fi/", "mật mã học lượng tử bảo mật tuyệt đối", "Quantum cryptography offers perfect security."),
        ("cybersecurity analyst", "/ˌsaɪ.bə.sɪˈkjʊə.rə.ti ˈæn.ə.lɪst/", "chuyên gia phân tích an ninh mạng", "The cybersecurity analyst investigated the breach."),
        ("incident response", "/ˈɪn.sɪ.dənt rɪˈspɒns/", "quy trình ứng phó sự cố bảo mật", "The incident response team was deployed immediately."),
        ("disaster recovery", "/dɪˈzɑː.stər rɪˈkʌv.ər.i/", "quy trình khắc phục sau thảm họa", "Our disaster recovery plan worked perfectly."),
        ("business continuity", "/ˈbɪz.nɪs ˌkɒn.tɪˈnjuː.ə.ti/", "đảm bảo tính liên tục của doanh nghiệp", "We test our business continuity plan annually."),
        ("uptime guarantee", "/ˈʌp.taɪm ˌɡær.ənˈtiː/", "cam kết tỉ lệ hoạt động liên tục", "The web host offers a 99.9% uptime guarantee."),
        ("load balancing", "/ləʊd ˈbæl.əns.ɪŋ/", "công nghệ cân bằng tải máy chủ", "Load balancing distributes traffic across servers."),
        ("reverse proxy", "/rɪˈvɜːs ˈprɒk.si/", "máy chủ ủy nhiệm ngược bảo vệ backend", "The reverse proxy handles SSL termination."),
        ("content delivery network", "/kənˈtent dɪˈvɪv.ər.i ˈnet.wɜːk/", "mạng phân phối nội dung CDN toàn cầu", "A content delivery network speeds up page loads globally."),
        ("edge computing", "/edʒ kəmˈpjuː.tɪŋ/", "điện toán biên xử lý dữ liệu sát rìa", "Edge computing reduces bandwidth usage."),
        ("serverless architecture", "/ˈsɜː.və.ləs ˈɑː.kɪ.tek.tʃər/", "kiến trúc không máy chủ (Serverless)", "Serverless architecture scales automatically.")
    ]
}
