# Dữ liệu từ vựng tech, marketing, job, business đầy đủ 50 từ mỗi level tránh trùng lặp 100%

# 1. TECH (A1-C1)
tech_vocab = {
    "A1": [
        ("phone", "/foʊn/", "điện thoại di động", "She checked her messages on her phone."),
        ("screen", "/skriːn/", "màn hình hiển thị", "The computer screen is bright and clear."),
        ("camera", "/ˈkæmərə/", "máy ảnh, máy quay phim", "He bought a new digital camera."),
        ("tablet", "/ˈtæblət/", "máy tính bảng", "We watch movies on our tablet."),
        ("video", "/ˈvɪdioʊ/", "băng hình, phim video", "She posted a funny video online."),
        ("game", "/ɡeɪm/", "trò chơi điện tử/máy tính", "He plays video games every weekend."),
        ("internet", "/ˈɪntərnet/", "mạng internet toàn cầu", "You need the internet to search for info."),
        ("email", "/ˈiːmeɪl/", "thư điện tử", "Send me an email with the details."),
        ("telephone", "/ˈtɛlɪˌfoʊn/", "điện thoại cố định/nói chung", "The telephone is ringing in the hall."),
        ("display", "/dɪˈspleɪ/", "màn hình hiển thị tinh thể", "The new model has an OLED display."),
        ("lens", "/lɛnz/", "ống kính máy ảnh/thấu kính", "Clean the camera lens before taking photos."),
        ("pad", "/pæd/", "tập giấy nhỏ; miếng lót chuột", "Write the note on a writing pad."),
        ("clip", "/klɪp/", "đoạn phim ngắn, video ngắn", "Watch this short video clip of the cat."),
        ("match", "/mæʧ/", "trận đấu bóng đá/thể thao", "We watched a live football match."),
        ("net", "/nɛt/", "mạng lưới internet nói chung", "He spent all day surfing the net."),
        ("electronic mail", "/ɪˌlɛkˈtrɑnɪk meɪl/", "thư điện tử chính thức", "Formal requests should be sent via electronic mail."),
        ("sound", "/saʊnd/", "âm thanh", "Turn up the sound on the speaker."),
        ("mouse", "/maʊs/", "con chuột máy tính", "Move the computer mouse to select."),
        ("keyboard", "/ˈkiː.bɔːd/", "bàn phím", "A mechanical keyboard is nice to type on."),
        ("laptop", "/ˈlæp.tɒp/", "máy tính xách tay", "Open your laptop to start work."),
        ("battery", "/ˈbæt.ər.i/", "cục pin", "My phone battery is running low."),
        ("charger", "/ˈtʃɑː.dʒər/", "thiết bị sạc pin", "Plug the phone into the charger."),
        ("cable", "/ˈkeɪ.bəl/", "dây cáp kết nối", "Connect the monitor with an HDMI cable."),
        ("button", "/ˈbʌt.ən/", "nút bấm vật lý/mềm", "Press the power button to turn on."),
        ("light", "/laɪt/", "đèn báo tín hiệu", "A blue light indicates bluetooth is on."),
        ("card", "/kɑːd/", "thẻ nhớ/thẻ SIM", "Insert the micro SIM card here."),
        ("plug", "/plʌɡ/", "phích cắm điện", "Put the plug into the wall socket."),
        ("wire", "/waɪər/", "dây dẫn điện", "Be careful not to trip over the wire."),
        ("key", "/kiː/", "phím trên bàn phím", "Hold down the shift key to type capital letters."),
        ("power", "/ˈpaʊ.ər/", "nguồn điện, năng lượng", "Connect the machine to a power source."),
        ("speaker", "/ˈspiː.kər/", "loa phát âm thanh", "The laptop has built-in stereo speakers."),
        ("music", "/ˈmjuː.zɪk/", "âm nhạc số", "He listens to stream music while working."),
        ("app", "/æp/", "ứng dụng di động/máy tính", "Install the updated weather app."),
        ("code", "/kəʊd/", "mã nguồn lập trình", "He is learning to write simple code."),
        ("link", "/lɪŋk/", "đường dẫn, liên kết web", "Click the link in the description."),
        ("page", "/peɪdʒ/", "trang web", "Reload the webpage to see updates."),
        ("search", "/sɜːtʃ/", "tìm kiếm thông tin", "Use a search engine to find recipes."),
        ("save", "/seɪv/", "lưu lại dữ liệu", "Save your document before closing."),
        ("open", "/ˈəʊ.pən/", "mở tệp tin/ứng dụng", "Open the image in the editor."),
        ("close", "/kləʊz/", "đóng tệp tin/ứng dụng", "Close the browser window when done."),
        ("print", "/prɪnt/", "in ấn tài liệu ra giấy", "Print two copies of the contract."),
        ("online", "/ˈɒn.laɪn/", "kết nối trực tuyến", "Are you online right now?"),
        ("offline", "/ˌɒfˈlaɪn/", "không có mạng, ngoại tuyến", "The game can be played offline."),
        ("icon", "/ˈaɪ.kɒn/", "biểu tượng nhỏ trên màn hình", "Click the trash icon to empty it."),
        ("folder", "/ˈfəʊl.dər/", "thư mục chứa các tệp", "Create a folder for your projects."),
        ("file", "/faɪl/", "tệp tin dữ liệu", "Send the PDF file via email."),
        ("click", "/klɪk/", "nhấp chuột trái", "Left-click to select the option."),
        ("user", "/ˈjuː.zər/", "người dùng hệ thống", "Each user needs a unique password."),
        ("web", "/web/", "mạng lưới internet nói chung", "Browse the web for hotel deals."),
        ("text", "/tekst/", "văn bản, tin nhắn chữ", "Send me a text when you arrive.")
    ]
}
