# AI B2, C1 phong phú: 50 từ mỗi cấp không trùng lặp

ai_b2_c1 = {
    "B2": [
        ("neural network", "/ˈnjʊərəl ˈnetwɜːk/", "mạng nơ-ron", "AI is built on neural networks."),
        ("machine learning", "/məˈʃiːn ˈlɜːnɪŋ/", "học máy", "Machine learning is a subset of AI."),
        ("dataset", "/ˈdeɪtəset/", "tập dữ liệu", "The model was trained on a massive dataset."),
        ("optimization", "/ˌɒptɪmaɪˈzeɪʃn/", "sự tối ưu hóa", "We perform optimization on the search logic."),
        ("classification", "/ˌklæsɪfɪˈkeɪʃn/", "sự phân loại", "The algorithm handles image classification."),
        ("framework", "/ˈfreɪmwɜːk/", "khung làm việc, thư viện mẫu", "TensorFlow is a popular framework for deep learning."),
        ("generative", "/ˈdʒenərətɪv/", "tạo sinh", "ChatGPT is a popular generative AI application."),
        ("autonomous", "/ɔːˈtɒnəməs/", "tự trị, tự lái", "Autonomous vehicles are being tested on public roads."),
        ("deep network", "/diːp ˈnet.wɜːk/", "mạng học sâu, mạng nơ-ron nhiều lớp", "A deep network requires powerful hardware to train."),
        ("pattern recognition", "/ˈpæt.ən ˌrek.əɡˈnɪʃ.ən/", "sự nhận dạng khuôn mẫu", "Pattern recognition is widely used in facial scan technology."),
        ("corpus", "/ˈcɔː.pəs/", "kho ngữ liệu văn bản", "The linguists analyzed a corpus of spoken English speeches."),
        ("tuning", "/ˈtʃuː.nɪŋ/", "sự căn chỉnh, tinh chỉnh hiệu năng", "Engine tuning can improve fuel efficiency and performance."),
        ("categorization", "/ˌkæt.ə.ɡər.aɪˈzeɪ.ʃən/", "sự chia nhóm, phân loại danh mục", "The library uses a strict system for book categorization."),
        ("library_1", "/ˈlaɪ.brər.i/", "thư viện mã nguồn phần mềm", "You can import this python library to handle HTTP requests."),
        ("creative", "/kriˈeɪ.tɪv/", "sáng tạo, mang tính sáng tạo", "She has many creative ideas for the new marketing campaign."),
        ("self-driving", "/ˌselfˈdraɪ.vɪŋ/", "tự lái, tự điều khiển hành trình", "Self-driving cars are expected to reduce traffic accidents."),
        ("gradient descent", "/ˈɡreɪdiənt dɪˈsɛnt/", "phương pháp hạ gradient (tối ưu hóa)", "Gradient descent is used to minimize the loss function."),
        ("attention mechanism", "/əˈtenʃən ˈmɛkənɪzəm/", "cơ chế chú ý trong AI", "The attention mechanism allows the model to focus on key words."),
        ("fine-tuning", "/faɪn ˈtjuːnɪŋ/", "tinh chỉnh mô hình AI", "Fine-tuning a pre-trained model improves its accuracy."),
        ("algorithm update", "/ˈæl.ɡə.rɪð.əm ˈʌp.deɪt/", "cập nhật thuật toán", "The recent algorithm update changed search rankings."),
        ("regression", "/rɪˈɡrɛʃ.ən/", "phép hồi quy", "Linear regression is used to forecast house prices."),
        ("overfitting", "/ˌoʊ.vərˈfɪt.ɪŋ/", "hiện tượng quá khớp dữ liệu", "Regularization is used to prevent overfitting."),
        ("underfitting", "/ˌʌn.dərˈfɪt.ɪŋ/", "hiện tượng chưa khớp dữ liệu", "Underfitting happens when the model is too simple."),
        ("regularization", "/ˌrɛɡ.jə.lə.raɪˈzeɪ.ʃən/", "phương pháp chuẩn hóa", "L2 regularization penalizes large weights."),
        ("validation", "/ˌvæl.ɪˈdeɪ.ʃən/", "xác thực chéo dữ liệu", "Split the dataset into training and validation sets."),
        ("normalization", "/ˌnɔː.mə.laɪˈzeɪ.ʃən/", "chuẩn hóa dữ liệu về khoảng 0-1", "Data normalization improves gradient descent convergence."),
        ("standardization", "/ˌstæn.də.daɪˈzeɪ.ʃən/", "chuẩn hóa dữ liệu theo phân phối chuẩn", "Standardization rescales features to have zero mean."),
        ("encoder", "/ɪnˈkoʊ.dər/", "bộ mã hóa", "The encoder converts text into a dense vector."),
        ("decoder", "/diːˈkoʊ.dər/", "bộ giải mã", "The decoder generates target text word by word."),
        ("embedding", "/ɪmˈbɛd.ɪŋ/", "nhúng từ, biểu diễn từ vector", "Word embedding captures semantic relationships."),
        ("tokenization", "/ˌtoʊ.kən.aɪˈzeɪ.ʃən/", "chia nhỏ văn bản thành các token", "Tokenization is the first step in NLP."),
        ("stemming", "/ˈstɛm.ɪŋ/", "cắt tỉa từ về dạng gốc thô", "Stemming reduces words to their base form."),
        ("lemmatization", "/ˌlɛm.ə.tə.zaɪˈzeɪ.ʃən/", "đưa từ về dạng từ điển chuẩn", "Lemmatization uses vocabulary and morphological analysis."),
        ("stopword", "/ˈstɒp.wɜːd/", "từ dừng, từ phổ biến vô nghĩa", "Remove stopwords like 'the' and 'is' from text."),
        ("corpus size", "/ˈcɔː.pəs saɪz/", "kích thước kho ngữ liệu", "The corpus size is 10 billion tokens."),
        ("transformer block", "/trænsˈfɔː.mər blɒk/", "khối transformer", "The model stacked 12 transformer blocks."),
        ("hyperparameter tuning", "/ˌhaɪ.pər.pəˈræm.ɪ.tər ˈtʃuː.nɪŋ/", "tinh chỉnh siêu tham số", "Grid search is used for hyperparameter tuning."),
        ("validation loss", "/ˌvæl.ɪˈdeɪ.ʃən lɒs/", "hàm mát mát xác thực", "The validation loss started to increase."),
        ("training loss", "/ˈtreɪ.nɪŋ lɒs/", "hàm mất mát huấn luyện", "Monitor the training loss during epochs."),
        ("epoch", "/ˈiː.pɒk/", "vòng huấn luyện toàn bộ dữ liệu", "The model was trained for 50 epochs."),
        ("batch size", "/bætʃ saɪz/", "kích thước lô huấn luyện", "A batch size of 32 was selected."),
        ("learning rate", "/ˈlɜː.nɪŋ reɪt/", "tốc độ học tập", "A high learning rate can cause instability."),
        ("optimizer", "/ˈɒp.tɪ.maɪ.zər/", "bộ tối ưu hóa", "Adam is a robust network optimizer."),
        ("momentum", "/məˈmɛn.təm/", "động lượng tối ưu", "Momentum accelerates gradient descent."),
        ("dropout", "/ˈdraʊp.aʊt/", "kỹ thuật loại bỏ nơ-ron ngẫu nhiên", "Dropout is a powerful regularization technique."),
        ("bias", "/ˈbaɪ.əs/", "độ lệch, thiên lệch", "The model has high bias but low variance."),
        ("variance", "/ˈveə.ri.əns/", "phương sai", "High variance indicates overfitting."),
        ("precision", "/prɪˈsɪʒ.ən/", "độ chính xác dự đoán đúng", "We optimized the model for high precision."),
        ("recall", "/rɪˈkɔːl/", "độ bao phủ, tỉ lệ tìm thấy", "High recall is important in medical diagnosis."),
        ("f1 score", "/ˌɛf.wʌn skɔːr/", "điểm số F1 trung bình điều hòa", "The F1 score balanced precision and recall.")
    ],
    "C1": [
        ("cognitive computing", "/ˈkɒɡnətɪv kəmˈpjuːtɪŋ/", "điện toán nhận thức", "Cognitive computing mimics human thought."),
        ("deep learning", "/diːp ˈlɜːnɪŋ/", "học sâu", "Deep learning achieves state of the art results."),
        ("reinforcement", "/ˌriːɪnˈfɔːsmənt/", "sự tăng cường", "AlphaGo uses reinforcement learning."),
        ("transformers", "/trænsˈfɔːməs/", "mô hình Transformer", "Modern LLMs are built on the Transformer architecture."),
        ("supervised", "/ˈsuːpəvaɪzd/", "có giám sát", "Supervised learning requires labeled training data."),
        ("natural language", "/ˈnætʃrəl ˈlæŋɡwɪdʒ/", "ngôn ngữ tự nhiên", "Natural Language Processing makes chatbots smarter."),
        ("hyperparameters", "/ˌhaɪpəpəˈræmɪtəz/", "siêu tham số", "Tuning hyperparameters is essential for model training."),
        ("backpropagation", "/ˌbækprɒpəˈɡeɪʃn/", "lan truyền ngược", "Backpropagation is used to train deep neural networks."),
        ("attention mechanisms", "/əˈten.ʃən ˈmek.ə.nɪz.əmz/", "cơ chế chú ý trong mạng nơ-ron", "Attention mechanisms help networks focus on relevant words."),
        ("labeled learning", "/ˈleɪ.bəld ˈlɜː.nɪŋ/", "học máy có gắn nhãn dữ liệu", "Labeled learning is highly accurate."),
        ("human speech", "/ˈhjuː.mən spiːtʃ/", "tiếng nói của con người", "The system can transcribe human speech."),
        ("model settings", "/ˈmɒd.əl ˈset.ɪŋz/", "thiết lập cấu hình mô hình", "Adjusting model settings improves accuracy."),
        ("error propagation", "/ˈer.ər ˌprɒp.əˈɡeɪ.ʃən/", "sự lan truyền sai số", "Error propagation can lead to incorrect results."),
        ("artificial brain", "/ˌɑː.tɪˈfɪʃ.əl breɪn/", "não bộ nhân tạo", "Scientists are building an artificial brain."),
        ("representation learning", "/ˌrep.rɪ.zenˈteɪ.ʃən ˈlɜː.nɪŋ/", "học biểu diễn tính năng", "Representation learning extracts raw features."),
        ("feedback loops", "/ˈfiːd.bæk luːps/", "vòng phản hồi điều khiển", "Feedback loops accelerate system learning."),
        ("unsupervised learning", "/ˌʌn.suː.pə.vaɪzd ˈlɜː.nɪŋ/", "học máy không giám sát", "Clustering is a form of unsupervised learning."),
        ("semi-supervised", "/ˌsɛm.i ˈsuː.pə.vaɪzd/", "học bán giám sát", "Semi-supervised learning uses a small labeled dataset."),
        ("transfer learning", "/ˈtræns.fɜːr ˈlɜː.nɪŋ/", "học chuyển đổi tri thức", "Transfer learning saves significant training time."),
        ("active learning", "/ˈæk.tɪv ˈlɜː.nɪŋ/", "học máy chủ động tương tác", "Active learning queries users for labels."),
        ("autoencoder", "/ˌɔː.toʊ.ɪnˈkoʊ.dər/", "mạng mã hóa tự động giảm chiều", "An autoencoder learns efficient data codings."),
        ("generative adversarial", "/ˈdʒɛn.ər.ə.tɪv ˌæd.vəˈsɛə.ri.əl/", "mạng sinh đối kháng (GAN)", "GANs generate realistic synthetic images."),
        ("latent space", "/ˈleɪ.tənt speɪs/", "không gian ẩn biểu diễn đặc trưng", "The encoder maps input into a latent space."),
        ("dimensionality reduction", "/daɪˌmɛn.ʃənˈæl.ə.ti rɪˈdʌk.ʃən/", "giảm chiều dữ liệu", "PCA is used for dimensionality reduction."),
        ("eigenvector", "/ˈaɪ.ɡənˌvɛk.tər/", "vectơ riêng của ma trận", "Eigenvectors define the principal components."),
        ("covariance matrix", "/koʊˈvɛə.ri.əns ˈmeɪ.trɪks/", "ma trận hiệp phương sai", "Compute the covariance matrix of features."),
        ("stochastic gradient", "/stəˈkæs.tɪk ˈɡreɪ.di.ənt/", "hạ gradient ngẫu nhiên (SGD)", "SGD updates weights after each sample."),
        ("vanishing gradient", "/ˈvæn.ɪ.ʃɪŋ ˈɡreɪ.di.ənt/", "triệt tiêu gradient ở lớp sâu", "LSTMs resolve the vanishing gradient problem."),
        ("exploding gradient", "/ɪkˈsploʊ.dɪŋ ˈɡreɪ.di.ənt/", "bùng nổ gradient ở lớp sâu", "Gradient clipping prevents exploding gradient."),
        ("recurrent network", "/rɪˈkʌr.ənt ˈnɛt.wɜːk/", "mạng nơ-ron hồi quy (RNN)", "RNNs are suited for sequential data."),
        ("long short-term memory", "/lɒŋ ʃɔːt tɜːm ˈmɛm.ər.i/", "mạng LSTM chuyên trị chuỗi dài", "LSTM is a type of recurrent network."),
        ("convolutional network", "/ˌkɒn.vəˈluː.ʃən.əl ˈnɛt.wɜːk/", "mạng nơ-ron tích chập (CNN)", "CNNs are widely used in computer vision."),
        ("pooling layer", "/ˈpuːl.ɪŋ ˈleɪ.ər/", "lớp gom thuộc tính để giảm tải", "Max pooling is a common pooling layer."),
        ("activation function", "/ˌæk.tɪˈveɪ.ʃən ˈfʌŋk.ʃən/", "hàm kích hoạt phi tuyến", "ReLU is the most popular activation function."),
        ("backpropagation through time", "/ˌbæk.prɒp.əˈɡeɪ.ʃən θruː taɪm/", "lan truyền ngược qua thời gian (BPTT)", "BPTT is used to train recurrent networks."),
        ("sequence-to-sequence", "/ˈsiː.kwəns tuː ˈsiː.kwəns/", "mô hình chuỗi-sang-chuỗi", "Seq2seq is used in neural translation."),
        ("self-attention", "/self əˈtɛn.ʃən/", "tự chú ý liên kết nội tại", "Self-attention maps relations within one sequence."),
        ("multi-head attention", "/ˈmʌl.ti hɛd əˈtɛn.ʃən/", "chú ý nhiều nhánh song song", "Multi-head attention captures diverse contexts."),
        ("positional encoding", "/pəˈzɪʃ.ən.əl ɪnˈkoʊ.dɪŋ/", "mã hóa vị trí từ trong chuỗi", "Positional encoding adds order info to transformers."),
        ("large language model", "/lɑːdʒ ˈlæŋ.ɡwɪdʒ ˈmɒd.əl/", "mô hình ngôn ngữ lớn (LLM)", "GPT-4 is a state-of-the-art large language model."),
        ("pre-training", "/priː ˈtreɪ.nɪŋ/", "huấn luyện sơ bộ trước", "Pre-training requires vast computing power."),
        ("zero-shot learning", "/ˈzɪə.rəʊ ʃɒt ˈlɜː.nɪŋ/", "học không cần mẫu huấn luyện", "LLMs display zero-shot learning capabilities."),
        ("few-shot learning", "/fjuː ʃɒt ˈlɜː.nɪŋ/", "học với vài mẫu gợi ý", "Few-shot learning provides a few context examples."),
        ("prompt engineering", "/prɒmpt ˌɛn.dʒɪˈnɪə.rɪŋ/", "kỹ nghệ thiết kế câu lệnh gợi ý", "Prompt engineering optimizes LLM responses."),
        ("retrieval augmented", "/rɪˈtriː.vəl ɔːɡˈmɛn.tɪd/", "sinh văn bản tăng cường truy xuất (RAG)", "RAG integrates external databases with LLMs."),
        ("vector database", "/ˈvɛk.tər ˈdeɪ.tə.beɪs/", "cơ sở dữ liệu vectơ", "Pinecone is a popular vector database."),
        ("cosine similarity", "/ˈkoʊ.saɪn ˌsɪm.əˈlær.ə.ti/", "độ tương đồng cosin", "Cosine similarity measures vector alignment."),
        ("embedding dimension", "/ɪmˈbɛd.ɪŋ daɪˈmɛn.ʃən/", "số chiều không gian nhúng vector", "The model has an embedding dimension of 768."),
        ("neural computing", "/ˈnjʊərəl kəmˈpjuːtɪŋ/", "điện toán nơ-ron mô phỏng não bộ", "Neural computing advances AI efficiency."),
        ("expert system", "/ˈɛk.spɜːt ˈsɪs.təm/", "hệ chuyên gia lập luận logic", "Expert systems were the early wave of AI.")
    ]
}
