# Dữ liệu từ vựng Travel phong phú (50 từ cho mỗi cấp từ A1-C1) không trùng lặp

travel_a1_a2_b1 = {
    "A1": [
        ("map", "/mæp/", "bản đồ", "We bought a city map."),
        ("train", "/treɪn/", "tàu hỏa", "The train arrives at ten."),
        ("plane", "/pleɪn/", "máy bay", "The plane flies very high."),
        ("car", "/kɑːr/", "xe ô tô", "We rented a small car."),
        ("road", "/rəʊd/", "con đường", "The road is very long."),
        ("room", "/ruːm/", "căn phòng, phòng nghỉ", "My room is on the second floor."),
        ("stop", "/stɒp/", "điểm dừng, trạm dừng", "Get off at the next bus stop."),
        ("land", "/lænd/", "đất liền, vùng đất", "They saw land after weeks at sea."),
        ("lake", "/leɪk/", "hồ nước", "We walked around the lake."),
        ("park", "/pɑːk/", "công viên", "The park is full of flowers."),
        ("shop", "/ʃɒp/", "cửa hàng", "I need to find a gift shop."),
        ("street", "/striːt/", "đường phố", "This street is very quiet."),
        ("time", "/taɪm/", "thời gian, giờ giấc", "What time does the tour start?"),
        ("boat", "/bəʊt/", "thuyền, tàu nhỏ", "They took a small boat to the island."),
        ("port", "/pɔːt/", "cảng, hải cảng", "The ship docked at the port."),
        ("day", "/deɪ/", "ngày, ban ngày", "It is a sunny day for travel."),
        ("night", "/naɪt/", "đêm, ban đêm", "We stayed at the hotel for one night."),
        ("year", "/jɪər/", "năm", "They travel abroad once a year."),
        ("holiday", "/ˈhɒl.ə.deɪ/", "ngày nghỉ, kỳ nghỉ", "We are on holiday this week."),
        ("place", "/pleɪs/", "địa điểm, nơi chốn", "This is a great place to visit."),
        ("world", "/wɜːld/", "thế giới", "I want to travel the world."),
        ("country", "/ˈkʌn.tri/", "đất nước, quốc gia", "Japan is a safe country to visit."),
        ("town", "/taʊn/", "thị trấn", "The town is very old and small."),
        ("sea", "/siː/", "biển, đại dương", "The sea is warm today."),
        ("forest", "/ˈfɒr.ɪst/", "khu rừng", "We hiked in the deep forest."),
        ("hill", "/hɪl/", "đồi, ngọn đồi", "They climbed to the top of the hill."),
        ("river", "/ˈrɪv.ər/", "dòng sông", "A river flows through the city."),
        ("island", "/ˈaɪ.lənd/", "hòn đảo", "We spent the summer on a tropical island."),
        ("key", "/kiː/", "chìa khóa", "Here is the key to your room."),
        ("door", "/dɔːr/", "cửa, cánh cửa", "Please lock the door behind you."),
        ("bag", "/bæɡ/", "túi xách, ba lô", "Put your water bottle in your bag."),
        ("ticket", "/ˈtɪk.ɪt/", "vé", "Show your ticket to the driver."),
        ("hotel", "/həʊˈtel/", "khách sạn", "We booked a room at the hotel."),
        ("bus", "/bʌs/", "xe buýt", "I take the bus every morning."),
        ("passport", "/ˈpɑːs.pɔːt/", "hộ chiếu", "You need a passport to travel abroad."),
        ("flight", "/flaɪt/", "chuyến bay", "Our flight is delayed by an hour."),
        ("station", "/ˈsteɪ.ʃən/", "nhà ga, trạm", "Meet me at the train station."),
        ("guide", "/ɡaɪd/", "hướng dẫn viên; sách chỉ dẫn", "The guide showed us the museum."),
        ("hostel", "/ˈhɒs.təl/", "nhà nghỉ giá rẻ", "Hostels are great for budget travelers."),
        ("luggage", "/ˈlʌɡ.ɪdʒ/", "hành lý du lịch", "You can leave your heavy luggage at the hotel reception."),
        ("beach", "/biːtʃ/", "bãi biển", "We sat on the sandy beach."),
        ("fly", "/flaɪ/", "bay, đi máy bay", "Birds fly south for the winter."),
        ("visa", "/ˈviː.zə/", "thị thực nhập cảnh", "She applied for a student visa."),
        ("inn", "/ɪn/", "nhà trọ cổ", "The travelers stayed at a cozy inn."),
        ("traveler", "/ˈtræv.əl.ər/", "khách lữ hành", "The traveler rested by the road."),
        ("booking", "/ˈbʊk.ɪŋ/", "việc đặt trước", "Please check your booking details."),
        ("lodging", "/ˈlɒdʒ.ɪŋ/", "chỗ trọ, nơi lưu trú tạm", "They searched for cheap lodging."),
        ("attraction", "/əˈtræk.ʃən/", "điểm tham quan hấp dẫn", "The palace is a popular tourist attraction."),
        ("pass", "/pɑːs/", "thẻ thông hành, thẻ ra vào", "Show your boarding pass at the gate."),
        ("coach", "/kəʊtʃ/", "xe khách liên tỉnh", "We took a coach to the next city.")
    ],
    "A2": [
        ("airport", "/ˈeə.pɔːt/", "sân bay", "The airport is far from the city."),
        ("luggage scale", "/ˈlʌɡ.ɪdʒ skeɪl/", "cân hành lý", "We weighed our bags on the scale."),
        ("boarding gate", "/ˈbɔː.dɪŋ ɡeɪt/", "cổng lên máy bay", "Proceed to boarding gate seven."),
        ("passenger train", "/ˈpæs.ən.dʒər treɪn/", "tàu chở khách", "The passenger train runs hourly."),
        ("timetable", "/ˈtaɪm.teɪ.bəl/", "lịch chạy tàu/xe", "Check the train timetable online."),
        ("taxi", "/ˈtæk.si/", "xe taxi", "We hailed a taxi outside the station."),
        ("subway", "/ˈsʌb.weɪ/", "tàu điện ngầm", "The subway is fast and cheap."),
        ("highway", "/ˈhaɪ.weɪ/", "đường cao tốc", "Cars sped down the highway."),
        ("journey time", "/ˈdʒɜː.ni taɪm/", "thời gian di chuyển", "The journey time is three hours."),
        ("ticket office", "/ˈtɪk.ɪt ˈɒf.ɪs/", "phòng vé", "Buy your tickets at the ticket office."),
        ("reservation desk", "/ˌrez.əˈveɪ.ʃən dɛsk/", "quầy đặt chỗ trước", "Ask at the reservation desk."),
        ("platform", "/ˈplæt.fɔːm/", "sân ga, thềm ga", "The train is on platform four."),
        ("passenger boat", "/ˈpæs.ən.dʒər bəʊt/", "tàu chở khách đường thủy", "The boat crossed the calm river."),
        ("harbor", "/ˈhɑː.bər/", "bến cảng, vũng tàu", "Yachts docked in the peaceful harbor."),
        ("cruise", "/kruːz/", "chuyến du thuyền", "They took a cruise in the Caribbean."),
        ("cabin", "/ˈkæb.ɪn/", "cabin, buồng ngủ trên tàu", "Our cabin was very comfortable."),
        ("backpacker", "/ˈbæk.pæk.ər/", "khách du lịch ba lô", "The backpacker carried a large tent."),
        ("souvenir", "/ˌsuː.vənˈɪər/", "quà lưu niệm", "She bought a souvenir in Paris."),
        ("sightseeing bus", "/ˈsaɪtˌsiː.ɪŋ bʌs/", "xe buýt ngắm cảnh", "We took an open-top sightseeing bus."),
        ("foreign country", "/ˈfɒr.ən ˈkʌn.tri/", "nước ngoài", "He loves visiting foreign countries."),
        ("tour guide", "/tʊər ɡaɪd/", "hướng dẫn viên du lịch", "The tour guide explained the history."),
        ("local food", "/ˈləʊ.kəl fuːd/", "món ăn địa phương", "We tried some delicious local food."),
        ("market stall", "/ˈmɑː.kɪt stɔːl/", "quầy hàng ở chợ", "She bought fresh fruit from a market stall."),
        ("national park", "/ˈnæʃ.ən.əl pɑːk/", "vườn quốc gia", "They camped in the national park."),
        ("hiking trail", "/ˈhaɪ.kɪŋ treɪl/", "đường mòn đi bộ dã ngoại", "Follow the marked hiking trail."),
        ("waterfall", "/ˈwɔː.tə.fɔːl/", "thác nước", "The waterfall is high and beautiful."),
        ("mountain peak", "/ˈmaʊn.tɪn piːk/", "đỉnh núi", "Snow covered the mountain peak."),
        ("canyon", "/ˈkæn.jən/", "hẻm núi lớn", "They hiked down into the deep canyon."),
        ("desert", "/ˈdez.ət/", "sa mạc", "Cacti grow in the hot desert."),
        ("beach resort", "/biːtʃ rɪˈzɔːt/", "khu nghỉ dưỡng bãi biển", "We booked a room at a beach resort."),
        ("swimming pool", "/ˈswɪm.ɪŋ puːl/", "bể bơi", "The hotel has an outdoor swimming pool."),
        ("seafood", "/ˈsiː.fuːd/", "hải sản", "They serve fresh seafood by the harbor."),
        ("umbrella", "/ʌmˈbrel.ə/", "cái ô, cái dù", "Take an umbrella in case it rains."),
        ("sunscreen", "/ˈsʌn.skriːn/", "kem chống nắng", "Apply sunscreen before going to the beach."),
        ("sunglasses", "/ˈsʌn.ɡlɑː.sɪz/", "kính râm, kính mát", "She wore dark sunglasses in the sun."),
        ("camera lens", "/ˈkæm.ər.ə lenz/", "ống kính máy ảnh", "Clean your camera lens regularly."),
        ("photo album", "/ˈfəʊ.təʊ ˈæl.bəm/", "cuốn album ảnh", "She put the holiday photos in an album."),
        ("postcard", "/ˈpəʊst.kɑːd/", "bưu thiếp", "Send a postcard to your family."),
        ("luggage tag", "/ˈlʌɡ.ɪdʒ tæɡ/", "thẻ ghi thông tin hành lý", "Write your name on the luggage tag."),
        ("backpack", "/ˈbæk.pæk/", "ba lô", "He packed his clothes into a backpack."),
        ("sleeping bag", "/ˈsliː.pɪŋ bæɡ/", "túi ngủ dã ngoại", "It got cold in the sleeping bag."),
        ("tent", "/tent/", "cái lều dã ngoại", "We set up our tent under the trees."),
        ("camping site", "/ˈkæm.pɪŋ saɪt/", "bãi cắm trại", "The camping site has hot showers."),
        ("travel agency", "/ˈtræv.əl ˈeɪ.dʒən.si/", "đại lý du lịch", "Book the tour through a travel agency."),
        ("map guide", "/mæp ɡaɪd/", "bản đồ chỉ dẫn", "The map guide shows historical sites."),
        ("information desk", "/ˌɪn.fəˈmeɪ.ʃən dɛsk/", "quầy thông tin", "Ask for a free map at the information desk."),
        ("currency", "/ˈkʌr.ən.si/", "tiền tệ", "Exchange your money for local currency."),
        ("exchange rate", "/ɪksˈtʃeɪndʒ reɪt/", "tỷ giá hối đoái", "The exchange rate is good today."),
        ("cash machine", "/kæʃ məˈʃiːn/", "máy rút tiền tự động ATM", "I need to find a cash machine."),
        ("credit card", "/ˈkred.ɪt kɑːd/", "thẻ tín dụng", "Can I pay by credit card?")
    ],
    "B1": [
        ("destination", "/ˌdestɪˈneɪʃn/", "điểm đến", "What is your final travel destination?"),
        ("itinerary", "/aɪˈtɪnərəri/", "lịch trình chuyến đi", "We planned our travel itinerary carefully."),
        ("accommodation", "/əˌkɒməˈdeɪʃn/", "chỗ ở, nơi lưu trú", "They booked a budget accommodation in Hanoi."),
        ("explore", "/ɪkˈsplɔː(r)/", "khám phá, thám hiểm", "We love to explore new places on weekends."),
        ("reservation", "/ˌrezəˈveɪʃn/", "sự đặt trước", "I made a hotel reservation online."),
        ("adventure", "/ədˈventʃə(r)/", "cuộc phiêu lưu", "He wrote a book about his desert adventure."),
        ("excursion", "/ɪkˈskɜːʃn/", "chuyến tham quan ngắn", "We went on a day excursion to the island."),
        ("passenger", "/ˈpæsɪndʒə(r)/", "hành khách", "All passengers must fasten their seatbelts."),
        ("scenic route", "/ˈsiː.nɪk ruːt/", "tuyến đường nhiều cảnh đẹp", "We took the scenic route through the mountains."),
        ("travel insurance", "/ˈtræv.əl ɪnˈʃɔː.rəns/", "bảo hiểm du lịch", "It is wise to buy travel insurance before going."),
        ("tourist season", "/ˈtʊə.rɪst ˈsiː.zən/", "mùa du lịch cao điểm", "Hotel rates double during the peak tourist season."),
        ("border crossing", "/ˈbɔː.dər ˈkrɒs.ɪŋ/", "cửa khẩu biên giới", "We faced long delays at the border crossing."),
        ("customs officer", "/ˈkʌs.təmz ˈɒf.ɪ.sər/", "nhân viên hải quan", "The customs officer inspected our luggage."),
        ("duty-free", "/ˌdʒuː.tiˈfriː/", "miễn thuế", "She bought perfume at the duty-free shop."),
        ("jet lag", "/ˈdʒet læɡ/", "sự mệt mỏi sau chuyến bay dài xuyên múi giờ", "Drinking water helps reduce the effects of jet lag."),
        ("time zone", "/ˈtaɪm zəʊn/", "múi giờ", "London and Hanoi are in different time zones."),
        ("local culture", "/ˈləʊ.kəl ˈkʌl.tʃər/", "văn hóa bản địa", "He respects and enjoys learning local culture."),
        ("historic site", "/hɪˈstɒr.ɪk saɪt/", "di tích lịch sử", "The temple is a protected historic site."),
        ("landmark", "/ˈlænd.mɑːk/", "cột mốc danh thắng nổi tiếng", "The Eiffel Tower is a famous global landmark."),
        ("monument", "/ˈmɒn.jə.mənt/", "đài tưởng niệm, tượng đài", "A stone monument stands in the town square."),
        ("heritage", "/ˈher.ɪ.tɪdʒ/", "di sản văn hóa/thiên nhiên", "Hoi An is a UNESCO world heritage site."),
        ("museum", "/mjuːˈziː.əm/", "bảo tàng", "The museum displays ancient artifacts."),
        ("art gallery", "/ɑːt ˈɡæl.ər.i/", "triển lãm nghệ thuật", "We visited an art gallery in Chelsea."),
        ("souvenir shop", "/ˌsuː.vənˈɪər ʃɒp/", "cửa hàng bán quà lưu niệm", "The souvenir shop was packed with tourists."),
        ("guidebook", "/ˈɡaɪdbʊk/", "sách hướng dẫn du lịch", "The guidebook recommends the best local cafes."),
        ("phrasebook", "/ˈfreɪzbʊk/", "sách cụm từ giao tiếp thông dụng", "Carry a phrasebook when visiting rural areas."),
        ("map reading", "/mæp ˈriː.dɪŋ/", "kỹ năng đọc bản đồ", "Map reading is an essential outdoor skill."),
        ("navigation", "/ˌnæv.ɪˈɡeɪ.ʃən/", "sự định hướng, điều hướng", "GPS navigation made driving much easier."),
        ("itinerary planner", "/aɪˈtɪn.ər.ər.i ˈplæn.ər/", "người lập lịch trình", "Use an online itinerary planner."),
        ("package holiday", "/ˈpæk.ɪdʒ ˈhɒl.ə.deɪ/", "kỳ nghỉ trọn gói", "We booked a package holiday to Mallorca."),
        ("travel voucher", "/ˈtræv.əl ˈvaʊ.tʃər/", "phiếu giảm giá du lịch", "You can redeem the travel voucher online."),
        ("cancellation fee", "/ˌkæn.səlˈeɪ.ʃən fiː/", "phí hủy dịch vụ", "The hotel charges a 50% cancellation fee."),
        ("check-in", "/ˈtʃek.ɪn/", "thủ tục nhận phòng/lên máy bay", "Check-in begins two hours before the flight."),
        ("check-out", "/ˈtʃek.aʊt/", "thủ tục trả phòng", "Hotel check-out is usually at noon."),
        ("boarding pass", "/ˈbɔː.dɪŋ pɑːs/", "thẻ lên tàu/máy bay", "Print your boarding pass at home."),
        ("excess baggage", "/ɪkˈses ˈbæɡ.ɪdʒ/", "hành lý quá cước", "We had to pay for excess baggage."),
        ("carry-on bag", "/ˈkær.i.ɒn bæɡ/", "hành lý xách tay lên máy bay", "Keep your passport in your carry-on bag."),
        ("hand luggage", "/hænd ˈlʌɡ.ɪdʒ/", "hành lý xách tay", "Put small liquids in your hand luggage."),
        ("security check", "/sɪˈkʊə.rə.ti tʃek/", "kiểm tra an ninh", "Empty your pockets at the security check."),
        ("metal detector", "/ˈmet.əl dɪˈtek.tər/", "máy dò kim loại", "Walk through the metal detector slowly."),
        ("customs declaration", "/ˈkʌs.təmz ˌdek.ləˈreɪ.ʃən/", "tờ khai hải quan", "Fill out the customs declaration form."),
        ("shuttle bus", "/ˈʃʌt.əl bʌs/", "xe buýt đưa đón chặng ngắn", "Take the hotel shuttle bus to the beach."),
        ("car rental", "/kɑːr ˈren.təl/", "dịch vụ thuê xe tự lái", "Arrange a car rental at the airport."),
        ("public transport", "/ˈpʌb.lɪk ˈtræn.spɔːt/", "phương tiện giao thông công cộng", "Use public transport to save money."),
        ("metro station", "/ˈmet.rəʊ ˈsteɪ.ʃən/", "ga tàu điện ngầm", "The metro station is just outside."),
        ("bus terminal", "/bʌs ˈtɜː.mɪ.nəl/", "bến xe buýt lớn", "The coach leaves from the central bus terminal."),
        ("railway network", "/ˈreɪl.weɪ ˈnet.wɜːk/", "mạng lưới đường sắt", "The railway network covers the whole country."),
        ("ferry terminal", "/ˈfer.i ˈtɜː.mɪ.nəl/", "bến phà", "We arrived at the ferry terminal at dawn."),
        ("departure lounge", "/dɪˈpɑː.tʃər laʊndʒ/", "phòng chờ khởi hành", "We waited in the departure lounge."),
        ("arrival hall", "/əˈraɪ.vəl hɔːl/", "sảnh đón khách đến", "He met his friends in the arrival hall.")
    ]
}
