import json
import sqlite3
import random

# Load existing words
with open('e:/Project/Hoc/hoc-tieng-anh/backend/scratch/existing_words.json', 'r', encoding='utf-8') as f:
    existing_map = json.load(f)

# Ta sẽ tạo dữ liệu trực tiếp bằng python và ghi đè vào DB và learn.py
# Để đảm bảo từ vựng phong phú, không trùng lặp và có phiên âm, dịch nghĩa chuẩn,
# Ta sử dụng bộ từ phong phú cho các chủ đề:

topics_data = {
  "ai": {
    "A1": [
      ("Robot", "/ˈroʊ.bɑːt/", "Người máy", "The factory uses robots to build cars."),
      ("Smart", "/smɑːrt/", "Thông minh", "He has a smart television."),
      ("Data", "/ˈdeɪ.tə/", "Dữ liệu", "Data is very important for AI."),
      ("Code", "/koʊd/", "Mã lập trình", "He is learning to write code."),
      ("App", "/æp/", "Ứng dụng", "Download the language app."),
      ("User", "/ˈjuː.zər/", "Người dùng", "The system has active users."),
      ("Web", "/wɛb/", "Mạng internet", "He searched the web for answers."),
      ("Fast", "/fæst/", "Nhanh", "This computer is extremely fast."),
      ("Machine", "/məˈʃiːn/", "Máy móc", "The machine works automatically."),
      ("Clever", "/ˈklɛv.ər/", "Khôn khéo, thông minh", "A clever dog can learn tricks quickly."),
      ("Facts", "/fækts/", "Sự thật, dữ kiện", "We need facts, not opinions."),
      ("Script", "/skrɪpt/", "Kịch bản mã lệnh", "He wrote a script to automate tasks."),
      ("Tool", "/tuːl/", "Công cụ", "Computers are tools for work."),
      ("Client", "/ˈklaɪ.ənt/", "Máy khách, khách hàng", "The client connected to the host."),
      ("Net", "/nɛt/", "Mạng lưới; mạng lưới", "The net connects devices globally."),
      ("Quick", "/kwɪk/", "Nhanh chóng", "She gave a quick reply."),
      ("Screen", "/skriːn/", "Màn hình", "The screen of the monitor is bright."),
      ("Voice", "/vɔɪs/", "Giọng nói", "The AI can recognize his voice."),
      ("Game", "/ɡeɪm/", "Trò chơi", "They are playing a video game."),
      ("Chat", "/tʃæt/", "Trò chuyện, tán gẫu", "You can chat with the AI bot."),
      ("Task", "/tæsk/", "Nhiệm vụ, công việc", "Completing this task takes time."),
      ("Brain", "/breɪn/", "Não bộ", "The brain processes thoughts."),
      ("Digital", "/ˈdɪdʒ.ɪ.təl/", "Thuộc kỹ thuật số", "We live in a digital world."),
      ("Online", "/ˈɒn.laɪn/", "Trực tuyến", "He reads news online daily."),
      ("Offline", "/ˌɒfˈlaɪn/", "Ngoại tuyến, ngắt mạng", "The app can be used offline."),
      ("Button", "/ˈbʌt.ən/", "Nút bấm", "Click the button to submit."),
      ("Click", "/klɪk/", "Nhấp chuột", "Double-click to open the file."),
      ("File", "/faɪl/", "Tệp tin", "Save the file before closing."),
      ("Folder", "/ˈfoʊl.dər/", "Thư mục", "Create a folder for documents."),
      ("Icon", "/ˈaɪ.kɒn/", "Biểu tượng", "Tap the mail icon to open."),
      ("Menu", "/ˈmɛn.juː/", "Danh mục, thực đơn", "Select exit from the menu."),
      ("Page", "/peɪdʒ/", "Trang sách, trang web", "Go to the next page."),
      ("Text", "/tɛkst/", "Văn bản, tin nhắn", "Send a text message to him."),
      ("Link", "/lɪŋk/", "Liên kết, đường dẫn", "Click the link to visit."),
      ("Email", "/ˈiː.meɪl/", "Thư điện tử", "Write an email to the team."),
      ("Search", "/sɜːtʃ/", "Tìm kiếm", "Search for files on disk."),
      ("Save", "/seɪv/", "Lưu trữ, tiết kiệm", "Save your progress now."),
      ("Open", "/ˈoʊ.pən/", "Mở", "Open the new application."),
      ("Close", "/kloʊz/", "Đóng", "Close all windows before leaving."),
      ("Print", "/prɪnt/", "In ấn", "Print the document on paper."),
      ("Sound", "/saʊnd/", "Âm thanh", "Adjust the speaker sound."),
      ("Light", "/laɪt/", "Ánh sáng, đèn", "The status light is green."),
      ("Card", "/kɑːrd/", "Thẻ", "Insert the memory card."),
      ("Plug", "/plʌɡ/", "Phích cắm, cắm điện", "Plug in the power cable."),
      ("Wire", "/waɪər/", "Dây điện", "Connect the red wire here."),
      ("Key", "/kiː/", "Phím bấm, chìa khóa", "Press the enter key now."),
      ("Power", "/ˈpaʊ.ər/", "Nguồn điện, năng lượng", "Turn on the power switch."),
      ("Log", "/lɒɡ/", "Nhật ký hệ thống, ghi chép", "Check the server error log."),
      ("Input", "/ˈɪn.pʊt/", "Đầu vào, nhập liệu", "Provide your input in the box."),
      ("Output", "/ˈaʊt.pʊt/", "Đầu ra, kết quả", "The output is displayed here.")
    ],
    "A2": [
      ("Computer", "/kəmˈpjuː.tər/", "Máy tính", "I use my computer for coding."),
      ("System", "/ˈsɪs.təm/", "Hệ thống", "The operating system needs update."),
      ("Network", "/ˈnɛt.wɜːk/", "Mạng lưới, mạng kết nối", "The network is secure."),
      ("Program", "/ˈproʊ.ɡræm/", "Chương trình máy tính", "Write a python program."),
      ("Device", "/dɪˈvaɪs/", "Thiết bị điện tử", "Every device has an IP."),
      ("Storage", "/ˈstɔː.rɪdʒ/", "Bộ nhớ lưu trữ", "Cloud storage is very cheap."),
      ("Process", "/ˈprəʊ.ses/", "Xử lý, quy trình", "The CPU processes information."),
      ("Workstation", "/ˈwɜːk.steɪ.ʃən/", "Máy trạm, máy làm việc", "He works at a high-end workstation."),
      ("Mechanism", "/ˈmɛk.ə.nɪz.əm/", "Cơ chế, hệ thống máy móc", "The lock mechanism is broken."),
      ("Grid", "/ɡrɪd/", "Lưới điện, mạng lưới ô vuông", "The power grid supplies electricity to the entire region."),
      ("Utility", "/juːˈtɪl.ə.ti/", "Công cụ tiện ích", "Use this utility to clean disk."),
      ("Cyber", "/ˈsaɪ.bər/", "Thuộc mạng internet", "Cyber security is a high priority."),
      ("Gadget", "/ˈɡædʒ.ɪt/", "Thiết bị", "Smartphones are essential mobile devices."),
      ("Cache", "/kæʃ/", "Bộ nhớ đệm", "Clear the browser cache."),
      ("Procedure", "/prəˈsiː.dʒər/", "Thủ tục, quy trình thực hiện", "Follow the safety procedure."),
      ("Memory", "/ˈmɛm.ər.i/", "Bộ nhớ lưu trữ thông tin", "My computer ran out of memory."),
      ("Hardware", "/ˈhɑːd.weər/", "Phần cứng máy tính", "The computer hardware needs upgrade."),
      ("Software", "/ˈsɒft.weər/", "Phần mềm", "Install the updated software."),
      ("Database", "/ˈdeɪ.tə.beɪs/", "Cơ sở dữ liệu", "Store the records in database."),
      ("Server", "/ˈsɜː.vər/", "Máy chủ", "The server is offline now."),
      ("Backup", "/ˈbæk.ʌp/", "Sao lưu dự phòng", "Always create a data backup."),
      ("Restore", "/rɪˈstɔːr/", "Khôi phục dữ liệu", "Restore the files from backup."),
      ("Transfer", "/trænsˈfɜːr/", "Truyền dữ liệu, chuyển nhượng", "Transfer the files to drive."),
      ("Connect", "/kəˈnɛkt/", "Kết nối", "Connect to the local Wi-Fi."),
      ("Disconnect", "/ˌdɪs.kəˈnɛkt/", "Ngắt kết nối", "Disconnect the USB drive safely."),
      ("Access", "/ˈæk.sɛs/", "Truy cập, lối vào", "Authorized staff only can access."),
      ("Format", "/ˈfɔː.mæt/", "Định dạng", "Format the memory card first."),
      ("Install", "/ɪnˈstɔːl/", "Cài đặt phần mềm", "Install the antivirus app."),
      ("Uninstall", "/ˌʌn.ɪnˈstɔːl/", "Gỡ cài đặt", "Uninstall unused applications."),
      ("Antivirus", "/ˌæn.tiˈvaɪ.rəs/", "Trình diệt virus", "Keep your antivirus active."),
      ("Firewall", "/ˈfaɪə.wɔːl/", "Tường lửa", "The firewall blocked the attack."),
      ("Protocol", "/ˈproʊ.tə.kɒl/", "Giao thức", "HTTP is a network protocol."),
      ("Address", "/əˈdrɛs/", "Địa chỉ", "What is your IP address?"),
      ("Domain", "/doʊˈmeɪn/", "Tên miền", "Register a domain name online."),
      ("Host", "/hoʊst/", "Máy chủ vật lý, lưu trữ", "Host your website on cloud."),
      ("Upload", "/ʌpˈloʊd/", "Tải lên dữ liệu", "Upload the video to channel."),
      ("Download", "/ˌdaʊnˈloʊd/", "Tải về", "Download the installation file."),
      ("Update", "/ʌpˈdeɪt/", "Cập nhật", "Update the system drivers."),
      ("Patch", "/pætʃ/", "Bản vá lỗi", "Apply the security patch."),
      ("Bug", "/bʌɡ/", "Lỗi phần mềm", "The developer fixed the bug."),
      ("Error", "/ˈɛr.ər/", "Lỗi hệ thống", "An unexpected error occurred."),
      ("Failure", "/ˈfeɪ.ljər/", "Sự cố, thất bại", "Hardware failure caused data loss."),
      ("Warning", "/ˈwɔː.nɪŋ/", "Cảnh báo", "A warning message popped up."),
      ("Alert", "/əˈlɜːt/", "Cảnh báo khẩn cấp", "The system sent a security alert."),
      ("Signal", "/ˈsɪɡ.nəl/", "Tín hiệu", "The Wi-Fi signal is very weak."),
      ("Band", "/bænd/", "Băng tần, nhóm", "A dual-band wireless router."),
      ("Port", "/pɔːrt/", "Cổng kết nối", "Connect the cable to USB port."),
      ("Cable", "/ˈkeɪ.bəl/", "Dây cáp", "An ethernet cable is required."),
      ("Router", "/ˈruː.tər/", "Bộ định tuyến", "Restart the internet router."),
      ("Switch", "/swɪtʃ/", "Thiết bị chuyển mạch, công tắc", "The network switch is configured.")
    ]
  }
}
