# Bổ sung dữ liệu Marketing (A1-C1) đầy đủ 50 từ mỗi cấp tránh trùng lặp 100%

marketing_vocab = {
    "A1": [
        ("buy", "/baɪ/", "mua hàng hóa/dịch vụ", "I want to buy a new smartphone."),
        ("sell", "/sɛl/", "bán hàng hóa/dịch vụ", "They sell high-quality laptops."),
        ("shop", "/ʃɒp/", "cửa hàng bán lẻ", "Let's visit the clothing shop."),
        ("ad", "/æd/", "mẫu quảng cáo nhỏ", "I saw a funny ad on YouTube."),
        ("logo", "/ˈloʊ.ɡoʊ/", "biểu trưng thương hiệu", "The logo is red and white."),
        ("brand", "/brænd/", "nhãn hiệu, thương hiệu", "Apple is a famous technology brand."),
        ("price", "/praɪs/", "giá bán sản phẩm", "The price of the phone is high."),
        ("cost", "/kɒst/", "chi phí sản xuất/mua", "The production cost is low."),
        ("sale", "/seɪl/", "chương trình giảm giá, việc bán", "The big summer sale starts today."),
        ("free", "/friː/", "miễn phí hoàn toàn", "Buy one, get one free."),
        ("gift", "/ɡɪft/", "quà tặng kèm theo", "Every customer gets a free gift."),
        ("bill", "/bɪl/", "hóa đơn thanh toán tiền", "Please pay the internet bill."),
        ("pay", "/peɪ/", "thanh toán bằng tiền", "You can pay by credit card."),
        ("cash", "/kæʃ/", "tiền mặt vật lý", "The shop only accepts cash."),
        ("card", "/kɑːrd/", "thẻ ngân hàng để thanh toán", "Swipe your card to pay."),
        ("bag", "/bæɡ/", "túi xách đựng hàng", "Put the groceries in the bag."),
        ("box", "/bɒks/", "hộp các-tông đóng gói", "The laptop is in a cardboard box."),
        ("sign", "/saɪn/", "bảng hiệu quảng cáo", "Read the sign on the shop door."),
        ("word", "/wɜːd/", "từ ngữ, lời nói", "Word of mouth is powerful."),
        ("mail", "/meɪl/", "thư từ quảng cáo", "Send the catalog via mail."),
        ("deal", "/diːl/", "giao dịch, thỏa thuận tốt", "This is a great deal on shoes."),
        ("save", "/seɪv/", "tiết kiệm tiền/chi phí", "Use coupons to save money."),
        ("spend", "/spɛnd/", "tiêu dùng tiền bạc", "Don't spend too much money."),
        ("want", "/wɒnt/", "mong muốn mua sắm", "I want a new mechanical keyboard."),
        ("need", "/niːd/", "nhu cầu thiết yếu", "I need some printer paper."),
        ("find", "/faɪnd/", "tìm thấy sản phẩm tốt", "Find the best deals online."),
        ("try", "/traɪ/", "thử nghiệm sản phẩm mới", "Try the product before buying."),
        ("like", "/laɪk/", "thích thú sản phẩm", "Customers like friendly service."),
        ("good", "/ɡʊd/", "sản phẩm chất lượng tốt", "This is a very good brand."),
        ("new", "/njuː/", "sản phẩm mới ra mắt", "We launched a new product line."),
        ("old", "/oʊld/", "mẫu mã sản phẩm cũ", "They are selling old models cheap."),
        ("best", "/bɛst/", "tốt nhất, cao cấp nhất", "This is our best-selling book."),
        ("cheap", "/tʃiːp/", "giá rẻ, bình dân", "This shop sells cheap clothes."),
        ("high", "/haɪ/", "giá bán ở mức cao", "High prices reduce sales."),
        ("low", "/loʊ/", "giá bán ở mức thấp", "Low prices attract buyers."),
        ("show", "/ʃoʊ/", "buổi trình diễn, triển lãm", "Visit our product show."),
        ("market", "/ˈmɑː.kɪt/", "thị trường mua bán", "Target the local market first."),
        ("client", "/ˈklaɪ.ənt/", "khách hàng thân thiết", "We met with an important client."),
        ("customer", "/ˈkʌs.tə.mər/", "người mua hàng hóa", "The customer is always right."),
        ("product", "/ˈprɒd.ʌkt/", "sản phẩm hàng hóa", "Our product has a full warranty."),
        ("service", "/ˈsɜː.vɪs/", "dịch vụ đi kèm", "The after-sales service is excellent."),
        ("advertisement", "/ədˈvɜː.tɪs.mənt/", "mẫu quảng cáo chính thức", "We placed an advertisement in the newspaper."),
        ("commercial", "/kəˈmɜː.ʃəl/", "quảng cáo trên truyền hình/radio", "The TV commercial was very popular."),
        ("media", "/ˈmiː.di.ə/", "các kênh truyền thông đại chúng", "Advertise across multiple social media platforms."),
        ("publicity", "/pʌbˈlɪs.ə.ti/", "sự quảng bá công chúng rộng rãi", "The new campaign generated good publicity."),
        ("promotion", "/prəˈməʊ.ʃən/", "chương trình khuyến mãi lớn", "Join our special weekend promotion."),
        ("marketing", "/ˈmɑː.kɪ.tɪŋ/", "hoạt động tiếp thị quảng bá", "Digital marketing is key to modern growth."),
        ("advertising", "/ˈæd.və.taɪ.zɪŋ/", "hoạt động quảng cáo thương mại", "We allocated a big budget for digital advertising."),
        ("public relations", "/ˈpʌb.lɪk rɪˈleɪ.ʃənz/", "hoạt động quan hệ công chúng PR", "The PR team managed the public relations campaign."),
        ("campaign", "/kæmˈpeɪn/", "chiến dịch tiếp thị/quảng cáo", "Launch the new winter campaign.")
    ]
}
