# Bổ sung dữ liệu Tech B1 đầy đủ 50 từ không trùng lặp

tech_b1 = {
    "B1": [
        ("innovation", "/ˌɪn.əˈveɪ.ʃən/", "sự đổi mới, sáng chế", "Technology drives business innovation."),
        ("bandwidth", "/ˈbænd.wɪdθ/", "băng thông mạng internet", "Streaming 4K video requires high bandwidth."),
        ("cybersecurity", "/ˌsaɪ.bə.sɪˈkjʊə.rə.ti/", "an ninh mạng máy tính", "The firm invested heavily in cybersecurity."),
        ("cloud computing", "/klaʊd kəmˈpjuː.tɪŋ/", "điện toán đám mây", "We host our database using cloud computing."),
        ("virtual reality", "/ˌvɜː.tʃu.əl riˈæl.ə.ti/", "công nghệ thực tế ảo (VR)", "Virtual reality is used in pilot training."),
        ("wearable", "/ˈweə.rə.bəl/", "thiết bị công nghệ đeo trên người", "Smart watches are popular wearables."),
        ("streaming", "/ˈstriː.mɪŋ/", "phát trực tuyến luồng dữ liệu", "Live streaming is very popular on social media."),
        ("gadget", "/ˈɡædʒ.ɪt/", "thiết bị công nghệ nhỏ tiện ích", "He loves buying the latest kitchen gadgets."),
        ("encryption", "/ɪnˈkrɪp.ʃən/", "sự mã hóa dữ liệu bảo mật", "Data encryption protects sensitive documents."),
        ("decryption", "/diːˈkrɪp.ʃən/", "sự giải mã dữ liệu", "The software handles decryption automatically."),
        ("server room", "/ˈsɜː.vər ruːm/", "phòng chứa máy chủ", "The server room requires air conditioning."),
        ("backup drive", "/ˈbæk.ʌp draɪv/", "ổ đĩa sao lưu dự phòng", "Keep a backup drive in a secure place."),
        ("data recovery", "/ˈdeɪ.tə rɪˈkʌv.ər.i/", "khôi phục dữ liệu đã mất", "We hired a data recovery specialist."),
        ("local network", "/ˈləʊ.kəl ˈnet.wɜːk/", "mạng nội bộ gia đình/văn phòng", "The printer is connected to the local network."),
        ("broadband", "/ˈbrɔːd.bænd/", "mạng băng thông rộng", "Broadband internet is available in rural areas."),
        ("fiber optic", "/ˌfaɪ.bər ˈɒp.tɪk/", "cáp quang siêu tốc", "Fiber optic cables provide fast speeds."),
        ("ethernet", "/ˈiː.θə.net/", "cổng/mạng dây ethernet", "Connect the computer via ethernet."),
        ("ip address", "/ˌaɪˈpiː əˈdres/", "địa chỉ giao thức internet IP", "The system log recorded his IP address."),
        ("domain name", "/dəʊˈmeɪn neɪm/", "tên miền website", "Choose a memorable domain name."),
        ("web hosting", "/web ˈhəʊ.stɪŋ/", "dịch vụ lưu trữ website", "We pay a monthly fee for web hosting."),
        ("system administrator", "/ˈsɪs.təm ədˈmɪn.ɪ.streɪ.tər/", "quản trị viên hệ thống mạng", "Contact the system administrator to reset your password."),
        ("developer", "/dɪˈvel.ə.pər/", "nhà phát triển, lập trình viên", "She works as a frontend web developer."),
        ("designer", "/dɪˈzaɪ.nər/", "nhà thiết kế giao diện/trải nghiệm", "The UI designer improved the button layout."),
        ("beta version", "/ˈbiː.tə ˈvɜː.ʃən/", "phiên bản thử nghiệm beta", "The app is currently in beta version."),
        ("bug report", "/bʌɡ rɪˈpɔːt/", "bản báo cáo lỗi phần mềm", "Submit a bug report to the support team."),
        ("software patch", "/ˈsɒft.weər pætʃ/", "bản vá lỗi phần mềm", "The developer released a software patch."),
        ("compatibility", "/kəmˌpæt.əˈbɪl.ə.ti/", "tính tương thích hệ thống", "Check the compatibility of the software."),
        ("performance", "/pəˈfɔː.məns/", "hiệu năng, hiệu suất hoạt động", "The upgrade improved overall system performance."),
        ("efficiency", "/ɪˈfɪʃ.ən.si/", "hiệu suất, năng suất làm việc", "The new algorithm increased efficiency."),
        ("stability", "/stəˈbɪl.ə.ti/", "sự ổn định hoạt động", "The server update improved stability."),
        ("reliability", "/rɪˌlaɪ.əˈbɪl.ə.ti/", "độ tin cậy của thiết bị", "We need a router with high reliability."),
        ("redundancy", "/rɪˈdʌn.dən.si/", "tính dự phòng hệ thống khi gặp sự cố", "Data redundancy prevents loss during hardware failure."),
        ("virtualization", "/ˌvɜː.tʃu.ə.laɪˈzeɪ.ʃən/", "công nghệ ảo hóa máy chủ", "Virtualization reduces hardware costs."),
        ("hypervisor", "/ˈhaɪ.pər.vaɪ.zər/", "phần mềm quản lý ảo hóa", "The hypervisor manages multiple operating systems."),
        ("virtual machine", "/ˌvɜː.tʃu.əl məˈʃiːn/", "máy ảo chạy song song", "Run the old application in a virtual machine."),
        ("cloud storage", "/klaʊd ˈstɔː.rɪdʒ/", "bộ nhớ lưu trữ đám mây", "We save our photos using cloud storage."),
        ("synchronization", "/ˌsɪŋ.krə.naɪˈzeɪ.ʃən/", "sự đồng bộ hóa dữ liệu", "Enable automatic synchronization for your files."),
        ("sync", "/sɪŋk/", "đồng bộ hóa nhanh", "Sync your phone with your computer."),
        ("credentials", "/krɪˈden.ʃəlz/", "thông tin xác thực đăng nhập", "Enter your login credentials to access."),
        ("authentication", "/ɔːˌθen.tɪˈkeɪ.ʃən/", "xác thực người dùng danh tính", "Two-factor authentication adds extra security."),
        ("authorization", "/ˌɔː.θər.aɪˈzeɪ.ʃən/", "sự cấp quyền truy cập hệ thống", "You need authorization to view these files."),
        ("permission", "/pəˈmɪʃ.ən/", "quyền hạn thao tác file", "Change file permission to read-only."),
        ("directory", "/dɪˈrek.tər.i/", "thư mục chứa tệp hệ thống", "Open the root directory of the disk."),
        ("root folder", "/ruːt ˈfəʊl.dər/", "thư mục gốc cao nhất", "Find the configuration file in the root folder."),
        ("file system", "/faɪl ˈsɪs.təm/", "hệ thống quản lý tệp", "NTFS is a common Windows file system."),
        ("disk partition", "/dɪsk pɑːˈtɪʃ.ən/", "phân vùng ổ đĩa", "Create a new disk partition for backup."),
        ("format drive", "/ˈfɔː.mæt draɪv/", "định dạng lại ổ đĩa xóa dữ liệu", "Format the drive to clear all data."),
        ("bad sector", "/bæd ˈsek.tər/", "phân vùng ổ đĩa bị lỗi vật lý", "The tool detected several bad sectors on the disk."),
        ("firmware", "/ˈfɜːm.weər/", "phần mềm hệ thống nhúng", "Update the router firmware to fix the issue."),
        ("hard drive", "/hɑːd draɪv/", "ổ đĩa cứng máy tính", "The hard drive is making a strange noise.")
    ]
}
