# Travel B2 và C1 đầy đủ 50 từ mỗi cấp không trùng lặp

travel_b2_c1 = {
    "B2": [
        ("expedition", "/ˌekspəˈdɪʃn/", "cuộc thám hiểm", "They organized an expedition to Antarctica."),
        ("picturesque", "/ˌpɪktʃəˈresk/", "đẹp như tranh vẽ", "The town is located in a picturesque valley."),
        ("breathtaking", "/ˈbreθteɪkɪŋ/", "hấp dẫn, ngoạn mục", "The mountain view was absolutely breathtaking."),
        ("hospitable", "/hɒˈspɪtəbl/", "hiếu khách, mến khách", "The local villagers were extremely hospitable."),
        ("spectacular", "/spekˈtækjələ(r)/", "ngoạn mục, hùng vĩ", "The fireworks display was truly spectacular."),
        ("wilderness", "/ˈwɪldənəs/", "vùng hoang dã", "They love camping in the deep wilderness."),
        ("sightseeing", "/ˈsaɪtsiːɪŋ/", "sự tham quan ngắm cảnh", "We did a lot of sightseeing in Paris."),
        ("transcontinental", "/ˌtrænzˌkɒntɪˈnentl/", "xuyên lục địa", "They took a transcontinental train trip."),
        ("sojourn", "/ˈsɒdʒɜːn/", "sự lưu trú tạm thời", "Our brief sojourn in Rome was delightful."),
        ("uncharted", "/ˌʌnˈtʃɑːtɪd/", "chưa được khảo sát, hoang sơ", "They sailed into uncharted waters."),
        ("peregrination", "/ˌperɪɡrɪˈneɪʃn/", "hành trình dài ngày, ngao du", "His novels tell of his peregrinations in Asia."),
        ("bespoke", "/bɪˈspəʊk/", "được thiết kế riêng, độc bản", "The agency designs bespoke travel experiences."),
        ("wanderlust", "/ˈwɒndəlʌst/", "sự cuồng đi, đam mê du lịch", "Her wanderlust led her to visit fifty countries."),
        ("unspoiled", "/ˌʌnˈspɔɪld/", "hoang sơ, chưa bị đô thị hóa", "We found a quiet, unspoiled island in Greece."),
        ("vagabond", "/ˈvæɡəbɒnd/", "kẻ ngao du, người đi đây đi đó", "He lived a vagabond lifestyle, moving from town to town."),
        ("ecotourism", "/ˈiː.kəʊˌtʊə.rɪ.zəm/", "du lịch sinh thái", "Costa Rica is a pioneer in ecotourism."),
        ("biodiversity", "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/", "đa dạng sinh học", "The rainforest is rich in biodiversity."),
        ("conservation", "/ˌkɒn.səˈveɪ.ʃən/", "sự bảo tồn thiên nhiên", "We support the conservation of wildlife sites."),
        ("indigenous", "/ɪnˈdɪdʒ.ɪ.nəs/", "bản địa, thổ dân", "We learned about the indigenous tribes."),
        ("cultural immersion", "/ˈkʌl.tʃər.əl ɪˈmɜː.ʃən/", "hòa nhập văn hóa trọn vẹn", "Homestays offer deep cultural immersion."),
        ("globetrotter", "/ˈɡləʊbˌtrɒt.ər/", "người đi du lịch khắp thế giới", "She has been a globetrotter since childhood."),
        ("overtourism", "/ˌəʊ.vəˈtʊə.rɪ.zəm/", "nạn quá tải du lịch", "Overtourism is threatening historic cities."),
        ("destination management", "/ˌdes.tɪˈneɪ.ʃən ˈmæn.ɪdʒ.mənt/", "quản lý điểm đến du lịch", "A new plan for sustainable destination management."),
        ("hospitality industry", "/ˌhɒs.pɪˈtæl.ə.ti ˈɪn.dəs.tri/", "ngành dịch vụ hiếu khách/khách sạn", "She works in the global hospitality industry."),
        ("leisure travel", "/ˈleɪ.ʒər ˈtræv.əl/", "du lịch nghỉ dưỡng", "Leisure travel has recovered quickly."),
        ("business travel", "/ˈbɪz.nɪs ˈtræv.əl/", "du lịch công tác", "He accumulates miles through business travel."),
        ("bleisure", "/ˈbliː.ʒər/", "du lịch công tác kết hợp nghỉ dưỡng", "Bleisure is a growing trend among young workers."),
        ("adventure tourism", "/ədˈven.tʃər ˈtʊə.rɪ.zəm/", "du lịch mạo hiểm", "He runs an adventure tourism company."),
        ("extreme sport", "/ɪkˈstriːm spɔːt/", "môn thể thao mạo hiểm", "Bungee jumping is an extreme sport."),
        ("safety gear", "/ˈseɪf.ti ɡɪər/", "trang bị bảo hộ an toàn", "Always wear safety gear during rock climbing."),
        ("instructor", "/ɪnˈstrʌk.tər/", "người hướng dẫn kỹ thuật", "The ski instructor showed us the basics."),
        ("first-aid kit", "/ˌfɜːstˈeɪd ˌkɪt/", "hộp sơ cứu y tế", "Keep a first-aid kit in your backpack."),
        ("emergency contact", "/ɪˈmɜː.dʒən.si ˈkɒn.tækt/", "thông tin liên hệ khẩn cấp", "Write down the emergency contact number."),
        ("travel advisory", "/ˈtræv.əl ædˈvaɪ.zər.i/", "cảnh báo an toàn du lịch", "Check the latest government travel advisory."),
        ("health certificate", "/helθ səˈtɪf.ɪ.kət/", "giấy chứng nhận sức khỏe", "A yellow fever health certificate is required."),
        ("vaccination card", "/ˌvæk.sɪˈneɪ.ʃən kɑːd/", "thẻ tiêm chủng ngừa dịch", "Keep your vaccination card with your passport."),
        ("quarantine", "/ˈkwɒr.ən.tiː/", "cách ly kiểm dịch", "Pets may face quarantine when entering."),
        ("baggage claim", "/ˈbæɡ.ɪdʒ kleɪm/", "khu vực nhận lại hành lý", "Retrieve your bags at the baggage claim area."),
        ("lost and found", "/lɒst ænd faʊnd/", "phòng tìm đồ thất lạc", "Inquire about the missing bag at lost and found."),
        ("boarding call", "/ˈbɔː.dɪŋ kɔːl/", "thông báo lên tàu/máy bay", "Listen for the final boarding call."),
        ("layover", "/ˈleɪ.əʊ.vər/", "điểm dừng nghỉ chặng ngắn giữa chuyến bay", "We had a six-hour layover in Doha."),
        ("stopover", "/ˈstɒp.əʊ.vər/", "điểm dừng chân dài ngày trong chuyến bay", "They enjoyed a three-day stopover in Singapore."),
        ("connecting flight", "/kəˈnek.tɪŋ flaɪt/", "chuyến bay chuyển tiếp, nối chuyến", "Hurry, we must catch our connecting flight."),
        ("delayed flight", "/dɪˈleɪd flaɪt/", "chuyến bay bị trễ giờ", "The delayed flight caused us to miss the tour."),
        ("cancelled flight", "/ˈkæn.səld flaɪt/", "chuyến bay bị hủy", "The airline rescheduled our cancelled flight."),
        ("rebooking", "/ˌriːˈbʊk.ɪŋ/", "việc đặt lại vé/phòng", "The agent handled the rebooking smoothly."),
        ("compensation", "/ˌkɒm.penˈsteɪ.ʃən/", "khoản bồi thường", "Passengers are entitled to financial compensation."),
        ("travel agency representative", "/ˈtræv.əl ˈeɪ.dʒən.si ˌrep.rɪˈzen.tə.tɪv/", "đại diện hãng du lịch", "The representative met us at the airport."),
        ("tourist information", "/ˈtʊə.rɪst ˌɪn.fəˈmeɪ.ʃən/", "thông tin du lịch", "Get brochures at the tourist information center."),
        ("city guide map", "/ˈsɪt.i ɡaɪd mæp/", "bản đồ chỉ dẫn thành phố", "A free city guide map is very helpful.")
    ],
    "C1": [
        ("expeditionary", "/ˌek.spəˈdɪʃ.ən.ər.i/", "thuộc đoàn thám hiểm, mạo hiểm", "He joined an expeditionary team in Africa."),
        ("picturesqueness", "/ˌpɪk.tʃərˈesk.nəs/", "vẻ đẹp như tranh, tính độc đáo", "Artists are drawn to the town's picturesqueness."),
        ("breathtakingly", "/ˈbreθˌteɪ.kɪŋ.li/", "đến mức ngoạn mục, choáng ngợp", "The mountains are breathtakingly beautiful."),
        ("hospitableness", "/ˈhɒs.pɪ.tə.bəl.nəs/", "sự hiếu khách, mến khách", "We were deeply moved by their hospitableness."),
        ("spectacularly", "/spekˈtæk.jə.lə.li/", "một cách ngoạn mục, lộng lẫy", "The ruins were spectacularly lit at night."),
        ("wilderness area", "/ˈwɪldənəs ˈeə.ri.ə/", "khu vực bảo tồn hoang dã", "The hiking trail crosses a strict wilderness area."),
        ("sightseer", "/ˈsaɪtˌsiː.ər/", "người đi tham quan ngắm cảnh", "Thousands of sightseers flock to the temple."),
        ("transcontinental route", "/ˌtrænzˌkɒntɪˈnentl ruːt/", "tuyến đường xuyên lục địa", "A famous transcontinental route for cyclists."),
        ("sojourner", "/ˈsɒdʒ.ɜː.nər/", "người lưu trú tạm thời, lữ khách", "He described himself as a temporary sojourner."),
        ("uncharted territory", "/ˌʌnˈtʃɑː.tɪd ˈter.ə.tər.i/", "lãnh thổ chưa có trên bản đồ", "Exploring deep caves is entering uncharted territory."),
        ("peregrinator", "/ˈpɛrɪɡrɪneɪtər/", "người đi ngao du khắp nơi", "He spent his life as a lonely peregrinator."),
        ("bespoke tailoring", "/bɪˈspəʊk ˈteɪ.lər.ɪŋ/", "dịch vụ may đo thiết kế riêng biệt", "Bespoke tailoring is a luxury service in London."),
        ("wanderlust-filled", "/ˈwɒndəlʌst fɪld/", "đầy đam mê du lịch lữ hành", "He wrote a wanderlust-filled blog about Asia."),
        ("unspoiled nature", "/ˌʌnˈspɔɪld ˈneɪ.tʃər/", "thiên nhiên hoang sơ nguyên bản", "We prefer destinations with unspoiled nature."),
        ("vagabonding", "/ˈvæɡəbɒndɪŋ/", "lối sống ngao du đây đó tự do", "He spent a year vagabonding around South America."),
        ("ecotourist", "/ˈiː.kəʊˌtʊə.rɪst/", "khách du lịch sinh thái bảo vệ môi trường", "Responsible ecotourists support local green projects."),
        ("biodiverse", "/ˌbaɪ.əʊ.daɪˈvɜːs/", "đa dạng sinh học phong phú", "The tropical coral reef is extremely biodiverse."),
        ("conservationist", "/ˌkɒn.səˈveɪ.ʃən.ɪst/", "nhà bảo tồn thiên nhiên", "Conservationists are fighting to save the forest."),
        ("indigeneity", "/ˌɪn.dɪ.dʒəˈneɪ.ə.ti/", "tính chất bản địa đặc trưng", "The festival celebrates local indigeneity."),
        ("cultural assimilation", "/ˈkʌl.tʃər.əl əˌsɪm.ɪˈleɪ.ʃən/", "sự đồng hóa văn hóa", "The immigrants resisted total cultural assimilation."),
        ("globetrotting", "/ˈɡləʊbˌtrɒt.ɪŋ/", "việc đi du lịch thế giới liên tục", "His globetrotting adventures were filmed for TV."),
        ("sustainable tourism", "/səˈsteɪ.nə.bəl ˈtʊə.rɪ.zəm/", "du lịch bền vững bảo vệ môi trường", "Ecotourism is a form of sustainable tourism."),
        ("destination marketing", "/ˌdes.tɪˈneɪ.ʃən ˈmɑː.kɪ.tɪŋ/", "tiếp thị quảng bá điểm đến du lịch", "The agency focuses on international destination marketing."),
        ("hospitality management", "/ˌhɒs.pɪˈtæl.ə.ti ˈmæn.ɪdʒ.mənt/", "quản trị dịch vụ nhà hàng khách sạn", "He holds a degree in hospitality management."),
        ("voluntourism", "/ˌvɒl.ənˈtʊə.rɪ.zəm/", "du lịch kết hợp tình nguyện", "Voluntourism allows travelers to help local schools."),
        ("heritage conservation", "/ˈher.ɪ.tɪdʒ ˌkɒn.səˈveɪ.ʃən/", "bảo tồn di sản lịch sử văn hóa", "Funds are allocated for heritage conservation."),
        ("curator", "/kjʊəˈreɪ.tər/", "giám đốc/người phụ trách bảo tàng", "The curator guided us through the art exhibition."),
        ("archaeological site", "/ˌɑː.ki.əˈlɒdʒ.ɪ.kəl saɪt/", "khảo cổ trường, khu di chỉ", "We visited an ancient archaeological site in Greece."),
        ("artifact preservation", "/ˈɑː.tɪ.fækt ˌprez.əˈveɪ.ʃən/", "bảo tồn cổ vật lịch sử", "The museum specialized in artifact preservation."),
        ("restoration project", "/ˌres.təˈreɪ.ʃən ˈprɒdʒ.ekt/", "dự án phục chế di tích cổ", "The cathedral is undergoing a major restoration project."),
        ("itinerary customization", "/aɪˈtɪn.ər.ər.i ˌkʌs.tə.maɪˈzeɪ.ʃən/", "tùy biến thiết kế lịch trình cá nhân", "Bespoke agencies offer full itinerary customization."),
        ("travel coordinator", "/ˈtræv.əl kəʊˈɔː.dɪ.neɪ.tər/", "điều phối viên hành trình du lịch", "The travel coordinator arranged all domestic flights."),
        ("expedition leader", "/ˌek.spəˈdɪʃ.ən ˈliː.dər/", "trưởng đoàn thám hiểm mạo hiểm", "The experienced expedition leader led the team safely."),
        ("wilderness survival", "/ˈwɪldənəs səˈvaɪ.vəl/", "kỹ năng sinh tồn nơi hoang dã", "He taught a course on wilderness survival skills."),
        ("navigational system", "/ˌnæv.ɪˈɡeɪ.ʃən.əl ˈsɪs.təm/", "hệ thống dẫn đường hàng hải/hàng không", "The ship relies on a redundant navigational system."),
        ("customs clearance", "/ˈkʌs.təmz ˈklɪə.rəns/", "thủ tục thông quan hải quan", "It took two hours to obtain customs clearance."),
        ("duty-free allowance", "/ˌdʒuː.tiˈfriː əˈlaʊ.əns/", "hạn mức mua hàng miễn thuế", "Keep purchases within the duty-free allowance limit."),
        ("layover duration", "/ˈlaɪˌoʊ.vər djʊˈreɪ.ʃən/", "thời lượng dừng chờ chặng bay", "A long layover duration can be highly exhausting."),
        ("connecting terminal", "/kəˈnek.tɪŋ ˈtɜː.mɪ.nəl/", "nhà ga hành khách chuyển tiếp", "Follow signs to the connecting terminal for international flights."),
        ("rebooking procedure", "/ˌriːˈbʊk.ɪŋ prəˈsiː.dʒər/", "quy trình đặt lại vé/phòng khẩn cấp", "The airline streamlined its automated rebooking procedure."),
        ("compensation claim", "/ˌkɒm.penˈsteɪ.ʃən kleɪm/", "yêu cầu đền bù thiệt hại tài chính", "File a compensation claim for the delayed baggage."),
        ("travel advisory board", "/ˈtræv.əl ædˈvaɪ.zər.i bɔːd/", "hội đồng cảnh báo du lịch quốc gia", "The travel advisory board updated safety alerts."),
        ("medical clearance", "/ˈmed.ɪ.kəl ˈklɪə.rəns/", "giấy phép y tế thông hành", "Obtain medical clearance before traveling to high-altitude areas."),
        ("quarantine officer", "/ˈkwɒr.ən.tiː ˈɒf.ɪ.sər/", "nhân viên kiểm dịch biên giới", "The quarantine officer checked the imported plants."),
        ("baggage handling", "/ˈbæɡ.ɪdʒ ˈhænd.lɪŋ/", "dịch vụ bốc dỡ hành lý sân bay", "Poor baggage handling led to many damaged suitcases."),
        ("lost property office", "/lɒst ˈprɒp.ə.ti ˈɒf.ɪs/", "phòng lưu giữ tài sản thất lạc", "Inquire about keys at the lost property office."),
        ("connecting flight booking", "/kəˈnek.tɪŋ flaɪt ˈbʊk.ɪŋ/", "đặt giữ chỗ chuyến bay nối tiếp", "Confirm your connecting flight booking in advance."),
        ("travel coordinator assistant", "/ˈtræv.əl kəʊˈɔː.dɪ.neɪ.tər əˈsɪs.tənt/", "trợ lý điều phối hành trình", "The assistant confirmed our hotel reservations."),
        ("itinerary builder", "/aɪˈtɪn.ər.ər.i ˈbɪl.dər/", "công cụ lập lịch trình cá nhân", "An online itinerary builder makes planning simple."),
        ("leisure traveler", "/ˈleɪ.ʒər ˈtræv.əl.ər/", "du khách nghỉ dưỡng giải trí", "Leisure travelers prefer direct flights to beach resorts.")
    ]
}
