# Đầy đủ Tech A2, B1, B2, C1 phong phú 50 từ mỗi cấp không trùng lặp

tech_remaining = {
    "A2": [
        ("smartphone", "/ˈsmɑːt.fəʊn/", "điện thoại thông minh", "I bought a new smartphone yesterday."),
        ("battery", "/ˈbæt.ər.i/", "cục pin nguồn", "The battery on this laptop lasts for ten hours."),
        ("download", "/ˌdaʊnˈləʊd/", "tải xuống tệp tin từ internet", "You can download the PDF file for free."),
        ("website", "/ˈweb.saɪt/", "trang thông tin điện tử, website", "We visited their official website to book tickets."),
        ("password", "/ˈpɑːs.wɜːd/", "mật khẩu bảo mật", "Never share your email password with anyone."),
        ("update", "/ʌpˈdeɪt/", "bản cập nhật phần mềm", "The new update fixes several system bugs."),
        ("connect", "/kəˈnekt/", "kết nối thiết bị", "Connect the keyboard to the USB port."),
        ("message", "/ˈmes.ɪdʒ/", "tin nhắn điện thoại", "She sent a text message to confirm."),
        ("cellphone", "/ˈsel.fəʊn/", "điện thoại di động cá nhân", "Keep your cellphone in your front pocket."),
        ("charger", "/ˈtʃɑː.dʒər/", "thiết bị sạc điện", "I left my phone charger at the office."),
        ("upload", "/ʌpˈləʊd/", "tải lên dữ liệu", "It took ten minutes to upload the video."),
        ("webpage", "/ˈweb.peɪdʒ/", "trang web đơn lẻ", "Bookmark the webpage for quick access."),
        ("passcode", "/ˈpɑːs.kəʊd/", "mật mã số mở khóa", "Enter your passcode to unlock the tablet screen."),
        ("upgrade", "/ʌpˈɡreɪd/", "sự nâng cấp hệ thống", "The software upgrade added new features."),
        ("link", "/lɪŋk/", "liên kết đường dẫn", "Click the link to join the meeting."),
        ("notice", "/ˈnəʊ.tɪs/", "thông báo, yết thị", "Read the notice on the official website."),
        ("wifi", "/ˈwaɪ.faɪ/", "mạng không dây wifi", "Is there free wifi in this coffee shop?"),
        ("hotspot", "/ˈhɒt.spɒt/", "điểm phát sóng wifi di động", "Use your phone as a personal hotspot."),
        ("bluetooth", "/ˈbluː.tuːθ/", "kết nối không dây bluetooth", "Turn on bluetooth to connect the headphones."),
        ("headset", "/ˈhed.set/", "tai nghe kèm mic", "She wore a wireless headset during the call."),
        ("earbuds", "/ˈɪə.bʌdz/", "tai nghe nhỏ đút tai", "He lost one of his wireless earbuds."),
        ("microphone", "/ˈmaɪ.krə.fəʊn/", "thiết bị thu âm, mic", "Is your microphone turned on?"),
        ("webcam", "/ˈweb.kæm/", "máy ảnh kết nối máy tính", "The webcam has a built-in privacy shield."),
        ("scanner", "/ˈskæn.ər/", "máy quét ảnh/tài liệu", "Scan the contract using the office scanner."),
        ("printer", "/ˈprɪn.tər/", "máy in tài liệu", "The printer is out of black ink."),
        ("cartridge", "/ˈkɑː.trɪdʒ/", "hộp mực máy in", "Replace the empty toner cartridge."),
        ("toner", "/ˈtəʊ.nər/", "mực in dạng bột", "Shake the toner cartridge before installing."),
        ("driver", "/ˈdraɪ.vər/", "trình điều khiển phần cứng", "Install the latest graphics driver."),
        ("monitor", "/ˈmɒn.ɪ.tər/", "màn hình máy tính chuyên dụng", "A 27-inch monitor is great for editing."),
        ("resolution", "/ˌrez.əˈluː.ʃən/", "độ phân giải màn hình", "The display supports 4K resolution."),
        ("pixel", "/ˈpɪk.səl/", "điểm ảnh đơn lẻ", "A high-resolution image has millions of pixels."),
        ("brightness", "/ˈbraɪt.nəs/", "độ sáng màn hình", "Turn down the screen brightness to save power."),
        ("contrast", "/ˈkɒn.trɑːst/", "độ tương phản hình ảnh", "Adjust the contrast for better visibility."),
        ("volume", "/ˈvɒl.juːm/", "âm lượng loa", "Turn down the volume, it is too loud."),
        ("mute", "/mjuːt/", "tắt tiếng hoàn toàn", "You are on mute, we cannot hear you."),
        ("unmute", "/ʌnˈmjuːt/", "mở lại tiếng", "Please unmute your microphone."),
        ("antivirus", "/ˌæn.tiˈvaɪ.rəs/", "phần mềm diệt virus", "Keep your antivirus software updated."),
        ("firewall", "/ˈfaɪə.wɔːl/", "tường lửa mạng", "The firewall blocked the unauthorized connection."),
        ("malware", "/ˈmæl.weər/", "phần mềm độc hại, virus", "Scan the system to remove malware."),
        ("spyware", "/ˈspaɪ.weər/", "phần mềm gián điệp theo dõi", "The spyware was designed to steal passwords."),
        ("phishing", "/ˈfɪʃ.ɪŋ/", "tấn công giả mạo lừa đảo", "Beware of phishing emails asking for bank details."),
        ("spam", "/spæm/", "thư rác, tin nhắn rác", "The spam filter catches most promotional emails."),
        ("inbox", "/ˈɪn.bɒks/", "hộp thư đến", "Check your inbox for the activation link."),
        ("outbox", "/ˈaʊt.bɒks/", "hộp thư đi đang chờ", "The email is stuck in my outbox."),
        ("draft", "/drɑːft/", "thư nháp chưa gửi", "I saved the email as a draft."),
        ("attachment", "/əˈtætʃ.mənt/", "tệp đính kèm trong email", "Please find the invoice in the attachment."),
        ("signature", "/ˈsɪɡ.nə.tʃər/", "chữ ký điện tử ở cuối thư", "He added a professional signature to his emails."),
        ("contact list", "/ˈkɒn.tækt lɪst/", "danh sách liên hệ, danh bạ", "Add her email to your contact list."),
        ("chat room", "/tʃæt ruːm/", "phòng chat trực tuyến", "Join the official team chat room."),
        ("status bar", "/ˈsteɪ.təs bɑːr/", "thanh trạng thái màn hình", "The battery percentage is in the status bar.")
    ]
}
