# Dữ liệu từ vựng đầy đủ cho chủ đề AI (A1-C1, 50 từ/cấp)
# Tránh các từ đã có: app, clever, client, code, data (A1); application_1, computer, connection, device, digital (A2);
# analyze, application, assistant, automation, dashboard (B1); autonomous, categorization, classification, corpus, creative (B2);
# artificial brain, attention mechanisms, backpropagation, cognitive computing, deep learning (C1)

AI_A1 = [
    ("robot", "/ˈroʊ.bɒt/", "người máy, robot", "The robot can help with household chores."),
    ("smart", "/smɑːrt/", "thông minh, tiên tiến", "This is a smart home system."),
    ("learn", "/lɜːrn/", "học, tiếp thu kiến thức", "Machines can learn from data."),
    ("think", "/θɪŋk/", "suy nghĩ, phân tích", "Can computers think like humans?"),
    ("talk", "/tɔːk/", "nói chuyện, giao tiếp", "The AI can talk back to you."),
    ("voice", "/vɔɪs/", "giọng nói", "The AI recognizes your voice."),
    ("screen", "/skriːn/", "màn hình hiển thị", "Look at the screen for the results."),
    ("text", "/tɛkst/", "văn bản, chữ viết", "The AI reads text quickly."),
    ("help", "/hɛlp/", "hỗ trợ, trợ giúp", "AI can help you find answers."),
    ("search", "/sɜːrtʃ/", "tìm kiếm thông tin", "Use AI to search for information."),
    ("find", "/faɪnd/", "tìm thấy, phát hiện ra", "AI can find patterns in large datasets."),
    ("fast", "/fæst/", "nhanh chóng, tốc độ cao", "Computers are very fast."),
    ("easy", "/ˈiː.zi/", "dễ dàng, thuận tiện", "AI makes tasks easy for people."),
    ("type", "/taɪp/", "gõ phím, đánh máy", "You can type a question for the AI."),
    ("send", "/sɛnd/", "gửi đi, truyền tải", "Send a message to the chatbot."),
    ("answer", "/ˈæn.sər/", "câu trả lời, trả lời", "The AI gave a quick answer."),
    ("ask", "/æsk/", "đặt câu hỏi", "Ask the AI assistant anything."),
    ("open", "/ˈoʊ.pən/", "mở ra, khởi chạy", "Open the AI app on your phone."),
    ("close", "/kloʊz/", "đóng lại, tắt", "Close the app when you are done."),
    ("number", "/ˈnʌm.bər/", "con số, số liệu", "Enter a number to start the calculation."),
    ("word", "/wɜːrd/", "từ ngữ trong văn bản", "The AI understands every word you type."),
    ("use", "/juːz/", "sử dụng, dùng", "We use AI every day now."),
    ("make", "/meɪk/", "tạo ra, làm ra", "AI can make images from text."),
    ("work", "/wɜːrk/", "làm việc, vận hành", "How does the AI system work?"),
    ("test", "/tɛst/", "kiểm tra, thử nghiệm", "We need to test the new model."),
    ("read", "/riːd/", "đọc, nhận dạng văn bản", "The scanner can read barcodes automatically."),
    ("write", "/raɪt/", "viết, soạn thảo văn bản", "AI can write short paragraphs."),
    ("play", "/pleɪ/", "chơi game, tương tác", "The AI can play chess better than humans."),
    ("see", "/siː/", "nhìn thấy, nhận dạng hình ảnh", "Cameras let AI see the world."),
    ("hear", "/hɪər/", "nghe, nhận dạng giọng nói", "The device can hear your commands."),
    ("picture", "/ˈpɪk.tʃər/", "hình ảnh", "The AI can analyze a picture."),
    ("sound", "/saʊnd/", "âm thanh", "The AI processes sound input."),
    ("button", "/ˈbʌt.ən/", "nút nhấn, nút bấm", "Press the button to start the AI."),
    ("input", "/ˈɪn.pʊt/", "dữ liệu đầu vào", "The input is processed by the AI."),
    ("output", "/ˈaʊt.pʊt/", "kết quả đầu ra", "The AI output was very accurate."),
    ("language", "/ˈlæŋ.ɡwɪdʒ/", "ngôn ngữ tự nhiên", "AI can understand many languages."),
    ("human", "/ˈhjuː.mən/", "con người, loài người", "AI is designed to help humans."),
    ("machine", "/məˈʃiːn/", "cỗ máy, thiết bị điện tử", "This machine uses artificial intelligence."),
    ("system", "/ˈsɪs.təm/", "hệ thống điều hành", "The AI system runs smoothly."),
    ("network", "/ˈnɛt.wɜːrk/", "mạng lưới kết nối", "The neural network is very complex."),
    ("question", "/ˈkwɛs.tʃən/", "câu hỏi cần giải đáp", "Ask the chatbot a question."),
    ("image", "/ˈɪm.ɪdʒ/", "hình ảnh kỹ thuật số", "The AI identifies objects in an image."),
    ("chat", "/tʃæt/", "trò chuyện trực tuyến", "Chat with the AI assistant today."),
    ("software", "/ˈsɒft.weər/", "phần mềm máy tính", "The AI software is updated daily."),
    ("program", "/ˈproʊ.ɡræm/", "chương trình phần mềm", "This program uses AI to translate."),
    ("tool", "/tuːl/", "công cụ, phần mềm hỗ trợ", "AI is a powerful productivity tool."),
    ("sensor", "/ˈsɛn.sər/", "cảm biến điện tử", "The sensor detects motion and sound."),
    ("command", "/kəˈmænd/", "lệnh điều khiển", "Give the voice command to start."),
    ("message", "/ˈmɛs.ɪdʒ/", "tin nhắn, thông điệp", "Send a message to the chatbot."),
    ("result", "/rɪˈzʌlt/", "kết quả đầu ra", "The AI produced an accurate result."),
]

AI_A2 = [
    ("algorithm", "/ˈæl.ɡə.rɪ.ðəm/", "thuật toán xử lý dữ liệu", "The algorithm sorts data efficiently."),
    ("model", "/ˈmɒd.əl/", "mô hình AI được huấn luyện", "We trained a language model."),
    ("train", "/treɪn/", "huấn luyện mô hình AI", "We need more data to train the model."),
    ("predict", "/prɪˈdɪkt/", "dự đoán kết quả", "The model can predict stock prices."),
    ("accuracy", "/ˈæk.jʊ.rə.si/", "độ chính xác của mô hình", "The model achieved 95% accuracy."),
    ("robot arm", "/ˈroʊ.bɒt ɑːrm/", "cánh tay robot công nghiệp", "The robot arm assembles car parts."),
    ("chatbot", "/ˈtʃæt.bɒt/", "trợ lý ảo chat tự động", "The chatbot answers customer questions."),
    ("dataset", "/ˈdeɪ.tə.sɛt/", "tập dữ liệu huấn luyện", "We need a large dataset to train."),
    ("pattern", "/ˈpæt.ərn/", "mẫu dữ liệu, xu hướng", "The AI finds patterns in the data."),
    ("decision", "/dɪˈsɪʒ.ən/", "quyết định tự động", "The AI makes decisions automatically."),
    ("natural language", "/ˈnætʃ.ər.əl ˈlæŋ.ɡwɪdʒ/", "ngôn ngữ tự nhiên của con người", "Natural language processing helps AI understand."),
    ("speech", "/spiːtʃ/", "lời nói, giọng nói", "Speech recognition is now very accurate."),
    ("recognition", "/ˌrɛk.əɡˈnɪʃ.ən/", "nhận dạng đối tượng, giọng nói", "Face recognition unlocks the phone."),
    ("translate", "/trænsˈleɪt/", "dịch thuật tự động", "AI can translate between 100 languages."),
    ("translation", "/trænsˈleɪʃ.ən/", "bản dịch tự động", "The AI translation was very accurate."),
    ("detection", "/dɪˈtɛk.ʃən/", "phát hiện và nhận diện", "The system uses object detection."),
    ("filter", "/ˈfɪl.tər/", "lọc dữ liệu, lọc nội dung", "The spam filter removes unwanted emails."),
    ("error", "/ˈɛr.ər/", "lỗi, sai số trong mô hình", "We need to reduce model errors."),
    ("update", "/ˈʌp.deɪt/", "cập nhật mô hình, dữ liệu", "Update the AI model regularly."),
    ("version", "/ˈvɜːr.ʒən/", "phiên bản phần mềm", "The latest version is more accurate."),
    ("interface", "/ˈɪn.tər.feɪs/", "giao diện người dùng", "The user interface is very friendly."),
    ("feature", "/ˈfiː.tʃər/", "tính năng của phần mềm", "This AI feature saves hours of work."),
    ("generate", "/ˈdʒɛn.ər.eɪt/", "tạo ra nội dung, dữ liệu", "The AI can generate realistic images."),
    ("response", "/rɪˈspɒns/", "phản hồi của hệ thống AI", "The chatbot response was helpful."),
    ("process", "/ˈproʊ.sɛs/", "xử lý dữ liệu, thông tin", "The AI processes millions of records."),
    ("speed", "/spiːd/", "tốc độ xử lý", "The processing speed is impressive."),
    ("memory", "/ˈmɛm.ər.i/", "bộ nhớ máy tính", "The model needs a lot of memory."),
    ("storage", "/ˈstɔːr.ɪdʒ/", "bộ nhớ lưu trữ", "Large datasets require cloud storage."),
    ("cloud", "/klaʊd/", "điện toán đám mây", "We store AI models in the cloud."),
    ("server", "/ˈsɜːr.vər/", "máy chủ, server", "The server runs the AI model 24/7."),
    ("database", "/ˈdeɪ.tə.beɪs/", "cơ sở dữ liệu", "The AI queries a large database."),
    ("label", "/ˈleɪ.bəl/", "nhãn dữ liệu gán cho mẫu", "Each image needs a correct label."),
    ("class", "/klæs/", "lớp phân loại dữ liệu", "The model predicts the correct class."),
    ("score", "/skɔːr/", "điểm đánh giá chất lượng mô hình", "The model scored 98% on the test."),
    ("task", "/tæsk/", "nhiệm vụ cụ thể của AI", "The AI completes the task quickly."),
    ("image recognition", "/ˈɪm.ɪdʒ ˌrɛk.əɡˈnɪʃ.ən/", "nhận dạng hình ảnh tự động", "Image recognition is used in smartphones."),
    ("recommendation", "/ˌrɛk.ə.mɛnˈdeɪ.ʃən/", "gợi ý cá nhân hóa", "Netflix uses recommendation algorithms."),
    ("user", "/ˈjuː.zər/", "người dùng hệ thống", "The AI adapts to each user's needs."),
    ("profile", "/ˈproʊ.faɪl/", "hồ sơ người dùng", "AI builds a profile based on behavior."),
    ("behavior", "/bɪˈheɪ.vjər/", "hành vi người dùng", "AI analyzes user behavior data."),
    ("instruction", "/ɪnˈstrʌk.ʃən/", "hướng dẫn sử dụng", "Follow the instructions carefully."),
    ("test data", "/tɛst ˈdeɪ.tə/", "dữ liệu kiểm thử mô hình", "We evaluate models with test data."),
    ("training data", "/ˈtreɪ.nɪŋ ˈdeɪ.tə/", "dữ liệu dùng để huấn luyện", "Training data quality is crucial."),
    ("performance", "/pərˈfɔːr.məns/", "hiệu suất vận hành của mô hình", "Track the model's performance daily."),
    ("simulation", "/ˌsɪm.jʊˈleɪ.ʃən/", "mô phỏng thực tế ảo", "AI runs a physical simulation."),
    ("virtual", "/ˈvɜːr.tʃʊ.əl/", "ảo, môi trường kỹ thuật số", "The virtual assistant is always available."),
    ("real-time", "/ˌriːl ˈtaɪm/", "xử lý theo thời gian thực", "Real-time AI provides instant responses."),
    ("audio", "/ˈɔː.di.oʊ/", "dữ liệu âm thanh đầu vào", "The AI processes audio files instantly."),
    ("video", "/ˈvɪd.i.oʊ/", "dữ liệu video cho AI phân tích", "AI can analyze video footage automatically."),
    ("platform", "/ˈplæt.fɔːrm/", "nền tảng phần mềm AI", "The AI platform supports many models."),
]

AI_B1 = [
    ("supervised learning", "/ˌsuː.pər.vaɪzd ˈlɜːr.nɪŋ/", "học có giám sát dùng dữ liệu gán nhãn", "Supervised learning uses labeled data."),
    ("unsupervised learning", "/ˌʌn.suː.pər.vaɪzd ˈlɜːr.nɪŋ/", "học không giám sát tự phát hiện mẫu", "Unsupervised learning finds hidden patterns."),
    ("reinforcement learning", "/rɪˈɪn.fɔːrs.mənt ˈlɜːr.nɪŋ/", "học tăng cường qua thưởng phạt", "Reinforcement learning trains game-playing AI."),
    ("neural network", "/ˈnjʊər.əl ˈnɛt.wɜːrk/", "mạng nơ-ron nhân tạo mô phỏng não", "The neural network has many layers."),
    ("training", "/ˈtreɪ.nɪŋ/", "quá trình huấn luyện mô hình", "Model training requires significant computing power."),
    ("inference", "/ˈɪn.fər.əns/", "suy diễn, dự đoán của mô hình", "Inference speed must be fast for real-time apps."),
    ("overfitting", "/ˌoʊ.vərˈfɪt.ɪŋ/", "hiện tượng mô hình học quá khớp", "Overfitting reduces model generalization."),
    ("underfitting", "/ˌʌn.dərˈfɪt.ɪŋ/", "hiện tượng mô hình học chưa đủ", "Underfitting causes poor predictions."),
    ("validation", "/ˌvæl.ɪˈdeɪ.ʃən/", "kiểm định hiệu suất mô hình", "Validation data checks model performance."),
    ("hyperparameter", "/ˌhaɪ.pər.pəˈræm.ɪ.tər/", "siêu tham số thiết lập cho mô hình", "Tune hyperparameters to improve accuracy."),
    ("epoch", "/ˈiː.pɒk/", "một vòng huấn luyện qua toàn bộ data", "Training for more epochs can improve results."),
    ("batch", "/bætʃ/", "lô dữ liệu nhỏ cho từng bước học", "Process data in small batches."),
    ("loss function", "/lɒs ˈfʌŋk.ʃən/", "hàm mất mát đo độ sai của mô hình", "Minimize the loss function during training."),
    ("optimizer", "/ˈɒp.tɪ.maɪ.zər/", "bộ tối ưu hóa tham số mô hình", "Adam is a popular AI optimizer."),
    ("gradient descent", "/ˈɡreɪ.di.ənt dɪˈsɛnt/", "phương pháp tối ưu hóa học máy", "Gradient descent updates model weights."),
    ("embedding", "/ɪmˈbɛd.ɪŋ/", "biểu diễn vector từ trong không gian số", "Word embeddings capture semantic meaning."),
    ("vector", "/ˈvɛk.tər/", "véc-tơ biểu diễn dữ liệu số học", "Each word is represented as a vector."),
    ("probability", "/ˌprɒb.əˈbɪl.ɪ.ti/", "xác suất xảy ra của một sự kiện", "The model returns prediction probabilities."),
    ("threshold", "/ˈθrɛʃ.hoʊld/", "ngưỡng quyết định phân loại", "Set the threshold for classification."),
    ("precision", "/prɪˈsɪʒ.ən/", "độ chính xác dương tính của mô hình", "High precision reduces false positives."),
    ("recall", "/rɪˈkɔːl/", "độ phủ dương tính của mô hình", "High recall reduces missed detections."),
    ("benchmark", "/ˈbɛntʃ.mɑːrk/", "tiêu chuẩn so sánh hiệu suất AI", "Run the benchmark to compare models."),
    ("tokenization", "/ˌtoʊ.kə.naɪˈzeɪ.ʃən/", "quá trình tách văn bản thành token", "Tokenization splits text into smaller units."),
    ("token", "/ˈtoʊ.kən/", "đơn vị ngôn ngữ cơ bản trong NLP", "Each word is broken into tokens."),
    ("sentiment analysis", "/ˈsɛn.tɪ.mənt əˈnæl.ɪ.sɪs/", "phân tích cảm xúc văn bản", "Sentiment analysis detects emotions in text."),
    ("object detection", "/ˈɒb.dʒɪkt dɪˈtɛk.ʃən/", "nhận dạng và khoanh vùng đối tượng", "Object detection locates items in photos."),
    ("generative AI", "/ˈdʒɛn.ər.ə.tɪv eɪ aɪ/", "AI tạo sinh nội dung sáng tạo", "Generative AI creates new music and art."),
    ("language model", "/ˈlæŋ.ɡwɪdʒ ˈmɒd.əl/", "mô hình ngôn ngữ xử lý văn bản", "A language model predicts the next word."),
    ("prompt", "/prɒmpt/", "câu lệnh đầu vào cho mô hình AI", "Write a clear prompt for better results."),
    ("context", "/ˈkɒn.tɛkst/", "ngữ cảnh giúp AI hiểu đúng ý nghĩa", "Context helps AI give better answers."),
    ("fine-tuning", "/ˈfaɪn ˌtjuː.nɪŋ/", "tinh chỉnh mô hình cho tác vụ cụ thể", "Fine-tuning adapts a model to a new task."),
    ("pretrained model", "/priːˈtreɪnd ˈmɒd.əl/", "mô hình đã huấn luyện sẵn trên data lớn", "Use a pretrained model to save time."),
    ("transfer learning", "/ˈtræns.fɜːr ˈlɜːr.nɪŋ/", "học chuyển tiếp dùng kiến thức đã học", "Transfer learning speeds up model training."),
    ("convolutional", "/ˌkɒn.vəˈluː.ʃən.əl/", "tích chập dùng trong mạng thị giác", "Convolutional layers process image features."),
    ("recurrent", "/rɪˈkɜːr.ənt/", "hồi quy dùng cho dữ liệu tuần tự", "Recurrent networks handle sequential data."),
]

AI_B2 = [
    ("transformer architecture", "/trænsˈfɔːr.mər ˈɑːr.kɪ.tɛk.tʃər/", "kiến trúc transformer nền tảng cho GPT", "Transformer architecture powers modern AI."),
    ("self-attention", "/sɛlf əˈtɛn.ʃən/", "cơ chế tự chú ý trong transformer", "Self-attention weighs word relationships."),
    ("encoder", "/ɪnˈkoʊ.dər/", "bộ mã hóa biểu diễn đầu vào", "The encoder maps text to a vector."),
    ("decoder", "/dɪˈkoʊ.dər/", "bộ giải mã tạo ra đầu ra", "The decoder generates output text."),
    ("regularization", "/ˌrɛɡ.jʊ.lər.aɪˈzeɪ.ʃən/", "điều chuẩn hóa tránh quá khớp mô hình", "Regularization prevents overfitting."),
    ("dropout", "/ˈdrɒp.aʊt/", "kỹ thuật bỏ ngẫu nhiên nơ-ron học", "Dropout reduces overfitting in networks."),
    ("activation function", "/ˌæk.tɪˈveɪ.ʃən ˈfʌŋk.ʃən/", "hàm kích hoạt phi tuyến trong mạng", "ReLU is a common activation function."),
    ("weight", "/weɪt/", "trọng số của kết nối nơ-ron", "Weights are updated during training."),
    ("bias", "/ˈbaɪ.əs/", "sai lệch trong mô hình thống kê", "Reduce bias to improve fairness."),
    ("explainability", "/ɪkˌspleɪ.nə.ˈbɪl.ɪ.ti/", "khả năng giải thích quyết định AI", "Explainability is crucial for medical AI."),
    ("interpretability", "/ɪnˌtɜːr.prɪ.tə.ˈbɪl.ɪ.ti/", "khả năng diễn giải hành vi mô hình", "Model interpretability builds user trust."),
    ("fairness", "/ˈfɛr.nɪs/", "tính công bằng trong quyết định AI", "Ensure fairness in AI hiring tools."),
    ("hallucination", "/həˌluː.sɪˈneɪ.ʃən/", "hiện tượng AI bịa đặt thông tin sai", "Large models can hallucinate facts."),
    ("grounding", "/ˈɡraʊn.dɪŋ/", "neo đậu AI vào thực tế đáng tin cậy", "Grounding reduces AI hallucinations."),
    ("multimodal", "/ˌmʌl.tɪˈmoʊ.dəl/", "đa phương thức xử lý văn bản và hình ảnh", "Multimodal AI understands text and images."),
    ("zero-shot learning", "/ˈzɪər.oʊ ʃɒt ˈlɜːr.nɪŋ/", "học không cần ví dụ mẫu huấn luyện", "Zero-shot learning requires no training examples."),
    ("few-shot learning", "/fjuː ʃɒt ˈlɜːr.nɪŋ/", "học từ rất ít ví dụ mẫu nhỏ", "Few-shot learning needs minimal data."),
    ("in-context learning", "/ɪn ˈkɒn.tɛkst ˈlɜːr.nɪŋ/", "học từ ngữ cảnh trong prompt đầu vào", "In-context learning uses examples in prompts."),
    ("retrieval-augmented generation", "/rɪˈtriː.vəl ˈɔːɡ.mɛn.tɪd ˌdʒɛn.əˈreɪ.ʃən/", "tăng cường tạo sinh bằng truy xuất thông tin", "RAG improves factual accuracy in chatbots."),
    ("knowledge graph", "/ˈnɒl.ɪdʒ ɡrɑːf/", "đồ thị tri thức liên kết các thực thể", "Knowledge graphs support AI reasoning."),
    ("foundation model", "/faʊnˈdeɪ.ʃən ˈmɒd.əl/", "mô hình nền tảng lớn cho nhiều tác vụ", "GPT is a large foundation model."),
    ("token limit", "/ˈtoʊ.kən ˈlɪm.ɪt/", "giới hạn số token đầu vào mô hình", "Stay within the model's token limit."),
    ("latency", "/ˈleɪ.tən.si/", "độ trễ phản hồi của hệ thống AI", "Reduce latency for a faster user experience."),
    ("throughput", "/ˈθruː.pʊt/", "lưu lượng xử lý của hệ thống AI", "High throughput is needed for large-scale AI."),
    ("scalability", "/ˌskeɪ.lə.ˈbɪl.ɪ.ti/", "khả năng mở rộng quy mô hệ thống", "Scalability is key for production AI."),
    ("pruning", "/ˈpruː.nɪŋ/", "cắt tỉa mô hình giảm kích thước và chi phí", "Model pruning reduces inference cost."),
    ("quantization", "/ˌkwɒn.tɪˈzeɪ.ʃən/", "lượng hóa giảm độ chính xác để tiết kiệm", "Quantization compresses model size."),
    ("distillation", "/ˌdɪs.tɪˈleɪ.ʃən/", "chắt lọc kiến thức từ mô hình lớn sang nhỏ", "Knowledge distillation creates smaller models."),
    ("synthetic data", "/sɪnˈθɛt.ɪk ˈdeɪ.tə/", "dữ liệu tổng hợp nhân tạo thay thế thật", "Synthetic data augments training datasets."),
    ("data augmentation", "/ˈdeɪ.tə ˌɔːɡ.mɛnˈteɪ.ʃən/", "tăng cường dữ liệu mở rộng tập huấn luyện", "Data augmentation improves model robustness."),
    ("anomaly detection", "/əˈnɒm.ə.li dɪˈtɛk.ʃən/", "phát hiện bất thường trong dữ liệu", "Anomaly detection flags unusual behavior."),
    ("clustering", "/ˈklʌs.tər.ɪŋ/", "phân cụm dữ liệu không có nhãn", "Clustering groups similar data points."),
    ("dimensionality reduction", "/daɪˌmɛn.ʃəˈnæl.ɪ.ti rɪˈdʌk.ʃən/", "giảm số chiều dữ liệu trong học máy", "PCA is a dimensionality reduction technique."),
    ("attention head", "/əˈtɛn.ʃən hɛd/", "đầu chú ý trong kiến trúc transformer", "More attention heads improve performance."),
    ("positional encoding", "/pəˈzɪʃ.ən.əl ɪnˈkoʊ.dɪŋ/", "mã hóa vị trí token trong transformer", "Positional encoding helps model understand order."),
]

AI_C1 = [
    ("alignment", "/əˈlaɪn.mənt/", "căn chỉnh AI với giá trị con người", "AI alignment ensures safe behavior."),
    ("constitutional AI", "/ˌkɒn.stɪˈtjuː.ʃən.əl eɪ aɪ/", "AI tuân theo bộ nguyên tắc đạo đức cố định", "Constitutional AI reduces harmful outputs."),
    ("RLHF", "/ˌɑːr.ɛl.eɪtʃˈɛf/", "học tăng cường từ phản hồi của con người", "RLHF aligns ChatGPT to human preferences."),
    ("emergent behavior", "/ɪˈmɜːr.dʒənt bɪˈheɪ.vjər/", "hành vi nổi sinh bất ngờ từ mô hình lớn", "Emergent behavior appears at scale."),
    ("chain-of-thought", "/tʃeɪn əv θɔːt/", "kỹ thuật prompt khai thác lý luận tuần tự", "Chain-of-thought prompting improves reasoning."),
    ("reasoning", "/ˈriː.zən.ɪŋ/", "suy luận logic từng bước của AI", "Advanced AI demonstrates multi-step reasoning."),
    ("meta-learning", "/ˈmɛt.ə ˈlɜːr.nɪŋ/", "học cách học nhanh hơn với ít dữ liệu", "Meta-learning enables faster adaptation."),
    ("continual learning", "/kənˈtɪn.jʊ.əl ˈlɜːr.nɪŋ/", "học liên tục mà không quên kiến thức cũ", "Continual learning avoids catastrophic forgetting."),
    ("federated learning", "/ˈfɛd.ər.eɪ.tɪd ˈlɜːr.nɪŋ/", "học liên kết bảo toàn riêng tư dữ liệu", "Federated learning protects user privacy."),
    ("differential privacy", "/ˌdɪf.ər.ˈɛn.ʃəl ˈprɪv.ə.si/", "quyền riêng tư vi phân bảo vệ dữ liệu", "Differential privacy adds statistical noise."),
    ("adversarial attack", "/ˌæd.vəˈseər.i.əl əˈtæk/", "tấn công đối kháng nhằm đánh lừa mô hình", "Adversarial attacks fool image classifiers."),
    ("robustness", "/roʊˈbʌst.nɪs/", "tính bền vững trước các đầu vào bất thường", "Model robustness is tested with edge cases."),
    ("generalization", "/ˌdʒɛn.ər.əl.aɪˈzeɪ.ʃən/", "khả năng tổng quát hóa sang dữ liệu mới", "Good generalization is key for deployment."),
    ("inductive bias", "/ɪnˈdʌk.tɪv ˈbaɪ.əs/", "thiên kiến quy nạp trong kiến trúc mô hình", "CNNs have a strong inductive bias for images."),
    ("causal inference", "/ˈkɔː.zəl ˈɪn.fər.əns/", "suy luận nhân quả phân biệt nguyên nhân kết quả", "Causal inference goes beyond correlation."),
    ("counterfactual reasoning", "/ˌkaʊn.tərˈfæk.tʃʊ.əl ˈriː.zən.ɪŋ/", "lý luận phản thực tế về tình huống giả định", "Counterfactual reasoning asks what if scenarios."),
    ("mechanistic interpretability", "/ˌmɛk.ə.ˈnɪs.tɪk ɪnˌtɜːr.prɪ.tə.ˈbɪl.ɪ.ti/", "diễn giải cơ chế nội tại của mô hình", "Mechanistic interpretability reveals model circuits."),
    ("superalignment", "/ˌsuː.pər.əˈlaɪn.mənt/", "căn chỉnh AI siêu thông minh với lợi ích nhân loại", "Superalignment research aims to control AGI."),
    ("AGI", "/ˌeɪ.dʒiːˈaɪ/", "trí tuệ tổng hợp ở mức độ con người", "AGI would match human-level cognition."),
    ("ASI", "/ˌeɪ.ɛsˈaɪ/", "trí tuệ siêu việt vượt trội hơn con người", "ASI could surpass all human intelligence."),
    ("mixture of experts", "/ˈmɪks.tʃər əv ˈɛk.spɜːrts/", "kiến trúc kết hợp nhiều mô hình chuyên biệt", "Mixture of experts scales model capacity."),
    ("sparse model", "/spɑːrs ˈmɒd.əl/", "mô hình thưa chỉ kích hoạt một phần", "Sparse models reduce computation cost."),
    ("context window", "/ˈkɒn.tɛkst ˈwɪn.doʊ/", "cửa sổ ngữ cảnh tối đa mô hình xử lý được", "A larger context window handles longer texts."),
    ("tool use", "/tuːl juːz/", "khả năng AI gọi công cụ bên ngoài tự động", "Tool use lets AI search the web."),
    ("agentic AI", "/eɪˈdʒɛn.tɪk eɪ aɪ/", "AI hành động tự chủ hoàn thành mục tiêu", "Agentic AI plans and executes multi-step tasks."),
    ("multi-agent system", "/ˌmʌl.tiˈeɪ.dʒənt ˈsɪs.təm/", "hệ thống nhiều agent AI phối hợp hoạt động", "Multi-agent systems coordinate specialized AIs."),
    ("reward shaping", "/rɪˈwɔːrd ˈʃeɪ.pɪŋ/", "tạo hình phần thưởng học tăng cường tinh vi", "Reward shaping guides the agent's learning."),
    ("policy gradient", "/ˈpɒl.ɪ.si ˈɡreɪ.di.ənt/", "gradient chính sách tối ưu hóa hành động", "Policy gradient methods train RL agents."),
    ("value function", "/ˈvæl.juː ˈfʌŋk.ʃən/", "hàm giá trị ước tính lợi ích trạng thái", "The value function estimates long-term reward."),
    ("Monte Carlo", "/ˌmɒn.ti ˈkɑːr.loʊ/", "phương pháp lấy mẫu ngẫu nhiên trong RL", "Monte Carlo methods estimate expected returns."),
    ("compute", "/kəmˈpjuːt/", "sức mạnh tính toán phần cứng cho AI", "More compute leads to better AI models."),
    ("FLOP", "/flɒp/", "phép tính dấu phẩy động đo lường tính toán", "Training GPT-4 required quadrillions of FLOPs."),
    ("scaling law", "/ˈskeɪ.lɪŋ lɔː/", "quy luật mở rộng hiệu suất AI theo tài nguyên", "Scaling laws predict model improvements."),
    ("capability elicitation", "/ˌkeɪ.pə.ˈbɪl.ɪ.ti ɪˌlɪs.ɪˈteɪ.ʃən/", "khai thác khả năng tiềm ẩn của mô hình", "Capability elicitation finds hidden model skills."),
]
