# Từ vựng Marketing, Job, Business - đầy đủ A1-C1

# ===== MARKETING =====
# Đã có B1: acquisition, analytics, branding, campaign, celebrity...

MARKETING_A1 = [
    ("buy", "/baɪ/", "mua hàng hóa", "I want to buy a new phone."),
    ("sell", "/sɛl/", "bán hàng hóa", "We sell products online."),
    ("shop", "/ʃɒp/", "cửa hàng bán lẻ", "Let's go to the shop."),
    ("ad", "/æd/", "mẫu quảng cáo ngắn", "I saw an ad on YouTube."),
    ("logo", "/ˈloʊ.ɡoʊ/", "biểu trưng thương hiệu", "The logo is red and white."),
    ("brand", "/brænd/", "nhãn hiệu thương hiệu", "Apple is a famous brand."),
    ("price", "/praɪs/", "giá bán sản phẩm", "The price is too high."),
    ("cost", "/kɒst/", "chi phí mua sản phẩm", "The cost is reasonable."),
    ("sale", "/seɪl/", "đợt giảm giá hàng", "The sale ends today."),
    ("free", "/friː/", "miễn phí không tốn tiền", "Get one item free."),
    ("gift", "/ɡɪft/", "quà tặng cho khách", "Every customer gets a gift."),
    ("pay", "/peɪ/", "thanh toán tiền mua", "You can pay by card."),
    ("cash", "/kæʃ/", "tiền mặt thanh toán", "The shop accepts cash only."),
    ("card", "/kɑːrd/", "thẻ ngân hàng thanh toán", "Swipe your card to pay."),
    ("deal", "/diːl/", "giao dịch thỏa thuận tốt", "This is a great deal."),
    ("save", "/seɪv/", "tiết kiệm tiền chi tiêu", "Use coupons to save money."),
    ("market", "/ˈmɑː.kɪt/", "thị trường mua bán", "Target the local market."),
    ("client", "/ˈklaɪ.ənt/", "khách hàng thân thiết", "The client is very happy."),
    ("customer", "/ˈkʌs.tə.mər/", "người mua hàng hóa", "The customer is always right."),
    ("product", "/ˈprɒd.ʌkt/", "sản phẩm hàng hóa", "Our product has a warranty."),
    ("service", "/ˈsɜːr.vɪs/", "dịch vụ đi kèm sản phẩm", "The service is excellent."),
    ("promotion", "/prəˈmoʊ.ʃən/", "chương trình khuyến mãi", "Join our special promotion."),
    ("offer", "/ˈɒf.ər/", "đề nghị ưu đãi mua hàng", "We have a limited offer."),
    ("discount", "/ˈdɪs.kaʊnt/", "giảm giá phần trăm", "Get a 20% discount today."),
    ("coupon", "/ˈkuː.pɒn/", "phiếu giảm giá", "Use a coupon at checkout."),
    ("reward", "/rɪˈwɔːrd/", "điểm thưởng tích lũy", "Earn rewards with every purchase."),
    ("label", "/ˈleɪ.bəl/", "nhãn dán sản phẩm", "Read the product label carefully."),
    ("package", "/ˈpæk.ɪdʒ/", "gói sản phẩm đóng gói", "Open the package carefully."),
    ("review", "/rɪˈvjuː/", "đánh giá sản phẩm", "Read customer reviews first."),
    ("rating", "/ˈreɪ.tɪŋ/", "xếp hạng sao sản phẩm", "The product has a 5-star rating."),
    ("store", "/stɔːr/", "cửa hàng bán lẻ", "Visit our online store."),
    ("order", "/ˈɔːr.dər/", "đặt hàng mua sản phẩm", "Place your order online."),
    ("return", "/rɪˈtɜːrn/", "trả lại hàng mua", "You can return the item."),
    ("refund", "/ˈriː.fʌnd/", "hoàn tiền cho khách", "Request a full refund."),
    ("stock", "/stɒk/", "hàng tồn kho", "The item is out of stock."),
    ("supply", "/səˈplaɪ/", "nguồn cung hàng hóa", "Supply meets demand now."),
    ("demand", "/dɪˈmænd/", "nhu cầu thị trường", "Demand for this is high."),
    ("popular", "/ˈpɒp.jʊ.lər/", "phổ biến được ưa chuộng", "This is our most popular item."),
    ("trust", "/trʌst/", "niềm tin khách hàng", "Build trust with your customers."),
    ("quality", "/ˈkwɒl.ɪ.ti/", "chất lượng sản phẩm tốt", "Quality is our top priority."),
    ("value", "/ˈvæl.juː/", "giá trị sản phẩm nhận được", "This product offers great value."),
    ("message", "/ˈmɛs.ɪdʒ/", "thông điệp truyền thông", "The brand message is clear."),
    ("audience", "/ˈɔː.di.əns/", "đối tượng khách hàng mục tiêu", "Know your target audience."),
    ("target", "/ˈtɑːr.ɡɪt/", "mục tiêu tiếp thị", "Target young adults online."),
    ("reach", "/riːtʃ/", "tiếp cận người xem quảng cáo", "Our ad reaches many people."),
    ("channel", "/ˈtʃæn.əl/", "kênh phân phối truyền thông", "Use social media as a channel."),
    ("content", "/ˈkɒn.tɛnt/", "nội dung truyền thông sáng tạo", "Create engaging content daily."),
    ("post", "/poʊst/", "bài đăng trên mạng xã hội", "Post daily for more engagement."),
    ("share", "/ʃɛər/", "chia sẻ nội dung lan truyền", "Share the post with friends."),
    ("follow", "/ˈfɒl.oʊ/", "theo dõi thương hiệu online", "Follow us for updates."),
]

MARKETING_A2 = [
    ("advertising", "/ˈæd.vər.taɪ.zɪŋ/", "hoạt động quảng cáo thương mại", "Digital advertising is cost-effective."),
    ("marketing strategy", "/ˈmɑːr.kɪ.tɪŋ ˈstræt.ɪ.dʒi/", "chiến lược tiếp thị tổng thể", "We need a new marketing strategy."),
    ("target market", "/ˈtɑːr.ɡɪt ˈmɑːr.kɪt/", "thị trường mục tiêu hướng đến", "Identify your target market first."),
    ("market research", "/ˈmɑːr.kɪt rɪˈsɜːrtʃ/", "nghiên cứu thị trường và khách hàng", "Market research guides product decisions."),
    ("survey", "/ˈsɜːr.veɪ/", "khảo sát ý kiến khách hàng", "Conduct a customer satisfaction survey."),
    ("feedback", "/ˈfiːd.bæk/", "phản hồi từ khách hàng", "Use customer feedback to improve."),
    ("satisfaction", "/ˌsæt.ɪsˈfæk.ʃən/", "sự hài lòng của khách hàng", "Customer satisfaction is our goal."),
    ("loyalty", "/ˈlɔɪ.əl.ti/", "lòng trung thành của khách hàng", "Build customer loyalty with rewards."),
    ("brand awareness", "/brænd əˈweər.nɪs/", "nhận thức về thương hiệu", "Increase brand awareness through social media."),
    ("market share", "/ˈmɑːr.kɪt ʃɛər/", "thị phần của doanh nghiệp", "Increase our market share by 10%."),
    ("competitor", "/kəmˈpɛt.ɪ.tər/", "đối thủ cạnh tranh trên thị trường", "Analyze your key competitors."),
    ("competition", "/ˌkɒm.pɪˈtɪʃ.ən/", "sự cạnh tranh trên thị trường", "Competition drives innovation."),
    ("unique selling point", "/juːˈniːk ˈsɛl.ɪŋ pɔɪnt/", "điểm bán hàng độc đáo khác biệt", "What is your unique selling point?"),
    ("positioning", "/pəˈzɪʃ.ən.ɪŋ/", "định vị thương hiệu trong tâm trí khách", "Brand positioning sets you apart."),
    ("segmentation", "/ˌsɛɡ.mɛnˈteɪ.ʃən/", "phân khúc thị trường theo nhóm", "Segmentation targets specific customer groups."),
    ("demographic", "/ˌdɛm.əˈɡræf.ɪk/", "đặc điểm nhân khẩu học nhóm khách", "Understand the demographics of your audience."),
    ("influencer", "/ˈɪn.flu.ən.sər/", "người có sức ảnh hưởng trên mạng", "Partner with an influencer for reach."),
    ("viral", "/ˈvaɪər.əl/", "lan truyền nhanh chóng trên mạng", "The video went viral overnight."),
    ("engagement", "/ɪnˈɡeɪdʒ.mənt/", "mức độ tương tác với thương hiệu", "Track engagement on social media."),
    ("impression", "/ɪmˈprɛʃ.ən/", "lượt hiển thị quảng cáo cho người xem", "The ad received one million impressions."),
    ("click-through rate", "/klɪk θruː reɪt/", "tỷ lệ nhấp chuột vào quảng cáo", "Improve the click-through rate."),
    ("conversion", "/kənˈvɜːr.ʒən/", "chuyển đổi khách tiềm năng thành mua hàng", "Measure the conversion rate."),
    ("lead", "/liːd/", "khách hàng tiềm năng chưa mua", "Generate more sales leads."),
    ("funnel", "/ˈfʌn.əl/", "phễu bán hàng từ nhận biết đến mua", "The sales funnel needs optimization."),
    ("call to action", "/kɔːl tuː ˈæk.ʃən/", "lời kêu gọi hành động mua ngay", "Add a clear call to action."),
    ("landing page", "/ˈlæn.dɪŋ peɪdʒ/", "trang đích nhận lưu lượng quảng cáo", "Optimize the landing page for conversions."),
    ("email marketing", "/ˈiː.meɪl ˈmɑːr.kɪ.tɪŋ/", "tiếp thị qua thư điện tử", "Email marketing has a high ROI."),
    ("newsletter", "/ˈnjuːz.lɛt.ər/", "bản tin định kỳ cho khách đăng ký", "Send a monthly newsletter."),
    ("sponsorship", "/ˈspɒn.sər.ʃɪp/", "tài trợ sự kiện hoặc nội dung", "Get a sponsorship from a big brand."),
    ("affiliate", "/əˈfɪl.i.ɪt/", "đối tác liên kết kiếm hoa hồng", "Join our affiliate program."),
    ("commission", "/kəˈmɪʃ.ən/", "hoa hồng cho đối tác bán hàng", "Affiliates earn a 10% commission."),
    ("testimonial", "/ˌtɛs.tɪˈmoʊ.ni.əl/", "lời chứng thực từ khách hàng cũ", "Use testimonials to build trust."),
    ("case study", "/keɪs ˈstʌd.i/", "nghiên cứu tình huống thành công", "Share a case study with prospects."),
    ("press release", "/prɛs rɪˈliːs/", "thông cáo báo chí chính thức", "Issue a press release for the launch."),
    ("trade show", "/treɪd ʃoʊ/", "hội chợ thương mại ngành nghề", "Exhibit at the annual trade show."),
    ("event marketing", "/ɪˈvɛnt ˈmɑːr.kɪ.tɪŋ/", "tiếp thị thông qua tổ chức sự kiện", "Event marketing creates brand experiences."),
    ("direct mail", "/daɪˈrɛkt meɪl/", "gửi thư trực tiếp đến khách hàng", "Direct mail still works for some audiences."),
    ("print ad", "/prɪnt æd/", "quảng cáo in ấn trên báo chí", "Place a print ad in the newspaper."),
    ("billboard", "/ˈbɪl.bɔːrd/", "biển quảng cáo ngoài trời lớn", "Put a billboard near the highway."),
    ("word of mouth", "/wɜːrd əv maʊθ/", "truyền miệng từ khách hàng hài lòng", "Word of mouth is the best marketing."),
    ("referral", "/rɪˈfɜːr.əl/", "giới thiệu khách hàng mới từ cũ", "Referrals bring high-quality leads."),
    ("brand identity", "/brænd aɪˈdɛn.tɪ.ti/", "bản sắc thương hiệu tổng thể", "Build a strong brand identity."),
    ("tagline", "/ˈtæɡ.laɪn/", "khẩu hiệu thương hiệu ngắn gọn", "Create a memorable tagline."),
    ("slogan", "/ˈsloʊ.ɡən/", "khẩu hiệu quảng cáo ghi nhớ", "Nike's slogan is Just Do It."),
    ("copywriting", "/ˈkɒp.i.raɪ.tɪŋ/", "viết nội dung thuyết phục để bán hàng", "Good copywriting drives sales."),
    ("headline", "/ˈhɛd.laɪn/", "tiêu đề thu hút chú ý quảng cáo", "Write a compelling headline."),
    ("color scheme", "/ˈkʌl.ər skiːm/", "bảng màu thương hiệu nhất quán", "Choose a consistent color scheme."),
    ("mascot", "/ˈmæs.kɒt/", "linh vật đại diện thương hiệu", "The mascot makes the brand memorable."),
    ("jingle", "/ˈdʒɪŋ.ɡəl/", "điệu nhạc quảng cáo dễ nhớ", "The jingle gets stuck in your head."),
    ("packaging design", "/ˈpæk.ɪ.dʒɪŋ dɪˈzaɪn/", "thiết kế bao bì thu hút mắt khách", "Packaging design influences buying decisions."),
]

MARKETING_B1 = [
    ("brand equity", "/brænd ˈɛk.wɪ.ti/", "giá trị thương hiệu xây dựng theo thời gian", "Apple has enormous brand equity."),
    ("content marketing", "/ˈkɒn.tɛnt ˈmɑːr.kɪ.tɪŋ/", "tiếp thị nội dung hữu ích thu hút", "Content marketing builds long-term trust."),
    ("SEO", "/ˌɛs.iːˈoʊ/", "tối ưu hóa công cụ tìm kiếm", "Good SEO increases organic traffic."),
    ("SEM", "/ˌɛs.iːˈɛm/", "tiếp thị trên công cụ tìm kiếm trả tiền", "SEM includes paid search advertising."),
    ("PPC", "/ˌpiː.piːˈsiː/", "trả tiền mỗi lần nhấp chuột quảng cáo", "PPC campaigns drive immediate traffic."),
    ("ROI", "/ˌɑːr.oʊˈaɪ/", "tỷ suất hoàn vốn đầu tư marketing", "Calculate the ROI of each campaign."),
    ("KPI", "/ˌkeɪ.piːˈaɪ/", "chỉ số hiệu suất chính cần theo dõi", "Set clear KPIs for each campaign."),
    ("attribution", "/ˌæt.rɪˈbjuː.ʃən/", "quy kết nguồn gốc chuyển đổi khách hàng", "Attribution shows which channel converts."),
    ("omnichannel", "/ˌɒm.niˈtʃæn.əl/", "tiếp thị đa kênh liền mạch", "An omnichannel approach ensures consistency."),
    ("retargeting", "/riːˈtɑːr.ɡɪ.tɪŋ/", "tiếp thị lại khách đã tương tác trước", "Retargeting converts hesitant buyers."),
    ("lookalike audience", "/ˈlʊk.ə.laɪk ˈɔː.di.əns/", "đối tượng tương tự khách hàng hiện có", "Use lookalike audiences for paid ads."),
    ("A/B testing", "/ˌeɪ.biː ˈtɛs.tɪŋ/", "thử nghiệm so sánh hai phiên bản", "Run A/B tests on your landing pages."),
    ("persona", "/pərˈsoʊ.nə/", "chân dung khách hàng mục tiêu", "Create a buyer persona for each segment."),
    ("customer journey", "/ˈkʌs.tə.mər ˈdʒɜːr.ni/", "hành trình trải nghiệm của khách hàng", "Map the customer journey from awareness to purchase."),
    ("touchpoint", "/ˈtʌtʃ.pɔɪnt/", "điểm tiếp xúc giữa thương hiệu và khách", "Every touchpoint shapes brand perception."),
    ("churn rate", "/tʃɜːrn reɪt/", "tỷ lệ khách hàng ngừng sử dụng dịch vụ", "High churn rate hurts revenue."),
    ("customer lifetime value", "/ˈkʌs.tə.mər ˈlaɪf.taɪm ˈvæl.juː/", "giá trị vòng đời của một khách hàng", "CLV determines how much to spend on acquisition."),
    ("cost per acquisition", "/kɒst pɜːr ˌæk.wɪˈzɪʃ.ən/", "chi phí để có một khách hàng mới", "Reduce cost per acquisition with better targeting."),
    ("brand ambassador", "/brænd æmˈbæs.ə.dər/", "đại sứ thương hiệu đại diện truyền thông", "The celebrity became our brand ambassador."),
    ("user-generated content", "/ˈjuː.zər ˈdʒɛn.ər.eɪ.tɪd ˈkɒn.tɛnt/", "nội dung do người dùng tự tạo", "User-generated content builds authenticity."),
    ("organic reach", "/ɔːrˈɡæn.ɪk riːtʃ/", "tiếp cận tự nhiên không trả tiền", "Organic reach is declining on Facebook."),
    ("paid reach", "/peɪd riːtʃ/", "tiếp cận trả tiền qua quảng cáo", "Paid reach can target specific audiences."),
    ("social proof", "/ˈsoʊ.ʃəl pruːf/", "bằng chứng xã hội tin tưởng thương hiệu", "Social proof increases purchase confidence."),
    ("growth hacking", "/ɡroʊθ ˈhæk.ɪŋ/", "tăng trưởng nhanh qua thử nghiệm sáng tạo", "Growth hacking tests unconventional tactics."),
    ("product launch", "/ˈprɒd.ʌkt lɔːntʃ/", "ra mắt sản phẩm mới ra thị trường", "Plan a successful product launch event."),
    ("go-to-market strategy", "/ˌɡoʊ.tʊˈmɑːr.kɪt ˈstræt.ɪ.dʒi/", "chiến lược đưa sản phẩm ra thị trường", "Define your go-to-market strategy."),
    ("pricing strategy", "/ˈpraɪ.sɪŋ ˈstræt.ɪ.dʒi/", "chiến lược định giá sản phẩm", "A freemium pricing strategy attracts users."),
    ("distribution channel", "/ˌdɪs.trɪˈbjuː.ʃən ˈtʃæn.əl/", "kênh phân phối sản phẩm đến tay khách", "Choose the right distribution channel."),
    ("market penetration", "/ˈmɑːr.kɪt ˌpɛn.ɪˈtreɪ.ʃən/", "thâm nhập thị trường mới hiệu quả", "Market penetration requires competitive pricing."),
    ("cross-selling", "/ˈkrɒs ˌsɛl.ɪŋ/", "bán chéo sản phẩm bổ sung cho nhau", "Cross-selling increases order value."),
    ("upselling", "/ˈʌp.sɛl.ɪŋ/", "nâng cấp lên sản phẩm cao cấp hơn", "Upselling moves customers to premium tiers."),
    ("freemium", "/ˈfriː.mi.əm/", "mô hình miễn phí cơ bản tính phí cao cấp", "Spotify uses a freemium business model."),
    ("subscription model", "/səbˈskrɪp.ʃən ˈmɒd.əl/", "mô hình kinh doanh thu phí theo kỳ", "The subscription model ensures recurring revenue."),
    ("pay-per-click", "/peɪ pɜːr klɪk/", "trả tiền theo số lần nhấp quảng cáo", "Pay-per-click ads appear in search results."),
]

MARKETING_B2 = [
    ("integrated marketing communications", "/ˈɪn.tɪ.ɡreɪ.tɪd ˈmɑːr.kɪ.tɪŋ kəˌmjuː.nɪˈkeɪ.ʃənz/", "truyền thông tiếp thị tích hợp đồng nhất", "IMC ensures a consistent brand message."),
    ("programmatic advertising", "/ˌproʊ.ɡrəˈmæt.ɪk ˈæd.vər.taɪ.zɪŋ/", "quảng cáo tự động hóa theo thuật toán", "Programmatic advertising automates ad buying."),
    ("demand-side platform", "/dɪˈmænd saɪd ˈplæt.fɔːrm/", "nền tảng phía cầu quản lý quảng cáo tự động", "A DSP manages programmatic ad buying."),
    ("supply-side platform", "/səˈplaɪ saɪd ˈplæt.fɔːrm/", "nền tảng phía cung bán không gian quảng cáo", "Publishers use an SSP to sell ad space."),
    ("data-driven marketing", "/ˈdeɪ.tə ˈdrɪv.ən ˈmɑːr.kɪ.tɪŋ/", "tiếp thị dựa trên phân tích dữ liệu", "Data-driven marketing improves targeting."),
    ("predictive analytics", "/prɪˈdɪk.tɪv ˌæn.əˈlɪt.ɪks/", "phân tích dự đoán hành vi khách hàng", "Predictive analytics forecasts customer behavior."),
    ("customer data platform", "/ˈkʌs.tə.mər ˈdeɪ.tə ˈplæt.fɔːrm/", "nền tảng dữ liệu khách hàng tập trung", "A CDP unifies all customer data sources."),
    ("CRM", "/ˌsiː.ɑːrˈɛm/", "quản lý quan hệ khách hàng", "Use CRM to track customer interactions."),
    ("marketing automation", "/ˈmɑːr.kɪ.tɪŋ ˌɔː.tə.ˈmeɪ.ʃən/", "tự động hóa quy trình tiếp thị", "Marketing automation nurtures leads."),
    ("lead nurturing", "/liːd ˈnɜːr.tʃər.ɪŋ/", "chăm sóc khách tiềm năng theo thời gian", "Lead nurturing moves prospects to purchase."),
    ("behavioral targeting", "/bɪˈheɪ.vjər.əl ˈtɑːr.ɡɪ.tɪŋ/", "nhắm mục tiêu theo hành vi người dùng", "Behavioral targeting serves relevant ads."),
    ("psychographic", "/ˌsaɪ.kəˈɡræf.ɪk/", "phân khúc theo tâm lý và lối sống", "Psychographic segmentation targets values."),
    ("net promoter score", "/nɛt prəˈmoʊ.tər skɔːr/", "điểm số khuyến nghị thương hiệu từ khách", "Track NPS to measure customer loyalty."),
    ("brand perception", "/brænd pərˈsɛp.ʃən/", "nhận thức của công chúng về thương hiệu", "Monitor brand perception regularly."),
    ("sentiment monitoring", "/ˈsɛn.tɪ.mənt ˈmɒn.ɪ.tər.ɪŋ/", "theo dõi cảm xúc công chúng về thương hiệu", "Sentiment monitoring alerts you to crises."),
    ("share of voice", "/ʃɛər əv vɔɪs/", "thị phần tiếng nói trong ngành so với đối thủ", "Increase share of voice in the market."),
    ("media mix modeling", "/ˈmiː.di.ə mɪks ˈmɒd.əl.ɪŋ/", "mô hình hóa tổ hợp kênh truyền thông", "Media mix modeling optimizes budget."),
    ("multivariate testing", "/ˌmʌl.tɪˈvɛər.i.ɪt ˈtɛs.tɪŋ/", "thử nghiệm đa biến tối ưu hóa trang", "Multivariate testing tests multiple elements."),
    ("cohort analysis", "/ˈkoʊ.hɔːrt əˈnæl.ɪ.sɪs/", "phân tích nhóm người dùng theo thời gian", "Cohort analysis tracks user retention."),
    ("attribution modeling", "/ˌæt.rɪˈbjuː.ʃən ˈmɒd.əl.ɪŋ/", "mô hình hóa quy kết giá trị chuyển đổi", "Attribution modeling credits the right channels."),
    ("inbound marketing", "/ˈɪn.baʊnd ˈmɑːr.kɪ.tɪŋ/", "tiếp thị thu hút khách tự nhiên vào", "Inbound marketing draws customers in."),
    ("outbound marketing", "/ˈaʊt.baʊnd ˈmɑːr.kɪ.tɪŋ/", "tiếp thị chủ động tiếp cận khách hàng", "Outbound marketing includes cold calling."),
    ("account-based marketing", "/əˈkaʊnt beɪst ˈmɑːr.kɪ.tɪŋ/", "tiếp thị tập trung vào khách hàng lớn", "ABM targets high-value accounts directly."),
    ("competitive intelligence", "/kəmˈpɛt.ɪ.tɪv ɪnˈtɛl.ɪ.dʒəns/", "tình báo cạnh tranh phân tích đối thủ", "Gather competitive intelligence regularly."),
    ("SWOT analysis", "/swɒt əˈnæl.ɪ.sɪs/", "phân tích điểm mạnh yếu cơ hội thách thức", "Conduct a SWOT analysis before planning."),
    ("brand extension", "/brænd ɪkˈstɛn.ʃən/", "mở rộng thương hiệu sang danh mục mới", "Brand extension leverages existing equity."),
    ("co-marketing", "/ˌkoʊˈmɑːr.kɪ.tɪŋ/", "hợp tác tiếp thị cùng thương hiệu khác", "Co-marketing expands audience reach."),
    ("guerrilla marketing", "/ɡəˈrɪl.ə ˈmɑːr.kɪ.tɪŋ/", "tiếp thị du kích bất ngờ tạo sự chú ý", "Guerrilla marketing creates viral moments."),
    ("cause marketing", "/kɔːz ˈmɑːr.kɪ.tɪŋ/", "tiếp thị gắn liền với mục tiêu xã hội", "Cause marketing aligns brands with values."),
    ("neuromarketing", "/ˌnjʊər.oʊˈmɑːr.kɪ.tɪŋ/", "tiếp thị dựa trên khoa học thần kinh", "Neuromarketing uses brain science in ads."),
    ("price elasticity", "/praɪs ˌɪ.læsˈtɪs.ɪ.ti/", "độ co giãn giá cầu của sản phẩm", "Understand price elasticity before discounting."),
    ("product-market fit", "/ˈprɒd.ʌkt ˈmɑːr.kɪt fɪt/", "sự phù hợp giữa sản phẩm và thị trường", "Achieve product-market fit before scaling."),
    ("minimum viable product", "/ˈmɪn.ɪ.məm ˈvaɪ.ə.bəl ˈprɒd.ʌkt/", "sản phẩm khả dụng tối thiểu để test", "Launch an MVP before full development."),
    ("pivot", "/ˈpɪv.ɪt/", "thay đổi hướng chiến lược kinh doanh", "The startup pivoted to a new market."),
]

MARKETING_C1 = [
    ("brand architecture", "/brænd ˈɑːr.kɪ.tɛk.tʃər/", "kiến trúc danh mục thương hiệu tổng thể", "Brand architecture organizes a portfolio of brands."),
    ("positioning strategy", "/pəˈzɪʃ.ən.ɪŋ ˈstræt.ɪ.dʒi/", "chiến lược định vị thương hiệu cạnh tranh", "A clear positioning strategy differentiates the brand."),
    ("competitive moat", "/kəmˈpɛt.ɪ.tɪv moʊt/", "hào cạnh tranh bảo vệ lợi thế bền vững", "A strong brand is a competitive moat."),
    ("market saturation", "/ˈmɑːr.kɪt ˌsætʃ.ʊˈreɪ.ʃən/", "thị trường bão hòa khó tăng trưởng thêm", "Market saturation forces innovation."),
    ("blue ocean strategy", "/bluː ˈoʊ.ʃən ˈstræt.ɪ.dʒi/", "chiến lược đại dương xanh tạo thị trường mới", "Blue ocean strategy creates uncontested markets."),
    ("disruptive marketing", "/dɪsˈrʌp.tɪv ˈmɑːr.kɪ.tɪŋ/", "tiếp thị đột phá thay đổi quy tắc ngành", "Disruptive marketing challenges the status quo."),
    ("hyper-personalization", "/ˌhaɪ.pər.ˌpɜːr.sən.ə.laɪˈzeɪ.ʃən/", "cá nhân hóa siêu chi tiết theo từng người", "Hyper-personalization uses AI for individual targeting."),
    ("attention economy", "/əˈtɛn.ʃən ɪˈkɒn.ə.mi/", "kinh tế chú ý cạnh tranh thời gian người dùng", "Marketers compete in the attention economy."),
    ("dark social", "/dɑːrk ˈsoʊ.ʃəl/", "chia sẻ riêng tư không theo dõi được", "Dark social includes WhatsApp shares."),
    ("first-party data", "/fɜːrst ˈpɑːr.ti ˈdeɪ.tə/", "dữ liệu bên thứ nhất từ khách hàng trực tiếp", "First-party data is more valuable after cookies end."),
    ("zero-party data", "/ˈzɪər.oʊ ˈpɑːr.ti ˈdeɪ.tə/", "dữ liệu chủ động chia sẻ bởi khách hàng", "Zero-party data comes from preference centers."),
    ("cookieless future", "/ˈkʊk.i.lɪs ˈfjuː.tʃər/", "tương lai tiếp thị không dùng cookie", "Prepare for a cookieless future now."),
    ("intent data", "/ɪnˈtɛnt ˈdeɪ.tə/", "dữ liệu ý định mua hàng sắp tới", "Intent data identifies in-market buyers."),
    ("privacy-first marketing", "/ˈprɪv.ə.si fɜːrst ˈmɑːr.kɪ.tɪŋ/", "tiếp thị ưu tiên bảo vệ quyền riêng tư", "Privacy-first marketing builds trust."),
    ("contextual advertising", "/kənˈtɛks.tʃʊ.əl ˈæd.vər.taɪ.zɪŋ/", "quảng cáo theo bối cảnh nội dung trang", "Contextual advertising replaces behavioral tracking."),
    ("emotional branding", "/ɪˈmoʊ.ʃən.əl ˈbrænd.ɪŋ/", "xây dựng thương hiệu kết nối cảm xúc", "Emotional branding creates deep loyalty."),
    ("brand storytelling", "/brænd ˈstɔːr.i.tɛl.ɪŋ/", "kể chuyện thương hiệu hấp dẫn nhân văn", "Brand storytelling connects on a human level."),
    ("transmedia marketing", "/trænsˈmiː.di.ə ˈmɑːr.kɪ.tɪŋ/", "tiếp thị đa phương tiện kể chuyện liên kết", "Transmedia marketing spans multiple platforms."),
    ("social commerce", "/ˈsoʊ.ʃəl ˈkɒm.ɜːrs/", "thương mại xã hội mua bán qua mạng xã hội", "Social commerce enables buying on Instagram."),
    ("conversational marketing", "/ˌkɒn.vəˈseɪ.ʃən.əl ˈmɑːr.kɪ.tɪŋ/", "tiếp thị đối thoại tương tác thời gian thực", "Conversational marketing uses chatbots for engagement."),
    ("purpose-driven brand", "/ˈpɜːr.pəs ˈdrɪv.ən brænd/", "thương hiệu có mục đích sứ mệnh xã hội", "A purpose-driven brand attracts loyal customers."),
    ("brand activism", "/brænd ˈæk.tɪ.vɪzm/", "thương hiệu dũng cảm lên tiếng vấn đề xã hội", "Brand activism requires authenticity."),
    ("creator economy", "/kriːˈeɪ.tər ɪˈkɒn.ə.mi/", "nền kinh tế người sáng tạo nội dung số", "The creator economy transforms influencer marketing."),
    ("performance marketing", "/pərˈfɔːr.məns ˈmɑːr.kɪ.tɪŋ/", "tiếp thị dựa trên kết quả đo lường được", "Performance marketing pays for results only."),
    ("growth marketing", "/ɡroʊθ ˈmɑːr.kɪ.tɪŋ/", "tiếp thị tăng trưởng tập trung số liệu", "Growth marketing optimizes the full funnel."),
    ("ecosystem marketing", "/ˈiː.kəʊ.sɪs.təm ˈmɑːr.kɪ.tɪŋ/", "tiếp thị hệ sinh thái đối tác liên kết", "Ecosystem marketing leverages partner networks."),
    ("community-led growth", "/kəˈmjuː.nɪ.ti lɛd ɡroʊθ/", "tăng trưởng dẫn dắt bởi cộng đồng người dùng", "Community-led growth turns users into advocates."),
    ("product-led growth", "/ˈprɒd.ʌkt lɛd ɡroʊθ/", "tăng trưởng dẫn dắt bởi chính sản phẩm", "Slack achieved product-led growth."),
    ("voice search optimization", "/vɔɪs sɜːrtʃ ˌɒp.tɪ.maɪˈzeɪ.ʃən/", "tối ưu hóa tìm kiếm bằng giọng nói", "Optimize for voice search as AI assistants grow."),
    ("augmented reality marketing", "/ˌɔːɡ.mɛn.tɪd rɪˈæl.ɪ.ti ˈmɑːr.kɪ.tɪŋ/", "tiếp thị qua công nghệ thực tế tăng cường", "AR marketing lets customers try products virtually."),
    ("metaverse marketing", "/ˈmɛt.ə.vɜːrs ˈmɑːr.kɪ.tɪŋ/", "tiếp thị trong thế giới ảo metaverse", "Brands experiment with metaverse marketing."),
    ("dynamic creative optimization", "/daɪˈnæm.ɪk kriːˈeɪ.tɪv ˌɒp.tɪ.maɪˈzeɪ.ʃən/", "tối ưu hóa sáng tạo quảng cáo tự động", "DCO personalizes ads at scale."),
    ("walled garden", "/wɔːld ˈɡɑːr.dən/", "hệ sinh thái đóng kiểm soát dữ liệu", "Google and Meta are walled gardens."),
    ("incrementality testing", "/ˌɪŋ.krɪˈmɛnt.əl.ɪ.ti ˈtɛs.tɪŋ/", "kiểm tra tác động gia tăng thực sự của quảng cáo", "Incrementality testing measures true ad impact."),
    ("unified measurement", "/ˈjuː.nɪ.faɪd ˈmɛʒ.ər.mənt/", "đo lường thống nhất hiệu quả đa kênh", "Unified measurement solves multi-touch attribution."),
]

# ===== JOB =====
# Đã có A1: boss, break, cash, gathering, job... | B1: career, connecting, expertise, freelancer...

JOB_A1 = [
    ("work", "/wɜːrk/", "công việc hàng ngày", "I go to work every morning."),
    ("office", "/ˈɒf.ɪs/", "văn phòng làm việc", "My office is on the fifth floor."),
    ("meeting", "/ˈmiː.tɪŋ/", "cuộc họp nhóm", "We have a meeting at ten."),
    ("team", "/tiːm/", "nhóm làm việc", "I work in a small team."),
    ("manager", "/ˈmæn.ɪ.dʒər/", "quản lý cấp trên", "My manager is very kind."),
    ("colleague", "/ˈkɒl.iːɡ/", "đồng nghiệp cùng công ty", "My colleague helped me today."),
    ("salary", "/ˈsæl.ər.i/", "mức lương hàng tháng", "My salary is paid monthly."),
    ("interview", "/ˈɪn.tə.vjuː/", "buổi phỏng vấn xin việc", "I have a job interview tomorrow."),
    ("resume", "/ˈrɛz.jʊ.meɪ/", "hồ sơ xin việc", "Send your resume by email."),
    ("hire", "/ˈhaɪər/", "tuyển dụng nhân viên", "The company will hire ten people."),
    ("apply", "/əˈplaɪ/", "nộp đơn xin việc", "Apply for the job online."),
    ("task", "/tæsk/", "nhiệm vụ công việc", "Finish your task by noon."),
    ("report", "/rɪˈpɔːrt/", "báo cáo công việc", "Write a report for the boss."),
    ("project", "/ˈprɒdʒ.ɛkt/", "dự án đang thực hiện", "Our project ends next week."),
    ("email", "/ˈiː.meɪl/", "email công việc", "Send an email to the team."),
    ("phone", "/foʊn/", "điện thoại liên lạc", "Answer the phone quickly."),
    ("deadline", "/ˈdɛd.laɪn/", "hạn chót hoàn thành", "The deadline is Friday."),
    ("schedule", "/ˈʃɛd.juːl/", "lịch làm việc", "Check your schedule today."),
    ("skills", "/skɪlz/", "kỹ năng chuyên môn", "Learn new skills every year."),
    ("experience", "/ɪkˈspɪər.i.əns/", "kinh nghiệm làm việc", "I have five years of experience."),
    ("company", "/ˈkʌm.pə.ni/", "công ty đang làm việc", "I work for a tech company."),
    ("department", "/dɪˈpɑːrt.mənt/", "phòng ban trong công ty", "She works in the marketing department."),
    ("position", "/pəˈzɪʃ.ən/", "chức vụ công việc", "What is your current position?"),
    ("promotion", "/prəˈmoʊ.ʃən/", "thăng chức tăng cấp", "He got a promotion last month."),
    ("training", "/ˈtreɪ.nɪŋ/", "đào tạo nhân viên mới", "New staff get two weeks of training."),
    ("full-time", "/ˌfʊlˈtaɪm/", "toàn thời gian làm việc", "I work full-time at the bank."),
    ("part-time", "/ˌpɑːrtˈtaɪm/", "bán thời gian làm việc", "She works part-time at a cafe."),
    ("contract", "/ˈkɒn.trækt/", "hợp đồng lao động", "Sign the contract before starting."),
    ("benefits", "/ˈbɛn.ɪ.fɪts/", "phúc lợi lao động", "The job has great benefits."),
    ("vacation", "/veɪˈkeɪ.ʃən/", "kỳ nghỉ phép năm", "I have two weeks of vacation."),
    ("sick leave", "/sɪk liːv/", "nghỉ ốm có phép", "You can take sick leave when ill."),
    ("overtime", "/ˈoʊ.vər.taɪm/", "làm thêm giờ ngoài giờ hành chính", "I worked overtime this week."),
    ("shift", "/ʃɪft/", "ca làm việc", "I work the morning shift."),
    ("remote", "/rɪˈmoʊt/", "làm việc từ xa", "I work remote from home."),
    ("online", "/ˌɒnˈlaɪn/", "trực tuyến trên mạng", "We meet online every Monday."),
]

JOB_A2 = [
    ("profession", "/prəˈfɛʃ.ən/", "nghề nghiệp chuyên môn", "Teaching is a noble profession."),
    ("occupation", "/ˌɒk.jʊˈpeɪ.ʃən/", "nghề nghiệp đang làm", "Please state your occupation."),
    ("employer", "/ɪmˈplɔɪ.ər/", "chủ sử dụng lao động", "Your employer must sign the form."),
    ("employee", "/ˌɪm.plɔɪˈiː/", "nhân viên lao động", "Every employee gets health insurance."),
    ("workforce", "/ˈwɜːrk.fɔːrs/", "lực lượng lao động", "The company has a large workforce."),
    ("recruitment", "/rɪˈkruːt.mənt/", "tuyển dụng nhân sự mới", "Recruitment starts next month."),
    ("job description", "/dʒɒb dɪˈskrɪp.ʃən/", "mô tả công việc cụ thể", "Read the job description carefully."),
    ("cover letter", "/ˈkʌv.ər ˈlɛt.ər/", "thư xin việc giới thiệu bản thân", "Write a strong cover letter."),
    ("reference", "/ˈrɛf.ər.əns/", "thư giới thiệu từ người quen", "Provide two professional references."),
    ("probation", "/prəˈbeɪ.ʃən/", "thời gian thử việc", "The probation period is three months."),
    ("resignation", "/ˌrɛz.ɪɡˈneɪ.ʃən/", "đơn xin nghỉ việc", "Submit your resignation letter."),
    ("layoff", "/ˈleɪ.ɒf/", "sa thải do cắt giảm nhân sự", "Many workers faced layoffs."),
    ("redundancy", "/rɪˈdʌn.dən.si/", "dư thừa nhân sự bị cắt giảm", "She received redundancy pay."),
    ("retirement", "/rɪˈtaɪər.mənt/", "về hưu sau tuổi làm việc", "He plans retirement at 65."),
    ("pension", "/ˈpɛn.ʃən/", "lương hưu sau nghỉ việc", "Save for a pension early."),
    ("bonus", "/ˈboʊ.nəs/", "thưởng cuối năm", "We received a year-end bonus."),
    ("raise", "/reɪz/", "tăng lương theo hiệu suất", "She asked for a raise."),
    ("paycheck", "/ˈpeɪ.tʃɛk/", "phiếu lương hàng tháng", "The paycheck arrives on Friday."),
    ("wage", "/weɪdʒ/", "tiền công theo giờ", "The minimum wage increased."),
    ("tax", "/tæks/", "thuế thu nhập cá nhân", "Pay income tax every year."),
    ("career path", "/kəˈrɪər pæθ/", "con đường sự nghiệp", "Plan your career path carefully."),
    ("performance review", "/pərˈfɔːr.məns rɪˈvjuː/", "đánh giá hiệu suất công việc", "Annual performance reviews set goals."),
    ("goal setting", "/ɡoʊl ˈsɛt.ɪŋ/", "thiết lập mục tiêu công việc", "Goal setting improves motivation."),
    ("feedback", "/ˈfiːd.bæk/", "phản hồi cải thiện công việc", "Ask for feedback to improve."),
    ("mentorship", "/ˈmɛn.tər.ʃɪp/", "hướng dẫn từ người có kinh nghiệm", "A mentorship program helps newcomers."),
    ("internship", "/ˈɪn.tɜːrn.ʃɪp/", "thực tập tại công ty", "She did an internship at a bank."),
    ("volunteer", "/ˌvɒl.ənˈtɪər/", "tình nguyện viên không lương", "Volunteer work builds experience."),
    ("self-employed", "/ˌsɛlf.ɪmˈplɔɪd/", "tự kinh doanh làm chủ", "He became self-employed last year."),
    ("consultant", "/kənˈsʌl.tənt/", "chuyên gia tư vấn độc lập", "Hire a consultant for advice."),
    ("remote work", "/rɪˈmoʊt wɜːrk/", "làm việc từ xa tại nhà", "Remote work became common recently."),
    ("hybrid work", "/ˈhaɪ.brɪd wɜːrk/", "làm việc kết hợp văn phòng và nhà", "Hybrid work offers flexibility."),
    ("workplace", "/ˈwɜːrk.pleɪs/", "môi trường nơi làm việc", "The workplace should be safe."),
    ("commute", "/kəˈmjuːt/", "đi lại đến nơi làm việc", "The daily commute takes one hour."),
    ("corporate", "/ˈkɔːr.pər.ɪt/", "thuộc về doanh nghiệp lớn", "She works in the corporate sector."),
    ("startup", "/ˈstɑːr.tʌp/", "công ty khởi nghiệp mới", "He joined a startup after college."),
    ("networking", "/ˈnɛt.wɜːr.kɪŋ/", "xây dựng mối quan hệ nghề nghiệp", "Networking opens career doors."),
    ("professional development", "/prəˈfɛʃ.ən.əl dɪˈvɛl.əp.mənt/", "phát triển năng lực chuyên nghiệp", "Invest in professional development."),
    ("soft skills", "/sɒft skɪlz/", "kỹ năng mềm giao tiếp ứng xử", "Soft skills are valued highly."),
    ("hard skills", "/hɑːrd skɪlz/", "kỹ năng cứng chuyên môn cụ thể", "Hard skills include coding and data."),
    ("teamwork", "/ˈtiːm.wɜːrk/", "làm việc nhóm phối hợp nhau", "Teamwork achieves better results."),
    ("leadership", "/ˈliː.dər.ʃɪp/", "kỹ năng lãnh đạo nhóm", "Leadership motivates the whole team."),
    ("time management", "/taɪm ˈmæn.ɪdʒ.mənt/", "quản lý thời gian hiệu quả", "Time management reduces stress."),
    ("problem solving", "/ˈprɒb.ləm ˌsɒlv.ɪŋ/", "giải quyết vấn đề sáng tạo", "Problem solving is a key skill."),
    ("communication", "/kəˌmjuː.nɪˈkeɪ.ʃən/", "kỹ năng giao tiếp hiệu quả", "Good communication is essential."),
    ("critical thinking", "/ˈkrɪt.ɪ.kəl ˈθɪŋ.kɪŋ/", "tư duy phản biện logic", "Critical thinking improves decisions."),
    ("adaptability", "/əˌdæp.təˈbɪl.ɪ.ti/", "khả năng thích nghi linh hoạt", "Adaptability is key in tech jobs."),
    ("initiative", "/ɪˈnɪʃ.ə.tɪv/", "chủ động tiên phong hành động", "Show initiative to stand out."),
    ("creativity", "/ˌkriː.eɪˈtɪv.ɪ.ti/", "sáng tạo giải pháp mới mẻ", "Creativity drives innovation."),
    ("attention to detail", "/əˈtɛn.ʃən tʊ ˈdiː.teɪl/", "chú ý đến từng chi tiết nhỏ", "Attention to detail prevents errors."),
    ("multitasking", "/ˈmʌl.ti.tɑːs.kɪŋ/", "xử lý nhiều việc cùng lúc", "Multitasking is needed in busy roles."),
]

JOB_B2 = [
    ("competency framework", "/kəmˈpɛt.ən.si ˈfreɪm.wɜːrk/", "khung năng lực đánh giá nhân sự", "The competency framework guides hiring."),
    ("succession planning", "/səkˈsɛʃ.ən ˈplæn.ɪŋ/", "lập kế hoạch kế thừa nhân sự", "Succession planning prepares future leaders."),
    ("talent acquisition", "/ˈtæl.ənt ˌæk.wɪˈzɪʃ.ən/", "thu hút và tuyển dụng nhân tài", "Talent acquisition is strategic."),
    ("employer branding", "/ɪmˈplɔɪ.ər ˈbrænd.ɪŋ/", "xây dựng thương hiệu nhà tuyển dụng", "Employer branding attracts top talent."),
    ("employee value proposition", "/ɪmˈplɔɪ.iː ˈvæl.juː ˌprɒp.əˈzɪʃ.ən/", "đề xuất giá trị cho nhân viên", "The EVP makes the company attractive."),
    ("organizational culture", "/ˌɔːr.ɡən.aɪˈzeɪ.ʃən.əl ˈkʌl.tʃər/", "văn hóa tổ chức doanh nghiệp", "Culture drives employee engagement."),
    ("diversity and inclusion", "/daɪˈvɜːr.sɪ.ti ænd ɪnˈkluː.ʒən/", "đa dạng và hòa nhập trong tổ chức", "D&I programs improve team performance."),
    ("equity", "/ˈɛk.wɪ.ti/", "công bằng trong đãi ngộ và cơ hội", "Equity ensures fair treatment."),
    ("psychological safety", "/ˌsaɪ.kəˈlɒdʒ.ɪ.kəl ˈseɪf.ti/", "an toàn tâm lý để nói thẳng", "Psychological safety boosts innovation."),
    ("intrinsic motivation", "/ɪnˈtrɪn.sɪk ˌmoʊ.tɪˈveɪ.ʃən/", "động lực nội tại từ bên trong", "Intrinsic motivation drives sustained performance."),
    ("extrinsic motivation", "/ɛkˈstrɪn.sɪk ˌmoʊ.tɪˈveɪ.ʃən/", "động lực ngoại tại từ phần thưởng bên ngoài", "Bonuses are a form of extrinsic motivation."),
    ("talent management", "/ˈtæl.ənt ˈmæn.ɪdʒ.mənt/", "quản lý nhân tài trong tổ chức", "Talent management retains top performers."),
    ("performance management", "/pərˈfɔːr.məns ˈmæn.ɪdʒ.mənt/", "quản lý hiệu suất nhân viên hệ thống", "Performance management aligns goals."),
    ("OKR", "/ˌoʊ.keɪˈɑːr/", "mục tiêu và kết quả then chốt", "OKRs align team and company goals."),
    ("360-degree feedback", "/ˌθriː.sɪks.ti dɪˈɡriː ˈfiːd.bæk/", "phản hồi toàn diện từ mọi phía", "360-degree feedback gives complete insight."),
    ("upskilling", "/ˌʌpˈskɪl.ɪŋ/", "nâng cao kỹ năng hiện có", "Upskilling keeps employees competitive."),
    ("reskilling", "/ˌriːˈskɪl.ɪŋ/", "đào tạo lại kỹ năng hoàn toàn mới", "Reskilling prepares workers for automation."),
    ("learning and development", "/ˈlɜːr.nɪŋ ænd dɪˈvɛl.əp.mənt/", "học tập và phát triển nghề nghiệp", "Invest in L&D for better retention."),
    ("employee engagement", "/ɪmˈplɔɪ.iː ɪnˈɡeɪdʒ.mənt/", "sự gắn kết nhiệt tình của nhân viên", "High engagement reduces turnover."),
    ("attrition rate", "/əˈtrɪʃ.ən reɪt/", "tỷ lệ nghỉ việc tự nhiên của nhân viên", "High attrition costs the company."),
    ("headcount", "/ˈhɛd.kaʊnt/", "số lượng nhân sự trong tổ chức", "The headcount will grow by 20%."),
    ("C-suite", "/ˈsiː.swiːt/", "nhóm lãnh đạo cấp cao nhất", "The C-suite approved the strategy."),
    ("stakeholder", "/ˈsteɪk.hoʊl.dər/", "người liên quan có quyền lợi dự án", "Communicate clearly with stakeholders."),
    ("cross-functional", "/ˌkrɒs ˈfʌŋk.ʃən.əl/", "liên phòng ban phối hợp cùng nhau", "Cross-functional teams solve complex problems."),
    ("matrix organization", "/ˈmeɪ.trɪks ˌɔːr.ɡən.aɪˈzeɪ.ʃən/", "tổ chức ma trận hai tuyến báo cáo", "Matrix organizations share resources."),
    ("flat hierarchy", "/flæt ˈhaɪ.ər.ɑːr.ki/", "cấu trúc phẳng ít tầng quản lý", "Flat hierarchies speed up decisions."),
    ("delegation", "/ˌdɛl.ɪˈɡeɪ.ʃən/", "ủy quyền nhiệm vụ cho cấp dưới", "Effective delegation multiplies output."),
    ("accountability", "/əˌkaʊn.tə.ˈbɪl.ɪ.ti/", "trách nhiệm giải trình kết quả công việc", "Accountability drives better performance."),
    ("autonomy", "/ɔːˈtɒn.ə.mi/", "quyền tự chủ trong công việc", "Autonomy increases job satisfaction."),
    ("empowerment", "/ɪmˈpaʊər.mənt/", "trao quyền hạn cho nhân viên", "Empowerment increases employee confidence."),
    ("conflict resolution", "/ˈkɒn.flɪkt ˌrɛz.əˈluː.ʃən/", "giải quyết xung đột trong nhóm", "Conflict resolution preserves team harmony."),
    ("negotiation", "/nɪˌɡoʊ.ʃiˈeɪ.ʃən/", "đàm phán thương lượng mức lương", "Negotiation skills help in salary talks."),
    ("executive coaching", "/ɪɡˈzɛk.jʊ.tɪv ˈkoʊ.tʃɪŋ/", "huấn luyện cá nhân dành cho lãnh đạo", "Executive coaching improves leadership."),
    ("change management", "/tʃeɪndʒ ˈmæn.ɪdʒ.mənt/", "quản lý sự thay đổi tổ chức", "Change management reduces resistance."),
    ("organizational design", "/ˌɔːr.ɡən.aɪˈzeɪ.ʃən.əl dɪˈzaɪn/", "thiết kế cấu trúc tổ chức hiệu quả", "Organizational design supports strategy."),
]

JOB_C1 = [
    ("labor market dynamics", "/ˈleɪ.bər ˈmɑːr.kɪt daɪˈnæm.ɪks/", "động lực thị trường lao động biến đổi", "Labor market dynamics shift with technology."),
    ("gig economy", "/ɡɪɡ ɪˈkɒn.ə.mi/", "nền kinh tế hợp đồng ngắn hạn tự do", "The gig economy offers flexibility."),
    ("platform economy", "/ˈplæt.fɔːrm ɪˈkɒn.ə.mi/", "nền kinh tế nền tảng kỹ thuật số", "Uber operates in the platform economy."),
    ("precarious work", "/prɪˈkeər.i.əs wɜːrk/", "công việc bấp bênh không ổn định", "Precarious work lacks social protection."),
    ("labor relations", "/ˈleɪ.bər rɪˈleɪ.ʃənz/", "quan hệ lao động giữa công ty và nhân viên", "Good labor relations prevent strikes."),
    ("collective bargaining", "/kəˈlɛk.tɪv ˈbɑːr.ɡɪ.nɪŋ/", "thương lượng tập thể của công đoàn", "Collective bargaining protects worker rights."),
    ("industrial action", "/ɪnˈdʌs.tri.əl ˈæk.ʃən/", "hành động công nghiệp đình công phản đối", "Industrial action can halt production."),
    ("human capital", "/ˈhjuː.mən ˈkæp.ɪ.təl/", "vốn nhân lực năng lực con người", "Human capital is a firm's greatest asset."),
    ("intellectual capital", "/ˌɪn.tɪˈlɛk.tʃʊ.əl ˈkæp.ɪ.təl/", "vốn trí tuệ kiến thức sáng tạo", "Intellectual capital drives competitive advantage."),
    ("organizational resilience", "/ˌɔːr.ɡən.aɪˈzeɪ.ʃən.əl rɪˈzɪl.i.əns/", "khả năng phục hồi của tổ chức sau khủng hoảng", "Organizational resilience is built through diversity."),
    ("future of work", "/ˈfjuː.tʃər əv wɜːrk/", "tương lai công việc trong kỷ nguyên AI", "AI shapes the future of work."),
    ("automation displacement", "/ˌɔː.tə.ˈmeɪ.ʃən dɪsˈpleɪs.mənt/", "mất việc làm do tự động hóa thay thế", "Automation displacement requires reskilling."),
    ("augmented workforce", "/ɔːɡˈmɛn.tɪd ˈwɜːrk.fɔːrs/", "lực lượng lao động tăng cường bởi AI", "An augmented workforce uses AI tools."),
    ("strategic workforce planning", "/strəˈtiː.dʒɪk ˈwɜːrk.fɔːrs ˈplæn.ɪŋ/", "lập kế hoạch nhân sự chiến lược dài hạn", "Strategic workforce planning predicts talent needs."),
    ("total rewards strategy", "/ˈtoʊ.təl rɪˈwɔːrdz ˈstræt.ɪ.dʒi/", "chiến lược tổng đãi ngộ toàn diện", "Total rewards include pay, benefits, and culture."),
    ("pay equity analysis", "/peɪ ˈɛk.wɪ.ti əˈnæl.ɪ.sɪs/", "phân tích công bằng tiền lương giới tính", "Pay equity analysis closes the gender pay gap."),
    ("competency-based interview", "/kəmˈpɛt.ən.si beɪst ˈɪn.tə.vjuː/", "phỏng vấn dựa trên năng lực hành vi", "Competency-based interviews reveal true behavior."),
    ("behavioral interview", "/bɪˈheɪ.vjər.əl ˈɪn.tə.vjuː/", "phỏng vấn hành vi tình huống cụ thể", "Behavioral interviews use STAR method."),
    ("STAR method", "/stɑːr ˈmɛθ.əd/", "phương pháp tình huống nhiệm vụ hành động kết quả", "Use the STAR method to answer questions."),
    ("high-potential", "/haɪ pəˈtɛn.ʃəl/", "nhân tài tiềm năng cao trong tổ chức", "Identify high-potential employees early."),
    ("leadership pipeline", "/ˈliː.dər.ʃɪp ˈpaɪp.laɪn/", "chuỗi lãnh đạo kế cận được chuẩn bị", "A leadership pipeline ensures continuity."),
    ("psychological contract", "/ˌsaɪ.kəˈlɒdʒ.ɪ.kəl ˈkɒn.trækt/", "hợp đồng tâm lý kỳ vọng ngầm định", "Breaking the psychological contract causes turnover."),
    ("organizational citizenship behavior", "/ˌɔːr.ɡən.aɪˈzeɪ.ʃən.əl ˈsɪt.ɪ.zən.ʃɪp bɪˈheɪ.vjər/", "hành vi công dân tổ chức tự nguyện", "OCB goes beyond formal job requirements."),
    ("job crafting", "/dʒɒb ˈkrɑːf.tɪŋ/", "tái thiết kế công việc phù hợp bản thân", "Job crafting improves meaning and engagement."),
    ("burnout prevention", "/ˈbɜːrn.aʊt prɪˈvɛn.ʃən/", "phòng ngừa kiệt sức chuyên nghiệp", "Burnout prevention requires systemic change."),
    ("wellbeing strategy", "/ˈwɛl.biː.ɪŋ ˈstræt.ɪ.dʒi/", "chiến lược phúc lợi sức khỏe nhân viên", "A wellbeing strategy reduces absenteeism."),
    ("inclusive leadership", "/ɪnˈkluː.sɪv ˈliː.dər.ʃɪp/", "lãnh đạo hòa nhập tôn trọng đa dạng", "Inclusive leadership values every voice."),
    ("servant leadership", "/ˈsɜːr.vənt ˈliː.dər.ʃɪp/", "lãnh đạo phụng sự phục vụ nhóm trước", "Servant leadership puts the team first."),
    ("transformational leadership", "/trænsˈfɔːr.mə.ʃən.əl ˈliː.dər.ʃɪp/", "lãnh đạo chuyển hóa truyền cảm hứng", "Transformational leadership inspires change."),
    ("transactional leadership", "/trænˈzæk.ʃən.əl ˈliː.dər.ʃɪp/", "lãnh đạo giao dịch dùng thưởng phạt", "Transactional leadership uses rewards and punishments."),
    ("situational leadership", "/ˌsɪtʃ.ʊˈeɪ.ʃən.əl ˈliː.dər.ʃɪp/", "lãnh đạo tình huống linh hoạt thích ứng", "Situational leadership adapts to team needs."),
    ("cognitive diversity", "/ˈkɒɡ.nɪ.tɪv daɪˈvɜːr.sɪ.ti/", "đa dạng nhận thức cách tư duy khác nhau", "Cognitive diversity improves decision quality."),
    ("knowledge management", "/ˈnɒl.ɪdʒ ˈmæn.ɪdʒ.mənt/", "quản lý tri thức tổ chức chia sẻ", "Knowledge management prevents brain drain."),
    ("learning organization", "/ˈlɜːr.nɪŋ ˌɔːr.ɡən.aɪˈzeɪ.ʃən/", "tổ chức học hỏi liên tục thích nghi", "A learning organization adapts quickly."),
    ("meritocracy", "/ˌmɛr.ɪˈtɒk.rə.si/", "chế độ trọng dụng nhân tài theo thực lực", "A meritocracy rewards hard work."),
    ("nepotism", "/ˈnɛp.ə.tɪ.zəm/", "chủ nghĩa thân tộc thiên vị người quen", "Nepotism undermines fairness."),
    ("imposter syndrome", "/ɪmˈpɒs.tər ˈsɪn.droʊm/", "hội chứng kẻ mạo danh tự ti năng lực", "Many leaders experience imposter syndrome."),
    ("career capital", "/kəˈrɪər ˈkæp.ɪ.təl/", "vốn sự nghiệp kỹ năng và mối quan hệ", "Build career capital before choosing a path."),
    ("professional network", "/prəˈfɛʃ.ən.əl ˈnɛt.wɜːrk/", "mạng lưới chuyên nghiệp hỗ trợ sự nghiệp", "A strong professional network opens doors."),
    ("executive presence", "/ɪɡˈzɛk.jʊ.tɪv ˈprɛz.əns/", "phong thái lãnh đạo tạo ảnh hưởng", "Executive presence commands respect."),
    ("strategic thinking", "/strəˈtiː.dʒɪk ˈθɪŋ.kɪŋ/", "tư duy chiến lược dài hạn toàn diện", "Strategic thinking separates leaders from managers."),
    ("systems thinking", "/ˈsɪs.təmz ˈθɪŋ.kɪŋ/", "tư duy hệ thống toàn diện kết nối", "Systems thinking reveals root causes."),
    ("double-loop learning", "/ˈdʌb.əl luːp ˈlɜːr.nɪŋ/", "học vòng đôi thay đổi tư duy giả định", "Double-loop learning challenges assumptions."),
    ("after-action review", "/ˈɑːf.tər ˈæk.ʃən rɪˈvjuː/", "đánh giá sau hành động rút kinh nghiệm", "After-action reviews improve team learning."),
    ("appreciative inquiry", "/əˈpriː.ʃi.ə.tɪv ɪnˈkwaɪər.i/", "truy vấn trân trọng tập trung điểm mạnh", "Appreciative inquiry builds on strengths."),
    ("positive organizational scholarship", "/ˈpɒz.ɪ.tɪv ˌɔːr.ɡən.aɪˈzeɪ.ʃən.əl ˈskɒl.ər.ʃɪp/", "học thuật tổ chức tích cực phát huy tiềm năng", "POS focuses on human flourishing at work."),
    ("total quality management", "/ˈtoʊ.təl ˈkwɒl.ɪ.ti ˈmæn.ɪdʒ.mənt/", "quản lý chất lượng toàn diện TQM", "TQM improves processes continuously."),
    ("lean management", "/liːn ˈmæn.ɪdʒ.mənt/", "quản lý tinh gọn loại bỏ lãng phí", "Lean management eliminates waste."),
    ("six sigma", "/sɪks ˈsɪɡ.mə/", "phương pháp cải tiến chất lượng 6 sigma", "Six Sigma reduces process defects."),
    ("kaizen", "/ˈkaɪ.zɛn/", "triết lý cải tiến liên tục mỗi ngày", "Kaizen means continuous small improvements."),
]

# ===== BUSINESS =====
# Đã có B1: annual report, audit, benchmark, board of directors, brand awareness...

BUSINESS_A1 = [
    ("money", "/ˈmʌn.i/", "tiền tệ phương tiện trao đổi", "Money is needed to run a business."),
    ("sell", "/sɛl/", "bán sản phẩm dịch vụ", "We sell software to companies."),
    ("buy", "/baɪ/", "mua hàng hóa dịch vụ", "Buy supplies from the market."),
    ("profit", "/ˈprɒf.ɪt/", "lợi nhuận sau chi phí", "The profit margin is 20%."),
    ("loss", "/lɒs/", "thua lỗ kinh doanh", "The company made a loss last year."),
    ("cost", "/kɒst/", "chi phí kinh doanh", "Reduce costs to increase profit."),
    ("price", "/praɪs/", "giá bán sản phẩm", "Set a competitive price."),
    ("customer", "/ˈkʌs.tə.mər/", "khách hàng mua hàng", "Keep customers happy always."),
    ("product", "/ˈprɒd.ʌkt/", "sản phẩm kinh doanh", "Our product is high quality."),
    ("service", "/ˈsɜːr.vɪs/", "dịch vụ cung cấp", "We offer 24/7 customer service."),
    ("store", "/stɔːr/", "cửa hàng kinh doanh", "Open a store downtown."),
    ("shop", "/ʃɒp/", "cửa hàng bán lẻ nhỏ", "The corner shop is profitable."),
    ("market", "/ˈmɑːr.kɪt/", "thị trường kinh doanh", "Enter a new market this year."),
    ("bank", "/bæŋk/", "ngân hàng tài chính", "Keep money in the bank."),
    ("loan", "/loʊn/", "khoản vay ngân hàng", "Take a loan to start business."),
    ("tax", "/tæks/", "thuế phải nộp", "Pay taxes on time."),
    ("order", "/ˈɔːr.dər/", "đơn hàng đặt mua", "Process orders quickly."),
    ("invoice", "/ˈɪn.vɔɪs/", "hóa đơn xuất bán", "Send an invoice to the client."),
    ("payment", "/ˈpeɪ.mənt/", "khoản thanh toán", "Receive payment within 30 days."),
    ("contract", "/ˈkɒn.trækt/", "hợp đồng ký kết", "Sign the contract before starting."),
    ("partner", "/ˈpɑːrt.nər/", "đối tác kinh doanh", "Find a reliable business partner."),
    ("deal", "/diːl/", "thương vụ kinh doanh", "Close the deal this week."),
    ("office", "/ˈɒf.ɪs/", "văn phòng công ty", "Rent a small office downtown."),
    ("meeting", "/ˈmiː.tɪŋ/", "cuộc họp kinh doanh", "Schedule a client meeting."),
    ("plan", "/plæn/", "kế hoạch kinh doanh", "Write a business plan."),
    ("goal", "/ɡoʊl/", "mục tiêu kinh doanh", "Set clear business goals."),
    ("growth", "/ɡroʊθ/", "tăng trưởng doanh nghiệp", "Aim for 20% growth."),
    ("success", "/səkˈsɛs/", "thành công kinh doanh", "Success requires hard work."),
    ("fail", "/feɪl/", "thất bại trong kinh doanh", "Learn from every failure."),
    ("open", "/ˈoʊ.pən/", "khai trương mở cửa", "Open the shop at nine."),
    ("close", "/kloʊz/", "đóng cửa kết thúc", "Close the store at seven."),
    ("earn", "/ɜːrn/", "kiếm tiền thu nhập", "Earn more by working smart."),
    ("spend", "/spɛnd/", "tiêu tiền chi phí", "Spend wisely on marketing."),
    ("save", "/seɪv/", "tiết kiệm tiền dự phòng", "Save 10% of monthly income."),
    ("invest", "/ɪnˈvɛst/", "đầu tư tạo lợi nhuận", "Invest in good people."),
    ("return", "/rɪˈtɜːrn/", "lợi nhuận thu về từ đầu tư", "Get a good return on investment."),
    ("budget", "/ˈbʌdʒ.ɪt/", "ngân sách phân bổ chi tiêu", "Stick to the monthly budget."),
    ("account", "/əˈkaʊnt/", "tài khoản ngân hàng kinh doanh", "Open a business bank account."),
    ("bill", "/bɪl/", "hóa đơn phải trả", "Pay the bills on time."),
    ("receipt", "/rɪˈsiːt/", "hóa đơn biên lai mua hàng", "Keep every receipt for taxes."),
    ("stock", "/stɒk/", "hàng tồn kho", "Monitor your stock levels."),
    ("supply", "/səˈplaɪ/", "nguồn cung hàng hóa", "Ensure a steady supply."),
    ("delivery", "/dɪˈlɪv.ər.i/", "giao hàng đến khách", "Offer fast free delivery."),
    ("quality", "/ˈkwɒl.ɪ.ti/", "chất lượng sản phẩm", "Quality builds trust."),
    ("owner", "/ˈoʊ.nər/", "chủ doanh nghiệp", "The owner manages the team."),
    ("staff", "/stɑːf/", "đội ngũ nhân viên", "Hire friendly staff."),
    ("salary", "/ˈsæl.ər.i/", "lương nhân viên hàng tháng", "Pay staff a fair salary."),
    ("hire", "/haɪər/", "thuê nhân viên mới", "Hire experienced staff."),
    ("fire", "/faɪər/", "sa thải nhân viên", "Fire employees who underperform."),
    ("grow", "/ɡroʊ/", "mở rộng tăng trưởng", "Grow the business steadily."),
]

BUSINESS_A2 = [
    ("revenue", "/ˈrɛv.ɪ.njuː/", "doanh thu tổng cộng", "The revenue grew by 30%."),
    ("expenses", "/ɪkˈspɛn.sɪz/", "chi phí vận hành", "Cut unnecessary expenses."),
    ("cash flow", "/kæʃ floʊ/", "dòng tiền vào và ra", "Positive cash flow is essential."),
    ("balance sheet", "/ˈbæl.əns ʃiːt/", "bảng cân đối kế toán", "Review the balance sheet monthly."),
    ("income statement", "/ˈɪn.kʌm ˈsteɪt.mənt/", "báo cáo kết quả kinh doanh", "The income statement shows profits."),
    ("gross profit", "/ɡroʊs ˈprɒf.ɪt/", "lợi nhuận gộp trước chi phí", "The gross profit was high."),
    ("net profit", "/nɛt ˈprɒf.ɪt/", "lợi nhuận ròng sau tất cả chi phí", "Net profit is what you keep."),
    ("overhead", "/ˈoʊ.vər.hɛd/", "chi phí hoạt động cố định", "Reduce overhead to improve margins."),
    ("breakeven", "/ˌbreɪkˈiː.vən/", "hòa vốn không lãi không lỗ", "We reached breakeven in six months."),
    ("startup capital", "/ˈstɑːr.tʌp ˈkæp.ɪ.təl/", "vốn ban đầu khởi nghiệp", "Raise startup capital from investors."),
    ("investor", "/ɪnˈvɛs.tər/", "nhà đầu tư rót vốn", "Find an angel investor."),
    ("equity", "/ˈɛk.wɪ.ti/", "vốn cổ phần sở hữu", "Give investors 20% equity."),
    ("shareholder", "/ˈʃɛər.hoʊl.dər/", "cổ đông sở hữu cổ phần", "Shareholders receive dividends."),
    ("dividend", "/ˈdɪv.ɪ.dɛnd/", "cổ tức chia cho cổ đông", "Pay dividends from profits."),
    ("valuation", "/ˌvæl.jʊˈeɪ.ʃən/", "định giá doanh nghiệp", "The startup valuation is 10 million."),
    ("funding", "/ˈfʌn.dɪŋ/", "nguồn tài trợ vốn", "Secure funding before launching."),
    ("venture capital", "/ˈvɛn.tʃər ˈkæp.ɪ.təl/", "vốn đầu tư mạo hiểm", "Venture capital funds high-growth startups."),
    ("IPO", "/ˌaɪ.piːˈoʊ/", "phát hành cổ phiếu lần đầu ra công chúng", "The company plans an IPO next year."),
    ("merger", "/ˈmɜːr.dʒər/", "sáp nhập hai công ty thành một", "The merger created a bigger firm."),
    ("acquisition", "/ˌæk.wɪˈzɪʃ.ən/", "mua lại công ty khác", "The acquisition cost 50 million."),
    ("franchise", "/ˈfræn.tʃaɪz/", "nhượng quyền kinh doanh", "Buy a franchise to expand."),
    ("license", "/ˈlaɪ.səns/", "giấy phép kinh doanh", "Obtain a business license first."),
    ("trademark", "/ˈtreɪd.mɑːrk/", "nhãn hiệu đăng ký bảo hộ", "Register your trademark early."),
    ("patent", "/ˈpæt.ənt/", "bằng sáng chế bảo vệ ý tưởng", "Patent your innovation."),
    ("copyright", "/ˈkɒp.i.raɪt/", "bản quyền tác phẩm sáng tạo", "Copyright protects creative work."),
    ("subsidiary", "/səbˈsɪd.i.ər.i/", "công ty con trực thuộc", "Set up a subsidiary overseas."),
    ("joint venture", "/dʒɔɪnt ˈvɛn.tʃər/", "liên doanh hợp tác cùng đầu tư", "A joint venture shares risks."),
    ("partnership", "/ˈpɑːrt.nər.ʃɪp/", "quan hệ đối tác kinh doanh", "Form a partnership with a supplier."),
    ("sole trader", "/soʊl ˈtreɪ.dər/", "cá nhân kinh doanh một mình", "A sole trader has full control."),
    ("limited company", "/ˈlɪm.ɪ.tɪd ˈkʌm.pə.ni/", "công ty trách nhiệm hữu hạn", "Register as a limited company."),
    ("nonprofit", "/nɒnˈprɒf.ɪt/", "tổ chức phi lợi nhuận", "They run a nonprofit organization."),
    ("corporation", "/ˌkɔːr.pəˈreɪ.ʃən/", "tập đoàn công ty lớn", "The corporation has global offices."),
    ("supply chain", "/səˈplaɪ tʃeɪn/", "chuỗi cung ứng từ sản xuất đến bán", "Optimize the supply chain."),
    ("vendor", "/ˈvɛn.dər/", "nhà cung cấp dịch vụ hàng hóa", "Choose vendors carefully."),
    ("supplier", "/səˈplaɪ.ər/", "nhà cung ứng nguyên vật liệu", "Build strong supplier relationships."),
    ("outsourcing", "/ˈaʊt.sɔːr.sɪŋ/", "thuê ngoài dịch vụ tiết kiệm chi phí", "Outsourcing reduces operating costs."),
    ("offshoring", "/ˈɒf.ʃɔːr.ɪŋ/", "chuyển hoạt động ra nước ngoài", "Offshoring lowers labor costs."),
    ("B2B", "/ˌbiː.tuːˈbiː/", "doanh nghiệp bán cho doanh nghiệp", "We operate in the B2B sector."),
    ("B2C", "/ˌbiː.tuːˈsiː/", "doanh nghiệp bán cho người tiêu dùng", "B2C needs strong branding."),
    ("e-commerce", "/ˈiː.kɒm.ɜːrs/", "thương mại điện tử mua bán online", "E-commerce grew 40% last year."),
    ("brick and mortar", "/brɪk ænd ˈmɔːr.tər/", "cửa hàng thực tế không phải online", "Brick and mortar stores still matter."),
    ("omnichannel", "/ˌɒm.niˈtʃæn.əl/", "đa kênh phân phối liền mạch", "Adopt an omnichannel approach."),
    ("distribution", "/ˌdɪs.trɪˈbjuː.ʃən/", "phân phối hàng hóa đến khách", "Build a strong distribution network."),
    ("logistics", "/ləˈdʒɪs.tɪks/", "hậu cần vận chuyển hàng hóa", "Efficient logistics saves money."),
    ("inventory", "/ˈɪn.vən.tɒr.i/", "hàng tồn kho quản lý", "Track inventory in real time."),
    ("warehouse", "/ˈweər.haʊs/", "kho hàng lưu trữ", "The warehouse holds 10,000 items."),
    ("margin", "/ˈmɑːr.dʒɪn/", "biên lợi nhuận", "Improve margins by cutting waste."),
    ("markup", "/ˈmɑːr.kʌp/", "mức tăng giá bán so với giá gốc", "A 50% markup covers overhead costs."),
    ("discount", "/ˈdɪs.kaʊnt/", "chiết khấu giảm giá đặc biệt", "Offer bulk discounts to big clients."),
    ("negotiation", "/nɪˌɡoʊ.ʃiˈeɪ.ʃən/", "đàm phán thương lượng hợp đồng", "Strong negotiation skills save money."),
]

BUSINESS_B2 = [
    ("competitive strategy", "/kəmˈpɛt.ɪ.tɪv ˈstræt.ɪ.dʒi/", "chiến lược cạnh tranh bền vững", "Porter defines three competitive strategies."),
    ("value chain analysis", "/ˈvæl.juː tʃeɪn əˈnæl.ɪ.sɪs/", "phân tích chuỗi giá trị doanh nghiệp", "Value chain analysis identifies cost drivers."),
    ("core competency", "/kɔːr kəmˈpɛt.ən.si/", "năng lực cốt lõi khác biệt hóa", "Identify your core competencies."),
    ("business model innovation", "/ˈbɪz.nɪs ˈmɒd.əl ˌɪn.əˈveɪ.ʃən/", "đổi mới mô hình kinh doanh", "Business model innovation disrupts markets."),
    ("platform business model", "/ˈplæt.fɔːrm ˈbɪz.nɪs ˈmɒd.əl/", "mô hình kinh doanh nền tảng hai mặt", "Amazon uses a platform business model."),
    ("network effects", "/ˈnɛt.wɜːrk ɪˈfɛkts/", "hiệu ứng mạng lưới tăng giá trị theo người dùng", "Network effects create winner-take-all markets."),
    ("economies of scale", "/ɪˈkɒn.ə.miz əv skeɪl/", "kinh tế quy mô giảm chi phí khi tăng sản lượng", "Economies of scale lower unit costs."),
    ("economies of scope", "/ɪˈkɒn.ə.miz əv skoʊp/", "kinh tế phạm vi tiết kiệm sản xuất đa ngành", "Economies of scope benefit diversified firms."),
    ("market positioning", "/ˈmɑːr.kɪt pəˈzɪʃ.ən.ɪŋ/", "định vị thị trường trong tâm trí khách hàng", "Strong market positioning builds loyalty."),
    ("go-to-market", "/ˌɡoʊ.tʊˈmɑːr.kɪt/", "chiến lược tiếp cận thị trường mới", "Define the go-to-market before launch."),
    ("scalable business", "/ˈskeɪ.lə.bəl ˈbɪz.nɪs/", "kinh doanh có khả năng mở rộng quy mô", "Build a scalable business from day one."),
    ("revenue model", "/ˈrɛv.ɪ.njuː ˈmɒd.əl/", "mô hình doanh thu của doanh nghiệp", "Choose the right revenue model."),
    ("unit economics", "/ˈjuː.nɪt ˌɪ.kəˈnɒm.ɪks/", "kinh tế đơn vị sản phẩm lãi lỗ", "Understand unit economics before scaling."),
    ("customer acquisition cost", "/ˈkʌs.tə.mər ˌæk.wɪˈzɪʃ.ən kɒst/", "chi phí có được một khách hàng mới", "Lower customer acquisition cost improves margins."),
    ("lifetime value", "/ˈlaɪf.taɪm ˈvæl.juː/", "giá trị vòng đời của khách hàng", "High LTV justifies higher acquisition spend."),
    ("churn", "/tʃɜːrn/", "tỷ lệ khách hàng rời bỏ dịch vụ", "Reduce churn to improve retention."),
    ("retention rate", "/rɪˈtɛn.ʃən reɪt/", "tỷ lệ giữ chân khách hàng lâu dài", "A high retention rate signals loyalty."),
    ("expansion revenue", "/ɪkˈspæn.ʃən ˈrɛv.ɪ.njuː/", "doanh thu từ khách hàng mở rộng sử dụng", "Expansion revenue grows without new customers."),
    ("annual recurring revenue", "/ˈæn.jʊ.əl rɪˈkɜːr.ɪŋ ˈrɛv.ɪ.njuː/", "doanh thu định kỳ hàng năm ổn định", "ARR is the key SaaS metric."),
    ("monthly recurring revenue", "/ˈmʌnθ.li rɪˈkɜːr.ɪŋ ˈrɛv.ɪ.njuː/", "doanh thu định kỳ hàng tháng", "Track MRR to measure growth."),
    ("EBITDA", "/ɪˈbɪt.də/", "lợi nhuận trước lãi vay thuế khấu hao", "EBITDA measures operational profitability."),
    ("working capital", "/ˈwɜːr.kɪŋ ˈkæp.ɪ.təl/", "vốn lưu động hoạt động hàng ngày", "Manage working capital carefully."),
    ("liquidity", "/lɪˈkwɪd.ɪ.ti/", "tính thanh khoản tài sản dễ chuyển đổi", "Maintain enough liquidity for operations."),
    ("solvency", "/ˈsɒl.vən.si/", "khả năng thanh toán nợ dài hạn", "Solvency ensures long-term viability."),
    ("credit risk", "/ˈkrɛd.ɪt rɪsk/", "rủi ro tín dụng khách không trả nợ", "Assess credit risk before extending terms."),
    ("hedging", "/ˈhɛdʒ.ɪŋ/", "phòng ngừa rủi ro tài chính", "Hedging protects against currency risk."),
    ("due diligence", "/djuː ˈdɪl.ɪ.dʒəns/", "thẩm định kỹ lưỡng trước khi đầu tư", "Conduct due diligence before acquisition."),
    ("term sheet", "/tɜːrm ʃiːt/", "bản điều khoản đầu tư sơ bộ", "Review the term sheet carefully."),
    ("cap table", "/kæp ˈteɪ.bəl/", "bảng phân bổ vốn cổ phần", "Manage your cap table carefully."),
    ("vesting schedule", "/ˈvɛs.tɪŋ ˈʃɛd.juːl/", "lịch trình trao quyền cổ phần theo thời gian", "The vesting schedule spans four years."),
    ("burn rate", "/bɜːrn reɪt/", "tốc độ đốt tiền hàng tháng", "Monitor burn rate to extend runway."),
    ("runway", "/ˈrʌn.weɪ/", "thời gian sống sót còn lại của startup", "We have 18 months of runway."),
    ("pivot", "/ˈpɪv.ɪt/", "chuyển hướng chiến lược kinh doanh", "The company pivoted to SaaS."),
    ("traction", "/ˈtræk.ʃən/", "sức kéo tăng trưởng chứng minh được", "Demonstrate traction before raising."),
    ("product roadmap", "/ˈprɒd.ʌkt ˈroʊd.mæp/", "lộ trình phát triển sản phẩm", "Share the product roadmap with investors."),
    ("board meeting", "/bɔːrd ˈmiː.tɪŋ/", "cuộc họp hội đồng quản trị", "The board meeting is quarterly."),
    ("stakeholder management", "/ˈsteɪk.hoʊl.dər ˈmæn.ɪdʒ.mənt/", "quản lý kỳ vọng các bên liên quan", "Stakeholder management prevents conflict."),
    ("exit strategy", "/ˈɛk.sɪt ˈstræt.ɪ.dʒi/", "chiến lược thoát vốn cho nhà đầu tư", "Plan an exit strategy from the start."),
    ("M&A", "/ˌɛm.ænˈeɪ/", "mua bán và sáp nhập doanh nghiệp", "M&A activity increased last quarter."),
    ("leveraged buyout", "/ˈlɛv.ər.ɪdʒd ˈbaɪ.aʊt/", "mua lại doanh nghiệp bằng đòn bẩy nợ", "A leveraged buyout uses debt financing."),
    ("private equity", "/ˈpraɪ.vɪt ˈɛk.wɪ.ti/", "vốn tư nhân đầu tư vào công ty chưa niêm yết", "Private equity firms acquire mature companies."),
    ("Series A/B/C", "/ˈsɪər.iːz eɪ biː siː/", "vòng gọi vốn từ A đến C cho startup", "Raise Series A after proving growth."),
    ("angel investor", "/ˈeɪn.dʒəl ɪnˈvɛs.tər/", "nhà đầu tư thiên thần giai đoạn đầu", "An angel investor backs early startups."),
    ("bootstrapping", "/ˈbuːt.stræp.ɪŋ/", "tự tài trợ không cần vốn bên ngoài", "Bootstrapping avoids equity dilution."),
    ("crowdfunding", "/ˈkraʊd.fʌn.dɪŋ/", "gọi vốn từ đông đảo cộng đồng nhỏ lẻ", "Crowdfunding validates product demand."),
    ("convertible note", "/kənˈvɜːr.tɪ.bəl noʊt/", "trái phiếu chuyển đổi thành cổ phần", "A convertible note delays valuation."),
    ("SAFE agreement", "/seɪf əˈɡriː.mənt/", "thỏa thuận vốn đơn giản cho nhà đầu tư tương lai", "A SAFE is simpler than a convertible note."),
    ("pre-money valuation", "/priːˈmʌn.i ˌvæl.jʊˈeɪ.ʃən/", "định giá trước khi nhận vốn đầu tư", "The pre-money valuation was 5 million."),
    ("post-money valuation", "/poʊstˈmʌn.i ˌvæl.jʊˈeɪ.ʃən/", "định giá sau khi nhận vốn đầu tư", "The post-money valuation reached 7 million."),
    ("dilution", "/daɪˈluː.ʃən/", "pha loãng cổ phần khi phát hành thêm", "New funding causes equity dilution."),
]

BUSINESS_C1 = [
    ("corporate governance", "/ˈkɔːr.pər.ɪt ˈɡʌv.ər.nəns/", "quản trị doanh nghiệp minh bạch có trách nhiệm", "Strong corporate governance builds trust."),
    ("fiduciary duty", "/fɪˈdjuː.ʃi.ər.i ˈdjuː.ti/", "nghĩa vụ ủy thác trung thành với cổ đông", "Directors have a fiduciary duty to shareholders."),
    ("agency problem", "/ˈeɪ.dʒən.si ˈprɒb.ləm/", "vấn đề đại lý xung đột lợi ích quản lý-cổ đông", "The agency problem arises from ownership separation."),
    ("asymmetric information", "/ˌeɪ.sɪˈmɛt.rɪk ˌɪn.fəˈmeɪ.ʃən/", "thông tin bất cân xứng giữa các bên giao dịch", "Asymmetric information causes market failures."),
    ("principal-agent relationship", "/ˈprɪn.sɪ.pəl ˈeɪ.dʒənt rɪˈleɪ.ʃən.ʃɪp/", "quan hệ ủy nhiệm giữa chủ sở hữu và người quản lý", "The principal-agent relationship creates incentive issues."),
    ("moral hazard", "/ˈmɒr.əl ˈhæz.ərd/", "rủi ro đạo đức khi người được bảo vệ hành xử rủi ro", "Insurance creates a moral hazard."),
    ("adverse selection", "/ˈæd.vɜːrs sɪˈlɛk.ʃən/", "lựa chọn ngược lại khi thông tin bất cân xứng", "Adverse selection plagues insurance markets."),
    ("transaction cost economics", "/trænsˈæk.ʃən kɒst ˌɪ.kəˈnɒm.ɪks/", "kinh tế học chi phí giao dịch của Coase", "Transaction cost economics explains firm boundaries."),
    ("institutional theory", "/ˌɪn.stɪˈtjuː.ʃən.əl ˈθɪər.i/", "lý thuyết thể chế giải thích hành vi tổ chức", "Institutional theory explains why firms mimic each other."),
    ("resource-based view", "/rɪˈzɔːrs beɪst vjuː/", "quan điểm nguồn lực lợi thế cạnh tranh bền vững", "The resource-based view focuses on unique assets."),
    ("dynamic capabilities", "/daɪˈnæm.ɪk ˌkeɪ.pə.ˈbɪl.ɪ.tɪz/", "năng lực động để thích nghi và đổi mới", "Dynamic capabilities enable adaptation to change."),
    ("absorptive capacity", "/əbˈzɔːrp.tɪv kəˈpæs.ɪ.ti/", "năng lực hấp thụ tri thức mới từ bên ngoài", "Absorptive capacity enables external knowledge use."),
    ("open innovation", "/ˈoʊ.pən ˌɪn.əˈveɪ.ʃən/", "đổi mới mở hợp tác với bên ngoài", "Open innovation leverages external ideas."),
    ("ambidexterity", "/ˌæm.bɪˈdɛks.tər.ɪ.ti/", "tính thuận hai tay cân bằng khai thác và khám phá", "Ambidexterity balances efficiency and innovation."),
    ("organizational learning", "/ˌɔːr.ɡən.aɪˈzeɪ.ʃən.əl ˈlɜːr.nɪŋ/", "học hỏi tổ chức cải thiện năng lực theo thời gian", "Organizational learning drives continuous improvement."),
    ("institutional isomorphism", "/ˌɪn.stɪˈtjuː.ʃən.əl ˌaɪ.sə.ˈmɔːr.fɪ.zəm/", "đồng hình thể chế các tổ chức trở nên giống nhau", "Institutional isomorphism makes firms look similar."),
    ("strategic alignment", "/strəˈtiː.dʒɪk əˈlaɪn.mənt/", "căn chỉnh chiến lược giữa các cấp doanh nghiệp", "Strategic alignment ensures coordinated execution."),
    ("value proposition canvas", "/ˈvæl.juː ˌprɒp.əˈzɪʃ.ən ˈkæn.vəs/", "khung đề xuất giá trị cho khách hàng", "Use the value proposition canvas for product fit."),
    ("business model canvas", "/ˈbɪz.nɪs ˈmɒd.əl ˈkæn.vəs/", "khung mô hình kinh doanh chín khối", "Map your business using the business model canvas."),
    ("lean startup", "/liːn ˈstɑːr.tʌp/", "phương pháp khởi nghiệp tinh gọn học nhanh", "The lean startup method minimizes waste."),
    ("design thinking", "/dɪˈzaɪn ˈθɪŋ.kɪŋ/", "tư duy thiết kế lấy con người làm trung tâm", "Design thinking solves complex business problems."),
    ("jobs to be done", "/dʒɒbz tʊ biː dʌn/", "lý thuyết công việc cần hoàn thành của khách hàng", "Jobs to be done theory explains buying behavior."),
    ("disruptive innovation", "/dɪsˈrʌp.tɪv ˌɪn.əˈveɪ.ʃən/", "đổi mới đột phá thay thế thị trường hiện có", "Disruptive innovation creates new markets."),
    ("sustaining innovation", "/səˈsteɪ.nɪŋ ˌɪn.əˈveɪ.ʃən/", "đổi mới duy trì cải thiện sản phẩm hiện tại", "Sustaining innovation improves existing products."),
    ("blue ocean strategy", "/bluː ˈoʊ.ʃən ˈstræt.ɪ.dʒi/", "chiến lược đại dương xanh tạo thị trường mới", "Blue ocean strategy avoids direct competition."),
    ("stakeholder capitalism", "/ˈsteɪk.hoʊl.dər ˈkæp.ɪ.tə.lɪzm/", "chủ nghĩa tư bản các bên liên quan rộng hơn", "Stakeholder capitalism considers all parties."),
    ("ESG", "/ˌiː.ɛsˈdʒiː/", "môi trường xã hội quản trị doanh nghiệp bền vững", "ESG factors affect investment decisions."),
    ("circular economy", "/ˈsɜːr.kjʊ.lər ɪˈkɒn.ə.mi/", "kinh tế tuần hoàn tái sử dụng không lãng phí", "A circular economy eliminates waste."),
    ("social enterprise", "/ˈsoʊ.ʃəl ˈɛn.tər.praɪz/", "doanh nghiệp xã hội lợi nhuận và sứ mệnh", "A social enterprise balances profit and purpose."),
    ("shared value creation", "/ʃɛərd ˈvæl.juː kriˈeɪ.ʃən/", "tạo giá trị chung cho doanh nghiệp và xã hội", "Shared value creation aligns business with society."),
    ("impact investing", "/ˈɪm.pækt ɪnˈvɛs.tɪŋ/", "đầu tư tạo ra tác động xã hội tích cực", "Impact investing seeks financial and social returns."),
    ("triple bottom line", "/ˈtrɪp.əl ˈbɒt.əm laɪn/", "ba nền tảng lợi nhuận con người hành tinh", "The triple bottom line measures people, planet, profit."),
    ("regenerative business", "/rɪˈdʒɛn.ər.ə.tɪv ˈbɪz.nɪs/", "kinh doanh tái sinh phục hồi hệ sinh thái", "Regenerative business goes beyond sustainability."),
    ("B Corp certification", "/biː kɔːrp ˌsɜːr.tɪ.fɪˈkeɪ.ʃən/", "chứng nhận doanh nghiệp vì lợi ích xã hội", "B Corp certification signals social commitment."),
    ("shareholder primacy", "/ˈʃɛər.hoʊl.dər ˈpraɪ.mə.si/", "ưu tiên tối đa hóa giá trị cổ đông", "Shareholder primacy is questioned today."),
    ("purpose-driven business", "/ˈpɜːr.pəs ˈdrɪv.ən ˈbɪz.nɪs/", "kinh doanh có mục đích sứ mệnh ý nghĩa", "Purpose-driven businesses attract loyal employees."),
    ("organizational agility", "/ˌɔːr.ɡən.aɪˈzeɪ.ʃən.əl əˈdʒɪl.ɪ.ti/", "sự linh hoạt tổ chức thích nghi nhanh chóng", "Organizational agility enables rapid pivots."),
    ("resilient supply chain", "/rɪˈzɪl.i.ənt səˈplaɪ tʃeɪn/", "chuỗi cung ứng bền vững chịu đựng gián đoạn", "A resilient supply chain withstands disruptions."),
    ("geopolitical risk", "/ˌdʒiː.oʊ.pəˈlɪt.ɪ.kəl rɪsk/", "rủi ro địa chính trị ảnh hưởng kinh doanh", "Geopolitical risk affects global supply chains."),
    ("deglobalization", "/diːˌɡloʊ.bəl.aɪˈzeɪ.ʃən/", "phi toàn cầu hóa rút về sản xuất trong nước", "Deglobalization reshapes trade patterns."),
    ("nearshoring", "/ˈnɪər.ʃɔːr.ɪŋ/", "chuyển sản xuất về nước gần địa lý", "Nearshoring reduces supply chain risk."),
    ("regulatory compliance", "/ˌrɛɡ.jʊ.lə.tər.i kəmˈplaɪ.əns/", "tuân thủ quy định pháp lý của cơ quan chức năng", "Regulatory compliance avoids costly fines."),
    ("antitrust law", "/ˈæn.ti.trʌst lɔː/", "luật chống độc quyền bảo vệ cạnh tranh", "Antitrust law prevents monopolistic behavior."),
    ("market concentration", "/ˈmɑːr.kɪt ˌkɒn.sənˈtreɪ.ʃən/", "tập trung thị trường ít công ty chi phối", "High market concentration reduces competition."),
    ("contestable market", "/kənˈtɛs.tə.bəl ˈmɑːr.kɪt/", "thị trường có thể tranh chấp dễ gia nhập", "A contestable market has low entry barriers."),
    ("asymmetric bargaining power", "/ˌeɪ.sɪˈmɛt.rɪk ˈbɑːr.ɡɪ.nɪŋ ˈpaʊər/", "quyền lực thương lượng bất cân xứng giữa các bên", "Asymmetric bargaining power harms smaller firms."),
    ("principal hierarchy", "/ˈprɪn.sɪ.pəl ˈhaɪ.ər.ɑːr.ki/", "hệ thống cấp bậc ủy thác trong tổ chức", "The principal hierarchy clarifies accountability."),
    ("governance failure", "/ˈɡʌv.ər.nəns ˈfeɪ.ljər/", "thất bại quản trị dẫn đến tổn thất lớn", "Governance failure caused the financial crisis."),
    ("systemic risk", "/sɪˈstɛm.ɪk rɪsk/", "rủi ro hệ thống đe dọa toàn bộ kinh tế", "Systemic risk requires regulatory intervention."),
    ("creative destruction", "/kriˈeɪ.tɪv dɪˈstrʌk.ʃən/", "hủy diệt sáng tạo Schumpeter đổi mới phá hủy cũ", "Creative destruction drives capitalist progress."),
]
