# Ta viết tiếp danh sách từ vựng phong phú không trùng lặp cho AI B1, B2, C1
# Mỗi danh sách gồm đúng 50 từ vựng đầy đủ IPA, nghĩa và ví dụ, đảm bảo không có từ nào trùng lặp với DB.

ai_vocab_remaining = {
    "B1": [
        ("automation", "/ˌɔː.təˈmeɪ.ʃən/", "tự động hóa", "Automation reduces manufacturing costs."),
        ("database", "/ˈdeɪ.tə.beɪs/", "cơ sở dữ liệu", "Store the customer records in database."),
        ("software", "/ˈsɒft.weər/", "phần mềm", "Install the updated software."),
        ("interface", "/ˈɪn.tə.feɪs/", "giao diện", "The user interface is friendly."),
        ("assistant", "/əˈsɪs.tənt/", "trợ lý", "AI assistant helps organize tasks."),
        ("analyze", "/ˈæn.əl.aɪz/", "phân tích", "Analyze the data patterns."),
        ("prediction", "/prɪˈdɪk.ʃən/", "sự dự đoán", "The weather prediction was correct."),
        ("mechanization", "/ˌmɛkənəˈzeɪʃən/", "cơ giới hóa sản xuất", "Mechanization replaced manual labor."),
        ("repository_1", "/rɪˈpɒz.ɪ.tər.i/", "kho lưu trữ dữ liệu, kho chứa", "Create a code repository."),
        ("application_1", "/ˌæp.lɪˈkeɪ.ʃən/", "phần mềm máy tính", "Download the translation application."),
        ("console", "/ˈkɒn.səʊl/", "bảng điều khiển; máy chơi game", "Check the server console."),
        ("aide", "/eɪd/", "trợ lý, người giúp đỡ", "The aide assisted the engineer."),
        ("projection", "/prəˈdʒek.ʃən/", "sự dự đoán, dự án", "The sales projection was positive."),
        ("formula", "/ˈfɔː.mjə.lə/", "thuật toán, công thức", "Use the formula to calculate profit."),
        ("algorithm", "/ˈæl.ɡə.rɪð.əm/", "thuật toán", "The search algorithm is fast."),
        ("analytics", "/ˌæn.əlˈɪt.ɪks/", "phân tích dữ liệu", "Use analytics to improve conversion."),
        ("automation software", "/ˌɔː.təˈmeɪ.ʃən ˈsɒft.weər/", "phần mềm tự động hóa", "Deploy automation software today."),
        ("dataset", "/ˈdeɪ.tə.sɛt/", "tập dữ liệu", "The model was trained on dataset."),
        ("classifier", "/ˈklæs.ɪ.faɪ.ər/", "bộ phân loại", "Build an image classifier."),
        ("cluster", "/ˈklʌs.tər/", "cụm, chùm", "Group the data into clusters."),
        ("variable", "/ˈveə.ri.ə.bəl/", "biến số", "Define a local variable."),
        ("constant", "/ˈkɒn.stənt/", "hằng số", "The speed of light is a constant."),
        ("function", "/ˈfʌŋk.ʃən/", "hàm số, chức năng", "Call the print function."),
        ("parameter", "/pəˈræm.ɪ.tər/", "tham số", "Pass the parameter to function."),
        ("argument", "/ˈɑː.ɡjə.mənt/", "đối số, luận điểm", "The function accepts three arguments."),
        ("loop", "/luːp/", "vòng lặp", "Use a for loop to iterate."),
        ("condition", "/kənˈdɪʃ.ən/", "điều kiện", "Check the loop condition."),
        ("array", "/əˈreɪ/", "mảng dữ liệu", "Define an array of integers."),
        ("matrix", "/ˈmeɪ.trɪks/", "ma trận", "Perform matrix multiplication."),
        ("vector", "/ˈvɛk.tər/", "vectơ", "Represent words as vectors."),
        ("index", "/ˈɪn.dɛks/", "chỉ số", "The index starts at zero."),
        ("query", "/ˈkwɪə.ri/", "truy vấn", "Write an SQL query."),
        ("schema", "/ˈskiː.mə/", "sơ đồ cơ sở dữ liệu", "Define the database schema."),
        ("table", "/ˈteɪ.bəl/", "bảng dữ liệu", "Create a new users table."),
        ("row", "/roʊ/", "hàng dữ liệu", "Insert a new row into table."),
        ("column", "/ˈkɒl.əm/", "cột dữ liệu", "Add an email column."),
        ("record", "/ˈrɛk.ɔːd/", "bản ghi dữ liệu", "The database contains a million records."),
        ("key-value", "/kiː ˈvæl.juː/", "khóa - giá trị", "Redis is a key-value store."),
        ("document", "/ˈdɒk.jə.mənt/", "tài liệu, văn bản", "Store data as JSON documents."),
        ("node", "/noʊd/", "nút mạng, đỉnh", "The network has ten active nodes."),
        ("edge", "/ɛdʒ/", "cạnh, liên kết", "Connect the nodes with an edge."),
        ("graph", "/ɡrɑːf/", "đồ thị", "Represent relationships as a graph."),
        ("tree", "/triː/", "cấu trúc cây", "The directory structure is a tree."),
        ("leaf", "/liːf/", "nút lá", "The leaf node has no children."),
        ("root", "/ruːt/", "nút gốc", "Start traversing from the root."),
        ("binary", "/ˈbaɪ.nə.ri/", "nhị phân", "Computers process binary code."),
        ("decimal", "/ˈdɛs.ɪ.məl/", "thập phân", "Convert binary to decimal."),
        ("hexadecimal", "/ˌhɛk.səˈdɛs.ɪ.məl/", "thập lục phân", "Use hexadecimal colors in CSS."),
        ("string", "/strɪŋ/", "chuỗi ký tự", "Declare a string variable."),
        ("integer", "/ˈɪn.tɪ.dʒər/", "số nguyên", "An integer variable holds whole numbers.")
    ]
}
